Enterprise-CMCS/cmcs-eregulations

run.sh

- check that a git patch can be applied before applying it.
- allow regulations-parser docker to be built from cache.

EREGCSC-64 Exit run.sh on error

---

config/regulations-site/local_settings.py
docker-compose.yml
guidance/content/guidance/435-905.html
guidance/content/guidance/blank.html
guidance/content/regulations/sidebar/guidance.html
guidance/guidance.py

Guidance can now be authored for a a specific regulations part, e.g. 435-905, by adding a html file at `guidance/content/guidance/435-900.html.
This adds a `guidance` sidebar that pulls an html template by the requested reg and sub part if it exists.

EREGCSC-58 Create a "guidance" sidebar of hardcoded html

---

config/regulations-core/serverless.yml

Before this the configuration created it's own VPC.
This change uses existing VPC infrastructure referenced via IDs stored in ssm.

EREGCSC-69 Use existing vpc infrastructure

---

.github/workflows/deploy.yml

Before this builds would break as the `make clean` command no longer exists for static assets

Remove depricated make clean call in gh actions

---

config/regulations-site/local_settings.py
load_data.sh

- Removed help from sidebar
- Removed dependency on django.contrib.contenttypes & django.contrib.auth apps
- Disabled notice-comment app
- Additionally, modified load_data.sh to run in bash instead of sh due to conflicts on some setups

EREGCSC-104 Disabled unused content from regulations-site

---

config/regulations-site/Dockerfile

This removes the dependency on node.js as well as giving us access to Python 3.9 and its features. It also brings our local dev environment more up-to-date with the production environment.

EREGCSC-178 Update Dockerfile to use python:3-alpine instead of node:6

---

guidance/content/regulations/toc-section.html
guidance/content/regulations/toc-sub-toc.html
guidance/content/regulations/toc-subjgrp.html
guidance/content/regulations/toc-subpart.html

Before this orphaned sections wouldn't display their names etc. this
fixes that edge case.

Allow for sections to be orphans in the toc

---

CONTRIBUTING.md
LICENSE.md
README.md

These licensing files match the language used in other eRegs projects, to support reuse and interoperability. Examples: https://github.com/18F/atf-eregs/blob/master/LICENSE.md + https://github.com/eregs/regulations-site/blob/master/CONTRIBUTING.md
Also added a summary to the readme to orient readers from other regs projects.

Add license files + add a bit of context to readme

---

guidance/content/regulations/generic_universal.html
guidance/content/regulations/landing_433.html
guidance/content/regulations/recent-changes.html

Replaced hard-coded links with Django's 'url' function, e.g. {% url 'chrome_section_view' 'a' 'b' %}
When running under a subdirectory, hard-coded links would not work correctly.

EREGCSC-230 Fix hard coded urls to allow for prefix path (e.g. /dev)

---

config/regulations-site/serverless-experimental.yml
config/regulations-site/serverless.yml
guidance/content/regulations/sidebar/print_part.html

Increase timeout for regulations-site lambda function.
Before this a timeout would happen when loading a full part.
Depends on: https://github.com/CMSgov/regulations-site/pull/13

[Dependency] Bump regulations-site lib to - 7c7d586

---

Makefile
config/regulations-parser/Dockerfile
docker-compose.yml

This allows the local instance of the parser to run in a docker-compose environment and dynamically update with it's code.

Use minimal Dockerfile for local parser

---

Makefile

Node modules weren't being installed by make

fix: update storybook makefile entry

---

.github/workflows/deploy.yml

Should allow easy updating of default branch name.

Use new $default-branch macro in deploy gh action

---

serverless/static-assets/serverless/serverless.yml

version 1.5 changed the form of the variables needed in serverless.yml
https://github.com/aghadiry/serverless-cloudfront-invalidate/compare/v1.4.0...v.1.5.0#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R95-R135

Update cloudfrontInvalidate to be an array

---

regulations/templatetags/paragraphs.py

Before this paragraphs with two identifiers, e.g. `(a)(i)`, were underindented.

EREGCSC-732 Fix paragraph depth

---

cmcs_regulations/context_processors.py
cmcs_regulations/settings.py
regulations/templates/regulations/base.html
serverless/serverless.yml

Google Analytics Measurement ID is stored in AWS parameter store so it is not stored in source control.  This pulls that ID from AWS and adds it to app context so it can be references in a template

feat: pull GA_ID from AWS parameter store and pipe into template

---

.github/workflows/deploy.yml

https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#literals

EREGCSC-880 fix: must use single quotes for string literals

---

regulations/converters.py

fixes the regex for URL's to include one for identifiers in the format of "A-B" that we have begun seeing in the most recent ECFR results.

updating regex to allow for A-B and A to match as valid URL's

---

tools/ecfr-parser/ecfr/ecfr.go
tools/ecfr-parser/eregs/eregs.go
tools/ecfr-parser/main.go
tools/ecfr-parser/parseXML/parseXML.go

Utilizing thread pool to limit active connections to 3 at a time. User-configurable via command-line argument "-threads".
Also improved some logging messages. E.g.: changed "[MAIN]" to "[main]" for easier reading.

EREGCSC-1022 Revise eCFR API fetch strategy

---

.github/workflows/deploy-experimental.yml
serverless/populate_content.py
serverless/serverless-experimental.yml

Using an R(4/5/6).large database was just not required here so I have updated the experimental deploys to use a T4.medium DB as this is the smallest one I can use with the aurora engine.  I also added back in a data load step so now the fixture data will be loaded into the experimental deploys when they are created.

Smaller experimental deploy db's

---

.github/workflows/load-regulations.yml
tools/ecfr-parser/ecfr/ecfr.go
tools/ecfr-parser/eregs/eregs.go
tools/ecfr-parser/main.go

* Allows jobs to continue if one fails
* Also fixes leaking file descriptors during post to eRegs. Does NOT fix leak in ecfr.go's fetch function. This is temporarily needed for Github Actions.

Disable fail fast for LoadRegulations action

---

cmcs_regulations/settings.py
cmcs_regulations/urls.py
config/static-assets/nginx_fonts.conf
regulations/static/regulations/robots.txt
regulations/templates/regulations/base.html
requirements.txt

I added a robots.txt file at http(s)://url.com/robots.txt that will deny all traffic.  I also added in the header of X-Robots-Tag to django and static asset requests.  All of this can be confirmed with the network console.

Prevent Site from being scraped by search engines

---

tools/ecfr-parser/ecfr/versions.go

This seems to be choking strictly on versions from 2016 so in the case of a 2016 version the parser will adjust the date of the version to 2017-01-01.  This appears to be relatively consistent across the board, but I will also be following up with the ECFR team.

EREGSCSC-1022 - Make ECFR parser more reliable

---

serverless/serverless-experimental.yml
serverless/serverless.yml

This exposes the STATIC_URL variable that is required for the report admin migrations to succeed.  It is confirmed on the experimental deploys.

fixes problem with missing environment variables in migration process

---

Dockerfile
requirements.txt

You will need to clean and rebuild your containers to validate this.  You can even remove a requirement and see that the system doesn't come up because this file is being used.

Remove duplicate requirements.txt

---

regulations/templates/regulations/about.html

As part of EREGCSC-950 I want to take a different approach here (demo video with description), but it'll take a certain amount of time, and for now it's best to remove the outdated material to avoid confusion. I could not find anywhere that this section is currently referenced from, so I don't think I'm breaking any links.

Remove "Using this Tool" section from about page

---

regulations/templates/regulations/about.html

Add brief explanation and video link to the top of the about page; small updates to SME section. This should have team content review before merging.

EREGCSC-950 Add explainer to "about" page

---

tools/ecfr-parser/main.go

Resolves #1114
Error received when uploading supplemental content sections & subparts for some parts to eRegs, causes parser to fail with an exit code after 3 attempts. This is caused by a race condition where the parser is attempting to upload supplemental data for multiple versions of a single part simultaneously.
Now each worker thread sequentially processes an entire batch of all versions of a given part. This way, there's no chance of duplicate supplemental sections and subparts being created as no 2 versions can be simultaneously processed.
1. Run `make data.local` on a clean database
2. Verify no parser errors in terminal ("Successfully processed 122/122 versions")
3. Create Django Admin …

EREGCSC-1114 Parser fails while uploading supplemental content sections sometimes - error 500

---

supplemental_content/admin.py

Resolves #1110
- Admin panel to display 200 items per page rather than 500.
1. Visit admin panel and click Supplemental Content
2. Verify it is only displaying 200 items per page.

EREGCSC-1110 changed items per page to 200 in admin panel

---

solution/Makefile
solution/docker-compose.opensearch.yml

Resolves # 1131
This PR adds a docker environment for running Opensearch locally. It runs on localhost:5601
- Adds docker-compose.opensearch.yml
- Adds `make local.opensearch` to the Makefile
1. Run `make local.opensearch`
2. Check http://localhost:5601 to see if Opensearch Dashboard is running.

EREGCSC-1131 Opensearch Docker

---

solution/backend/supplemental_content/admin.py

Made whole row clickable  for supplemental content table in django admin.  Added a value of "NONE" if there is no value assigned.  No impact on database just in place of "-"

Made row clickable django admin

---

.github/workflows/deploy-experimental.yml
.github/workflows/deploy-prototype.yml
solution/ui/prototype/src/App.vue

Resolves # 1175
Deploys prototype site after reg site allowing prototype site to be aware of the reg_site url
- the order of deployment.  prototype site is no longer a separate step and happens after reg_site is deployed
- prototype site logs the api_url to the console to verify it is accurate
1. Go to prototype site
2. look at console.log and ensure it prints the right URL.

change deploy order of prototype site

---

solution/backend/regulations/templates/regulations/partials/node_types/Image.html
solution/parser/ecfr-parser/parsexml/parsexml.go
solution/parser/ecfr-parser/parsexml/parsexml_test.go
solution/ui/regulations/css/scss/partials/_reg_text.scss

Resolves #1148
Image references in eCFR source XMLs are of the format: `/graphics/{image}.{ext}` or `/graphics/{image}.eps.{ext}`. These references no longer resolve, and are now instead hosted on the Federal Register servers.
- If source is `/graphics/{image}.{ext}`, parser rewrites to `https://images.federalregister.gov/{image uppercase}/large.png`. (E.g. `/graphics/ec14no91.132.gif` -> `https://images.federalregister.gov/EC14NO91.132/large.png`)
- If source is `/graphics/{image}.eps.{ext}`, parser drops "eps" extension and rewrites like above.
- Unit test is written for all cases, see bottom of parsexml_test.go.
**NOTE**
If "skip versions" is set in the parser's configuration, image URLs will not be rewritten on deploy. Remember to …

EREGCSC-1148 Fix missing formula image in 433.10(c)(8)

---

solution/backend/package-lock.json
solution/backend/package.json
solution/backend/serverless-experimental.yml
solution/static-assets/serverless.yml
solution/ui/regulations/js/src/components/SupplementalContent.vue
solution/ui/regulations/js/src/components/SupplementalContentCategory.vue

Resolves Bug with Categories that show up before the Ajax call has finished
When content is fetched that ends up "above" Subregulatory Guidance (or any category that shows if empty) ends up not working as expected.  https://regulations-pilot.cms.gov/42/435/Subpart-B/2019-05-06/#435-100 is fine because the "new" content comes "lower" than the existing categories.  437 Subpart A on the other hand does not work quite right because of this.
- The key for category expanders to be by category name instead of index
View bug report here  https://fearless.slack.com/archives/C02DL6UU076/p1645121069963989
Go to 437 subpart A (in production) and confirm that the expanders for resources don't work.   
Using …

changing key to category.name instead of index as index is volatile.

---

solution/backend/regulations/templates/regulations/partials/node_types/APPENDIX.html
solution/backend/regulations/templates/regulations/partials/node_types/Paragraph.html

fix: use copy-btn vue cmpnt in appendix django template; better safet…y when encountering NoneType
Resolves [EREGCSC-1213](https://jiraent.cms.gov/browse/EREGCSC-1213)
Appendix to Subpart F of Part 441 has not been displaying on the [Pilot site](https://regulations-pilot.cms.gov/42/441/Subpart-F/2021-11-05/#441-259).  Instead, the word "None" is being rendered in its place.  
Additionally, clicking on the Appendix link in the left sidebar does nothing. 
Finally, clicking on the link to the appendix at the bottom of the Subpart F sections on the [Part 441 Table of Contents page](https://regulations-pilot.cms.gov/42/441) does not take you to the Appendix location in the reader view; instead [it takes you to the top of Subpart …

EREGCSC-1213 - Show Appendices properly

---

solution/backend/regulations/templates/regulations/partials/node_types/Paragraph.html
solution/ui/regulations/css/scss/partials/_search.scss

Resolves two issues:
1. on Pilot site where Copy Link tooltip would not show the formatted citation for paragraph nodes.
2. on Pilot site search page, text input was missing border
In a previous bugfix story, I removed a templatetag in the paragraph node that created a formatted citation to be used in the copy link/copy citation tooltip.
In another story, styling the prototype header search input removed the border from the pilot site's search page text input.
**This pull request changes*
Adds `paragraph_formatter` templatetag back into paragraph node template.
Adds border styling back to pilot site search page's text input while not affecting the prototype's style.
To test paragraph formatted citation:
1. Go to the pilot site and …

bugfix: add formatted citation templatetage back to pgraph node

---

solution/ui/prototype/src/components/PDPart/SectionCards.vue
solution/ui/prototype/src/components/SectionResources.vue
solution/ui/prototype/src/components/SectionResourcesSidebar.vue
solution/ui/prototype/src/components/node_types/Node.vue
solution/ui/prototype/src/components/node_types/Section.vue
solution/ui/prototype/src/components/node_types/Subpart.vue
solution/ui/prototype/src/components/part/PartContent.vue
solution/ui/prototype/src/views/PDPart.vue
solution/ui/prototype/src/views/Part.vue

Resolves #EREGCSC-1226 and #EREGCSC-1229
Cleans up some interactions between the PD and JS views. Ensures that buttons for "Show Resources" only show if there are resources to show.
- Show Resources button only shows if that subpart or section resource has resources.  For subpart this means supplemental content directly on the subpart.  For the PD view the blue button will show content for all sections in that subpart.  
1. on 42/400 none of the subparts have supplemental content so those buttons should not show.
2.on 42/441 subpart B has content so should show up.  
3. 400.202 has no supplemental content so no show resources button should show.

EREGCSC-1226 hide show resource buttons

---

.github/CODEOWNERS
.github/workflows/deploy.yml

Resolves #1239
Adds deployment of the prototype site to the main deployment process.  This will allow for a static, non changing URL for the prototype site that connects to the production database.
- deployment action adds a section for deploying the prototype.
1. This can not be verified until it the PR is approved and the deployment action is run.
2. When the deploy script runs it should print the cloudfront ID to the console.  Otherwise the URL should be available on the AWS console.  That URL should show the prototype site.

copied in deployment for prototype site.

---

solution/ui/prototype/package.json
solution/ui/prototype/src/components/SectionResources.vue

Resolves #1241
In order to have a smooth usability test flow, we should mend the following gaps identified in our 3/22 walkthrough:
- In JS drawer version, "Show All Resources" button at the top of the drawer should say "View All Resources".
1. Visit `/42/433` and click on "View Section Resources" for any section
2. Verify correct link text

EREGCSC-1241 Consistent "View all resources" buttons in JS and PD

---

solution/backend/supplemental_content/views.py
solution/ui/prototype/src/components/PDPart/Breadcrumbs.vue
solution/ui/prototype/src/components/PDPart/LeftColumn.vue
solution/ui/prototype/src/components/PDPart/RightColumn.vue
solution/ui/prototype/src/components/PDPart/SectionCard.vue
solution/ui/prototype/src/components/PDPart/SectionCards.vue
solution/ui/prototype/src/components/PDPart/SubpartSupplemental.vue
solution/ui/prototype/src/components/PDPart/TabFilters.vue
solution/ui/prototype/src/components/node_types/SubjectGroup.vue
solution/ui/prototype/src/components/node_types/Subpart.vue
solution/ui/prototype/src/utilities/api.js
solution/ui/prototype/src/utilities/utils.js
solution/ui/prototype/src/views/PDPart.vue

Prototype cleanup first pass.  Fixes many, but not all issues found in validation.
Clicking on the blue button next to a section will switch the right side to the section tab and fetch the resources for that section
Section tab title shows the number of pieces of content shown
Clicking on a blue button next to a sub part switches to the subpart tab, but does notexpand any subpart
Subpart resources section works more like the prod site and include content for all sections in that sub part.
Expanding relevant regulations shows a formatted list with links of the other related content
Expanding relevant regulations on one piece of content no longer expands all pieces of content
Entire bottom section of supplemental content card is now …

Prototype cleanup 1

---

solution/ui/prototype/src/components/JumpTo.vue

Resolves #1246
"activates" the go button in the Jump To section to turn blue when title and part are selected
Go button keeps you in the same "version" for PD vs non PD and drawer vs sidebar.
Go button in the header turns blue when title and part are selected
The navigation when clicking Go to keep you in the right version.
1. select a title and part, see the button turn blue
2. in the PD view choose a title and part and click Go, you should stay in the PD version
3. In the sidebar version select a title and part and click go, stay in the sidebar version
4. repeat above for the drawer version

go button should keep you in the same "version" of the site

---

solution/ui/prototype/src/components/homepage/Hero.vue

Resolves #1243
In order to help us get good feedback testers who end up on the eRegs prototype homepage, we should have some reasonably realistic copy that they can react to, rather than just a small bit of text.
- Homepage hero now has text "eRegulations organizes together regulations, subregulatory guidance, and other related policy materials."
1. Visit prototype homepage and verify hero looks correct with new header text.

EREGCSC-1243 [Prototype] Adjust homepage copy

---

solution/ui/prototype/src/components/resources/ResourcesResults.vue
solution/ui/prototype/src/views/Resources.vue

Filtering by a subcategory in option A always returns 0 results due to the supplemental content tree not being flat.
- Flattens supplemental content tree
- Removes duplicate entries (that are created due to tree flattening)
1. Visit `/resources` on the prototype and filter by a category, then a subcategory, then both.

Fix subcategory filtering for option A

---

solution/ui/regulations/css/scss/partials/_sidebar_right.scss

Resolves [EREGCSC-1092](https://jiraent.cms.gov/browse/EREGCSC-1092)
We want to add a little extra space below the last item in the sidebar.
- Changes right sidebar bottom padding from 16px to 40px
- Shortens right sidebar height by 40px
1. Visit the reader view for any subpart and expand some supplemental content so that the right sidebar content is taller than the container.  
- example: [42 CFR 435 Subpart A experimental deploy](https://01fzvhvqfh.execute-api.us-east-1.amazonaws.com/dev-386/42/435/Subpart-A/2019-05-06/) 
- vs [42 CFR 435 Subpart A on the Pilot Site](https://regulations-pilot.cms.gov/42/435/Subpart-A/2019-05-06/)
2. Scroll to bottom of right sidebar content.  
3. There should be some …

EREGCSC-1092 - Extra space at bottom of right sidebar

---

solution/backend/regcore/v3views.py

Resolves #1255
As a user I want all pages of eRegs to load as fast as possible. Currently, we need to determine the most recent version of the regulations from a list of versions before requesting content for that version.
- /v3/title/<title>/part/<part>/version/<version>/toc accepts "latest" as <version>
1. Visit /v3/title/42/part/433/version/latest/toc and verify the correct data is returned

EREGCSC-1255 Make "latest" work as a valid date string for V3 API calls

---

solution/backend/cmcs_regulations/settings.py
solution/backend/regcore/middleware/html_api.py
solution/backend/regcore/templates/response.html

Resolves #1259
As a developer I need to be able to debug API endpoints quickly and effectively. Although we have the ability to use Django Debug Toolbar for frontend pages, it won't work on backend pages because those responses are in JSON.
- Adding `?html_api` to the end of any API call returns the JSON response as basic HTML. (Changed from `?debug` to be more precise.)
1. Visit any API page, e.g. `/v3/title/42/part/433/version/2021-03-01/toc` and append `?html_api` (`/v3/title/42/part/433/version/2021-03-01/toc?html_api`)
2. Verify that the JSON content returned is correct, and view page source to verify that it is wrapped in HTML tags
3. Verify that Django Debug Toolbar appears as expected

EREGCSC-1259 Add middleware to render API responses as HTML so Django Debug Toolbar works

---

.github/workflows/ecfr-parser-checks.yml
solution/parser/ecfr-parser/main.go

Resolves #
"go get" is deprecated in more recent versions of Go. We used "go get" to install the linter used in Github Actions.
- We now "go install" the linter
1. Make sure the linter successfully runs on this PR. No other checks need to be run.

Fix Go linting in Github Actions

---

solution/backend/regcore/search/models.py

Resolves #1094
Explicitly adds an english config to the search queries.
- Stemming, search vector creation and highlighting should all be different now.
1. Searching for "State Medicaid Manual" with and without the quotes.  With quotes should be more specific and return fewer results
2. Search for:    
Application, applications
Demonstration, demonstrations
Authority, authorities
Disability, disabilities 
3. you should see similar results for both terms.  Search results should be more inclusive of the highlights.  For example Disability should include "Disabled" as a highlighted word in the results indicating it was in fact searched for.

Explicitly setting the search config to english and allowing quoted search terms

---

solution/backend/regulations/templates/regulations/base.html
solution/backend/regulations/templates/robots.txt

Resolves #EREGCSC-1240
Makes robots.txt use https (it would forward, but explicit https is better).  Removes noindex meta tag from base template.
1. go to /robots.txt and see it use an https link
2. view source on any page and look for the absence of the robots meta tag.

making URL for robots.txt https and removing no index meta tag from base template.

---

solution/backend/regcore/models.py
solution/backend/regcore/serializers.py
solution/backend/regcore/urls.py
solution/backend/regcore/v3views.py

Resolves #1253
As a developer it is necessary to retrieve a table of contents for titles, parts, and more. Ideally we want to retrieve only the data necessary to facilitate this.
The following new V3 endpoints exist:
- `/v3/title/<title>/toc`
Retrieve table of contents for one title only (extension of /v3/title/<title>)
- `/v3/title/<title>/part/<part>/version/<date>/subpart/<subpart>/toc`
Retrieve table of contents for a specific subpart down to the section level
**This pull request does NOT change...**
Originally a `/v3/title/<title>/part/<part>/version/<date>/section/<section>/toc` endpoint was planned, but this was done under the incorrect assumption that the `structure` field contains data down to the paragraph level. It doesn't, so …

EREGCSC-1253 Create additional table of contents endpoints

---

solution/backend/regcore/search/views.py
solution/backend/regcore/serializers.py
solution/backend/regcore/urls.py
solution/backend/regcore/v3views.py
solution/backend/regcore/views.py
solution/backend/supplemental_content/views.py
solution/ui/e2e/cypress/integration/swagger.spec.js

Resolves #1284
New V3 serializers broke Swagger because fields must be explicitly defined for Swagger to work.
- ViewSets and Serializers are rewritten so that Swagger works.
- Additionally, endpoint and parameter descriptions have been added for all V3 endpoints.
1. Visit `/api/swagger` and verify the page loads and endpoints have proper parameters and response templates.
2. Verify that V3 endpoints have correct endpoint and parameter descriptions.

EREGCSC-1284 Make Swagger API documentation work again

---

solution/backend/regcore/search/models.py
solution/backend/regcore/search/views.py
solution/backend/regulations/templates/regulations/search.html
solution/backend/regulations/templatetags/string_formatters.py

Resolves [EREGCCS-1289](https://jiraent.cms.gov/browse/EREGCSC-1289)
In search results, highlight terms when they are in document names.
- Adds new annotation to SearchIndex object that highlights the search query in the Section title
1. Visit experimental deployment's [Search page](https://xmuylu2ao4.execute-api.us-east-1.amazonaws.com/dev-403/search/) 
2. Search for a term or quoted phrase
a. example: "therapy"
3. Notice that the search query will be emphasized in the section name if present
4. Compare same search query against pilot site to see that the query is not emphasized in the section name if present

EREGCSC-1289 - Highlight search query in document name

---

solution/backend/regcore/serializers.py
solution/backend/regcore/v3views.py

Resolves #1284
New serializer structure for Swagger compliance broke posting and putting to `/v3/title/<title>`. Fixed by creating a ModelSerializer for these operations.
- Parser now works again.
1. Start with a clean database or disable "skip versions" and try to run the parser.

EREGCSC-1284-B Fix error when creating or updating a Title object

---

.github/workflows/deploy.yml
.github/workflows/remove-experimental.yml
solution/backend/supplemental_content/serializers.py
solution/parser/fr-parser/fedreg/fedreg.go
solution/parser/fr-parser/fedreg/fedreg_test.go
solution/parser/fr-parser/main.go
solution/parser/fr-parser/main_test.go

Resolves #1322
In order to improve runtime of the new FR parser, we need to cut out as many requests as possible. The parser currently fetches full text XML to extract sections, however many older documents have no such documents and the request returns 404.
- Added `&fields[]=full_text_xml_url` to the federalregister.gov API request
- Only attempt to fetch XML if `full_text_xml_url` is a string of non-zero length
1. Run `make frdocs.local` and look for logs indicating `[main] No list of sections available for FR doc [document number]`

EREGCSC-1322 Improve FR parser: don't try to fetch documents that don't exist

---

solution/backend/supplemental_content/serializers.py

Resolves #EREGCSC-1319
Creates a category when a piece of federal register content is uploaded that has a type that is not recognized.
1. Check the number of categories you have (should be 10)
2. Run make frdata.local 
3. You should have 12 categories instead of the previous 10.

1319 create unknown categories

---

solution/backend/regcore/serializers.py
solution/backend/regcore/v3views.py
solution/backend/supplemental_content/v3urls.py
solution/backend/supplemental_content/v3views.py
solution/parser/fr-parser/eregs/eregs.go
solution/parser/fr-parser/eregs/eregs_test.go
solution/parser/fr-parser/main.go
solution/parser/fr-parser/main_test.go

Resolves #1323
To improve parser runtime we want to skip docs that we have already fetched and processed.
- Parser fetches a list of URLs of processed content from eRegs
- All content retrieved from Federal Register that is in that list is skipped from processing
1. Make sure "Skip versions" is disabled in your parser configuration
2. Run `make frdocs.local`.
3. If this is the first time you've run the above, run it again. Runtime should be significantly lower.

EREGCSC-1323 Improve FR parser: skip docs we've already fetched

---

solution/backend/regulations/templates/regulations/search.html
solution/backend/regulations/views/search.py
solution/ui/regulations/css/scss/partials/_search.scss

Resolves #EREGCSC-1279
Showing users how they might be able to improve their results with quoted search
- added 2 variables to the search template context
- updated template to show desired words about quoted search
1. if a search has 2 or more words and is NOT quoted the page should show "Didn't find ..."  
2. If there are synonyms it should say "Or search..."
3. All other searches should be unchanged.

updating UI to show users when quoted search might help.

---

solution/backend/regulations/templates/regulations/partials/recent_changes.html
solution/backend/supplemental_content/serializers.py
solution/backend/supplemental_content/v3views.py
solution/parser/fr-parser/main.go

change the frdocs_list to return document numbers instead of URL's as they are the most unique identifier we have.
Just the one endpoint
removed some incorrect code from the NPRM template
1. v2/frdocs_list should be document numbers instead of url's
2.

frdoc_list now returns document_numbers 

---

solution/ui/prototype/src/components/custom_elements/SectionList.vue
solution/ui/prototype/src/components/custom_elements/SubpartList.vue
solution/ui/prototype/src/components/resources/ResourcesSelections.vue
solution/ui/prototype/src/utilities/api.js
solution/ui/prototype/src/views/Part.vue
solution/ui/prototype/src/views/Resources.vue

Resolves # EREGCSC-1333, EREGCSC-1324
The query string for searching for supplemental content.  New version prevents selected sections and subparts are tied to a part.
Also modifies chip to a new format display part and subparts correctly.
V1. Click on the resources page on prototypes, select a couple filters, will update the query string and results. 
V2.  Select a part on from the prototype.  Click a view resources box.  Click view all resources.

New routing for url for section and part search

---

solution/ui/regulations/eregs-vite/src/components/resources/ResourcesResults.vue
solution/ui/regulations/eregs-vite/src/views/CacheExplorer.vue
solution/ui/regulations/eregs-vite/src/views/Resources.vue

Resolves bug found when EREGCSC-1300 deployed to prod
Certain Parts returned from production v2's `all_parts` endpoint do not have `parent` and `parent_type` fields nested deep in an array of sections in a subpart.  Example: Part 436.
The resources page code was not handling these omissions, and was choking when they were found; these data issues were not present in dev v2's `all_parts` endpoint, which is why this was not caught during development.  As such, a hotfix is needed to handle these prod data omissions, and this PR is it.
Note: v3 endpoints that return the same data (more efficiently) have corrected these data omissions; we will be migrating to v3 in the near future.
- Adds safeguards to prevent reaching into an `undefined` value as …

Bugfix cache rsrcs

---

.github/workflows/deploy-experimental.yml
.github/workflows/deploy.yml
solution/ui/regulations/eregs-vite/src/components/resources/ResourcesResults.vue
solution/ui/regulations/eregs-vite/src/router/index.js

Resolves issue where Vue Router and Related Resources links do not work with dev/val URLs on deployment, e.g. https://qavc1ytrff.execute-api.us-east-1.amazonaws.com/dev and ./val
When deploying eRegs to production, the production-ready code is also deployed to the `dev` and `val` environments.  The URLs for these deployments have "dev" and "val" subdirectories, which is not handled by the code and the Vue router does not work.  This means that the Resources page and the Cache Explorer do not load when visiting the `dev` and `val` URLs.
Mirroring the work down for deploying the experimental site, a `VITE_ENV` variable will be passed in to the Vue/Vite app and used where necessary for the router to direct the user to the proper route.
- …

Fix: Resources deploy properly to dev/val environments on Prod deployment

---

.github/workflows/deploy.yml
solution/ui/regulations/eregs-vite/src/views/Resources.vue

Resolves #
- Makes .env file available for Vite building to have the correct URL for the desired environment.
- Build Vite resources after Django site is deployed
- Build and deploy storybook to protoype site
1. Pipeline needs to run successfully
2. prototype.site/storybook/index.html should work
3. resources page should access API via the right URL (once PR #430 is merged in)

updating pipeline for storybook and vite environment variables

---

solution/ui/regulations/eregs-vite/src/components/resources/ResourcesResults.vue

Resolves #
Currently this.base is undefined in the resources results component.  This leads to incorrect URL's in the locations.  
- passes base as an argument to the filter
1. On the resources view the location links should work for every resource shown.

changing how base gets passed into the filters.

---

solution/ui/prototype/src/components/custom_elements/FancyDropdown.vue
solution/ui/prototype/src/components/custom_elements/SubpartList.vue
solution/ui/prototype/src/components/part/PartNav.vue
solution/ui/prototype/src/components/part/PartSection.vue
solution/ui/prototype/src/components/part/PartSubpart.vue
solution/ui/prototype/src/components/resources/ResourcesSelections.vue
solution/ui/prototype/src/router/index.js
solution/ui/prototype/src/views/Part.vue

Resolves [EREGCSC-1384](https://jiraent.cms.gov/browse/EREGCSC-1384) and [EREGCSC-1385](https://jiraent.cms.gov/browse/EREGCSC-1385)
Implements Part-view tab behavior in the Part view of the prototype for the Multi-View Nav concept.  See Figma [here](https://www.figma.com/proto/OI3yDAbymYvHU3L7gTkhxR/eRegs-Multi-View-Nav-%26-View-Switching?page-id=2701%3A3601&node-id=2701%3A4567&viewport=-855%2C1864%2C0.07&scaling=scale-down&starting-point-node-id=2701%3A3615).
- Enables TOC/Part/Subpart/Section tab navigation on the Part view of the prototype
- Adds "split-tab" button functionality to Subpart and Section tabs
- Extends the existing FancyDropdown component to be used as split tab button with chevron label
- Clicking the down chevron on the …

EREGCSC-1385 -- Section (and Subpart) picker

---

solution/ui/regulations/eregs-vite/src/views/Resources.vue

Resolves # EREGSCSC-1321
We want to make it so that if you search a location ex. 400.200 you will update the filters with the appropriate chips
Type in 400.200 into the search bar.  It should add the chips for part 400 and section 400.200
Clear the results.  Type in 400.200 hello.  No chips should be added but it will search on that as a normal query.
Type in 400.99.  No chips should be added since its an invalid section.  Will just query on 400.99
Type in 500.9.  Same behavior s above
It will work for any valid part/section combination.  It will check the part first to see if the part number is valid, then check the section number to see if …

Search by location and add chips

---

.github/workflows/deploy-experimental.yml
solution/parser/ecfr-parser/ecfr/ecfr.go
solution/parser/ecfr-parser/ecfr/ecfr_test.go
solution/parser/ecfr-parser/ecfr/structure.go
solution/parser/ecfr-parser/ecfr/structure_test.go
solution/parser/ecfr-parser/main.go
solution/parser/ecfr-parser/main_test.go
solution/parser/fr-parser/main.go
solution/parser/fr-parser/main_test.go

Resolves #
The ECFR parser has been failing because requesting today's date is no longer valid.  This will use "current" instead of the actual date.
- ECFR parser should work as normal
1. Github actions should all just work.

Fixing ECFR to use current instead of today's date

---

.github/workflows/deploy-experimental.yml
solution/ui/regulations/eregs-vite/src/views/Resources.vue

Resolves #
On the resources page if you select only a category the filtering does not happen.  A part is currently required to make category filtering work, which isn't right.  Someone should be able to filter for a category without choosing a part first.
- a small check for part Dict is skipped if not parts are selected.
1. Go to resources page, change the category.  On Prod nothing will happen, on this branch it should search for all resources that have that category.

Category only Filtering bug

---

solution/ui/prototype/src/components/PDPart/LeftColumn.vue
solution/ui/prototype/src/components/part/PartToc.vue
solution/ui/prototype/src/views/PDPart.vue

Resolves #EREGCSC-1401
Fills in Table of Contents on the PD Part views
Styles up the expander for TOC
adds the partTOC element to the expansion panel
Passes a navName to the part TOC so it can do slightly different nav for each implementation
1. Go to PD/42/433 (or any option) and look at the Tabel of contents.  clicking links should update the URL, but that will have no effect on the content.

Filling out TOC accordion on PDPart views.

---

solution/ui/prototype/src/components/Header.vue
solution/ui/prototype/src/components/part/PartHero.vue
solution/ui/prototype/src/components/part/PartNav.vue
solution/ui/prototype/src/router/index.js
solution/ui/prototype/src/views/Part.vue

Resolves [EREGCSC-1386](https://jiraent.cms.gov/browse/EREGCSC-1386)
This work affects the TABS VIEW-SWITCHING concept.
If user is in Part view and scrolls down, the Global Header disappears.
If user scrolls back up, the Global Header appears.
If user scrolls below the light blue hero/nav stripe with the navigation tabs, the navigation tabs will stick to the top of the screen.  
If user scrolls up a bit, the navigation tabs will stick to the underside of the global header, which reappears on scroll up.
- Updates header component with stick modes to hide/unhide it when scrolling.
- Re-organizes PartNav component into two components:
- PartHero that contains Part Number and Description
- PartNav that contains the navigation tabs
- Makes …

EREGCSC-1386 -- Sticky navigation for tab concept

---

solution/ui/regulations/eregs-vite/src/views/Resources.vue

Resolves #EREGCSC-1410
Fixes search for sections within a subpart that has subject groups
go to the resources page
Choose Part 433
Select Subpart D
There should be 8 more chips than on production

EREGCSC-1410 Selecting Subpart doesn't show all chips

---

solution/ui/prototype/src/components/PDPart/LeftColumn.vue
solution/ui/prototype/src/views/PDPart.vue

Resolves [EREGCSC-1421](https://jiraent.cms.gov/browse/EREGCSC-1421)
Makes Zoom concept right sidebar (the resources sidebar) match the Tab view concept.
> **Note**
> the right sidebar should NOT populate with any related resources at this time.  It should only display "Resources" as a title, and then a short paragraph blurb explaining resource links.
- Removes moveable Panes from Zoom concept
- Adds right sidebar component from Tab view and matches its width
- Minor cleanup
1. Visit prototype
2. Go to Tab part view in one tab and Zoom part view in other tab
3. Right sidebar should width and content should match in both concepts

EREGCSC-1421 -- Reduce potential confusion of zoom view sidebar

---

solution/ui/prototype/src/components/JumpTo.vue

Resolves #EREGCSC-1395
Adds Title 45 to the navigation drop down (if it has been downloaded by the parser)
- Add title 45 to the jump to drop downs on the prototype site
- disables the part drop down until a title has been selected and options retrieved from the API
Use the jump to navigation to go to several random parts in title 42 or 45.

EREGCEC-1395 Title 45 Navigation

---

solution/backend/regulations/templates/regulations/partials/jump_to.html

Resolves #1427
- on thehomepage, if you choose a section it currently assumes you want that section in title 45 if title 45 has been loaded.  This hard codes title 42 as a stop gap until we have a design that accomodates 45.
Us the navigation on the home page, it should still work as expected.  It should also work if Title 45 has been pulled from ECFR.

EREGCSC-1427 Fix Cypress tests for Title 45

---

solution/backend/regulations/views/homepage.py
solution/ui/prototype/src/components/JumpTo.vue
solution/ui/prototype/src/utilities/api.js
solution/ui/prototype/src/utilities/utils.js
solution/ui/prototype/src/views/PDPart.vue
solution/ui/prototype/src/views/Part.vue

Resolves #EREGCSC-1415
Allows for navigation to a specific section of a specific part in either title 42 or 45.  
- configures navigation from the jump to widget for either the zoom or tabbed regulation page
In both the zoom and tabbed view:
1. Navigate to:
2. an orphan section (433.1)
3. a "regular section"
4. a section in a subgroup (433.152)
5. a section AFTER a reserved subpart (438.600)
6. an invalid section (Should show part view)
7. a section that is too high (438.999)
8. a section in a subpart without a descendant range (433.400)
NOTE: You should remain in your current view.  Using zoom should not take you to the tabbed version and vice versa.

Eregcsc 1415 section navigation

---

solution/ui/e2e/cypress/integration/search.spec.js

Resolves #EREGCSC-1427
Updates the search term used in the search cypress test.  The old search term had over 1,000 results and was timing out on the dev environment.  The new term should have fewer   results and be less prone to fail
- Cypress search.spec
1. Cypress tests need to pass

EREGCSC-1427 - Change Cypress Search Terms

---

solution/ui/prototype/src/views/PDPart.vue

Resolves #
Bug in 1396.  Previous and next buttons for sections were ignoring the limit of the subpart.  This stops it by limiting the section list to the items in the subpart
next section and subpart functionality is fixed.
Go to the zoom view.  hit previous and next within a section to navigate through them.  Sections that are reserved are not able to be hit into by using "previous or next"

EREGCSC-1396 Forward/Next fix

---

solution/backend/resources/v3views.py

Resolves #1435
Due to a duplicate sort on the query, `/v3/resources/federal_register_docs` and `/v3/resources/supplemental_content` are failing.
- Remove duplicate sort on line 242 of `backend/resources/v3views.py`
1. These endpoints display correctly with no errors

EREGCSC-1435 Fix supplemental content and federal register doc V3 endpoints failing

---

solution/ui/prototype/src/views/Part.vue

Resolves #
Fixes bug when clicking on tab view section without a subpart selected.  Gets the index for the section after the subpart is determined
Go to the tab view, and click a section.  The floating buttons on the bottom will reflect the appropriate sections before and after the sbupart

EREGCSC-1438 Fixing section index bug when clicking on section first

---

solution/backend/regulations/templates/regulations/supplemental_content.html
solution/backend/resources/v3serializers.py
solution/ui/regulations/js/api.js
solution/ui/regulations/js/src/components/SupplementalContentList.vue

Resolves #EREGCSC-1290
Points supplemental content links to an internal link so that we can notify google analytics of the click.
Adds internal URL to resource serializer
uses internal URL on the sidebar to track when a user clicks
Added google analytics to interstitial page for supplemental content links
Go to any subpart, click on any link in the sidebar.  It should be ".../supplemental_content/ID". 
Go the link above in view-source and confirm GA tag is shown.

EREGCSC-1290 Track Supplemental Content Links

---

solution/ui/regulations/js/src/components/SupplementalContent.vue

Resolves [EREGCSC-1440](https://jiraent.cms.gov/browse/EREGCSC-1440)
When loading a link that has Part, Section, AND paragraph information in the location hash (e.g. `42/431/Subpart-A/2020-06-30/#431-12-a`), the resources in the resources sidebar do not load.
The expected behavior would be that the sidebar would load the resources for the containing section (e.g. Part 431 section 12).
- Adds a condition that checks for paragraph information in location hash and strips it out of request for supplemental resources
1. Load a link that has a hash containing paragraph information (e.g. `42/431/Subpart-A/2020-06-30/#431-12-a`)
2. Make sure the right sidebar loads resources related to the parent section
3. …

EREGCSC-1440 -- Load resources when loading linking to paragraph

---

solution/ui/regulations/js/src/components/SupplementalContent.vue
solution/ui/regulations/js/src/components/SupplementalContentList.vue
solution/ui/regulations/js/utils.js

Resolves #EREGCSC-1426
Fixes a bug in the subpart resources section.  When subparts have sections in them that are in subject groups, the sections are not requested from the API
FIxes how the list of locations is determined when populating the resources sidebar
Go to 42.435 subpart J.  In the resources sidebar there should be over 100 resources.  Production has appx 5 currently.

EREGCSC-1426 Include sections in subject groups in resources sidebar

---

solution/ui/regulations/eregs-vite/src/views/Resources.vue

Resolves #EREGCSC-1376
When selecting a parent category the subcategories should be selected too.  This is like how subpart selection works.
- Adds subcategory chips when parent category is selected
Add a parent category, see subcateogry chips get added
select a duplicate category to add, confirm it doesn't duplicate
Add another top level category and see many subcategories get added
Any other things you feel like testing

EREGCSC-1376 Adding in sub categories when a parent category is chosen.

---

.github/workflows/deploy-experimental.yml
solution/backend/createdb.py
solution/backend/regcore/migrations/0002_parserconfiguration_titleconfiguration.py
solution/backend/serverless-experimental.yml

Resolves #EREGCSC-1431
A small refactor of our initial deployment process.  Instead of copying a reference DB, we simply create a new blank db and run migrations, create an admin, load fixtures, and then run the parser against.  This takes a bit more time than copying a premade database, but it allows us to change the fixtures easily and without breaking anything.
- Build process should create a new DB
- Parser should automatically pull in title 45 (75, 95, 155)
Check the build pipeline times
make sure admin login still works
agree that the time it all takes is not too egregious

EREGCSC-1431 changing DB create process to make a clean DB without any data in it.

---

solution/ui/regulations/eregs-vite/src/views/Resources.vue

Resolves #EREGCSC1437
Adds some words to the resources page if the search term is more than one word (a space exists) and search is not quoted
Search for a single word - no message
Search for multiple words - see message
search for multiple words, but in quotes - no message
click on link in message, see search has quotes (results will probably change, but maybe not)

Message suggesting using quoted search for resource searching.

---

solution/backend/regulations/templates/regulations/supplemental_content.html

Resolves #EREGCSC-1445
removes auto escape from redirect URL field
links such as http://localhost:8000/supplemental_content/447 should just work.  
I removed escaping which technically makes us less standards compliant (but more things work) so the following links which contain an & might be affected, but have been tested and found working.
http://localhost:8000/supplemental_content/1364
http://localhost:8000/supplemental_content/518
http://localhost:8000/supplemental_content/135
http://localhost:8000/supplemental_content/407
http://localhost:8000/supplemental_content/591
http://localhost:8000/supplemental_content/447
http://localhost:8000/supplemental_content/627 …

removed auto escaping of URL because it breaks some URLs

---

solution/ui/regulations/eregs-vite/src/utilities/api.js
solution/ui/regulations/eregs-vite/src/views/Resources.vue

Resolves # 1335
Adds the search for synonym message for the resources page
Search for a word with a synonym.  example ELE
A message should appear  with "Search for similar terms: {{then the list of synonyms}} seperated by commas
Click on one of them.  It will update the search box and the list of synonyms.  If it is multiple words Didn't find what you were looking for? Try searching for will appear as well as "Or" befoe "Search for similar term:"

EREGCSC-1335 Synonym message for search

---

solution/backend/resources/v3views.py
solution/ui/regulations/eregs-vite/src/components/resources/ResourcesResults.vue
solution/ui/regulations/eregs-vite/src/views/Resources.vue

Resolves [EREGCSC-1447](https://jiraent.cms.gov/browse/EREGCSC-1447)
- null dates go to the end of the list
- newest first is the default when sorting by date, can choose oldest
- copy would be "Date (newest)" vs "Date (oldest)"
- Updates `resources/v3views` to accept new `oldest` sort method
- Sort select on Resources page is always active now, as any results can be sorted by newest/oldest
- If there is no text `searchQuery`, the "Relevance" search option is disabled.  It becomes enabled when a search query is also used as a search paramter.
1. On the resources page, I can search for a term like COVID and sort by oldest, and I see documents from 2020 at the top

EREGCSC-1447 -- Enable "sort by oldest" for resources search page

---

solution/backend/resources/v3serializers.py
solution/ui/regulations/eregs-vite/src/views/Resources.vue

Resolves #
Adds quotes on suggested synonyms when searching by them.    Adjust the font size for the synonym text as search.  Removes unactive synonyms
Go to the resources page.
search for ele.
The synonym text should be font size 14.
Click one of the synonyms.  The search should update and be in quotations.
Go to the admin.  
Disable one of the synonyms for ele's active status.
Clear cache an redo the search.  
The one updated to not active should no longer dispaly.

EREGCSC-1335 Added quotes around synonym search, adjusted size

---

solution/backend/resources/models.py

Resolves #1457
Needed for more accurately reflecting how our users conceptualize regulations.
- Calling `str()` on a Section model shows `<title> CFR <part>.<section`.
- Calling `str()` on a Subpart model shows `<title> CFR <part> Subpart <subpart>`.
- These changes are reflected in the admin panel and anywhere else that utilizes `str()`.
1. Visit the admin panel and click on add new Supplemental Content
2. Look at string representations of locations in the "Locations" widget, make sure they match the above format

EREGCSC-1457 Update representation of locations from 42 1.123 to 42 CFR 1.123

---

solution/backend/cmcs_regulations/settings.py
solution/backend/regcore/context_processors.py
solution/backend/regulations/templates/regulations/partials/footer.html
solution/backend/regulations/templates/regulations/partials/landing_default.html
solution/backend/regulations/templates/regulations/reader.html
solution/backend/regulations/templatetags/string_formatters.py
solution/backend/regulations/views/homepage.py
solution/backend/regulations/views/reader.py
solution/backend/regulations/views/regulation_landing.py
solution/backend/resources/v3serializers.py

Resolves [EREGCSC-1468](https://jiraent.cms.gov/browse/EREGCSC-1468)
Fixes bug introduced in [EREGCSC-1176](https://jiraent.cms.gov/browse/EREGCSC-1176) where the "last updated from eCFR" date was not correct.
- removes `last_updated` variable from reader and regulation_landing views and their associated templates, since that is no longer trusted to be the date that the parser last ran
- adds a regcore context processor to query ECFRParserResult object, get date of most recent parser run that ended without an error, and inject that date as `parser_last_success` into the context of all templates
- updates templates to use `parser_last_success` date where needed to communicate the most recent error-free parser run
- refactors …

EREGCSC-1468 -- Fix last updated timestamp issues

---

solution/ui/regulations/eregs-vite/src/views/Resources.vue

Resolves #
Makes the "S" in search capitalize if there is multiword, otherwise its lower case
Search for something like "Express Lane Eligibility".  The S in "Or search" should be lower case.  
Next search for ELE.  There should be no "Or" and the "S" should be lowercase.

Fixing search message

---

solution/ui/e2e/cypress/integration/api.spec.js

Resolves [EREGCSC-1295](https://jiraent.cms.gov/browse/EREGCSC-1295)
First step towards adding automated API test suite to the project.
- Adds `api.spec.js` test suite to existing integration test folder
- hard-codes array of existing `v3` endpoints with some constant values (ex: `latest` for version date, part `430`, section `10`, etc) and iterates over them, making a request to each and expecting a `200` response
- number of tests equals number of API endpoints being tested
- `api.spec.js` runs as part of our existing integration test process -- i.e. it will run with existing integration tests during the testing step of the existing CI/CD pipeline.
- Can also be run locally by using existing test commands
- `make test` in `solution` folder …

EREGCSC-1295 -- Cypress API testing

---

solution/parser/ecfr-parser/main.go
solution/parser/ecfr-parser/network/network_test.go
solution/parser/fr-parser/eregs/eregs.go
solution/parser/fr-parser/eregs/eregs_test.go
solution/parser/fr-parser/fedreg/fedreg.go
solution/parser/fr-parser/fedreg/fedreg_test.go
solution/parser/fr-parser/main.go
solution/parser/fr-parser/main_test.go

Resolves #1359
When the FR parser encounters a doc that exists for more than one title, it marks all extracted sections (from SECTNO tags in the XML) as belonging to the first title it processes that contains that doc. Thus the sections once uploaded to eRegs are invalid, e.g. 42 CFR 123.45 actually belongs to title 45.
- The FR parser processes `<CFR>` tags in the XML to map sections listed in `<SECTNO>` tags to the proper title.
- Sections that belong to titles outside the scope of our parsing are ignored.
- Unit tests are updated accordingly.
1. From a clean database, run the FR parser with the default title options.
2. In the Django Admin panel, go to "Federal Register Documents" and search …

EREGCSC-1359 Correct FR parser handling of non-Title-42 SECTNOs

---

solution/backend/regcore/templates/add_synonym.html
solution/backend/regulations/templates/regulations/about.html
solution/backend/regulations/templates/regulations/base.html
solution/backend/regulations/templates/regulations/supplemental_content.html
solution/backend/regulations/templates/robots.txt

Resolves #1479
Further helps to prevent eRegs from showing up in search engine results.
- When search indexing is disabled via the admin panel:
- Google & Bing are allowed to crawl the site, but all pages contain "noindex" tags so any existing data will be dropped.
- All other robots are disallowed from crawling.
- Verified all pages are correctly serving noindex tags.
1. With indexing disabled via the admin panel, visit /robots.txt and note that Google and Bing are allowed to crawl, but other robots are not.
2. View the source of pages on the site and note the `<meta name="robots" content="noindex" />` tag within the `<head>` of the page.

EREGCSC-1479 Improve anti-indexing methods

---

solution/ui/e2e/cypress/integration/resources.spec.js

Resources test suite is temperamental and does not pass reliably.
This PR skips resources test suite until it can be looked at closer and debugged.
- adds `skip` keyword to resources test suite so the test runner skips it.
1. Look in deploy action for this PR and see if the resources tests were skipped
2. Pull down branch locally and run `make test` and see if resources tests were skipped

Disable resources test suite

---

solution/backend/populate_content.py
solution/test.txt

Resolves #n/a
Currently every time you commit and push to an open PR, the experimental deploy attempts to reload the fixtures.
To more closely match the behavior of local environments and production, and fix fixture import bugs (when IDs differ causing unique constraints to be violated), we should only load fixtures automatically once per deploy, on first creation.
The `populate_content` function checks the count of each model with a fixture. If the count is 0, we can safely load the fixture. Otherwise it is skipped.
1. Check that this PR deploys correctly after the first and second push.

Only seed experimental deploy databases once

---

solution/backend/regulations/templates/regulations/partials/landing_default.html
solution/backend/regulations/templates/regulations/reader.html
solution/ui/prototype/package-lock.json
solution/ui/prototype/package.json
solution/ui/regulations/eregs-vite/package-lock.json
solution/ui/regulations/eregs-vite/package.json
solution/ui/regulations/js/main.js
solution/ui/regulations/package-lock.json
solution/ui/regulations/package.json

Resolves [EREGCSC-1484](https://jiraent.cms.gov/browse/EREGCSC-1484)
Make the whole phrase "Part 430 up to date from eCFR" link to eCFR when displaying the "up to date as of" date
- Link text now includes the part number to better communicate that the link will take you to that specific part and not just the eCFR homepage.
1. Visit any part's ToC landing page or Reader view in the experimental deployment and make sure the link text is no longer just "eCFR", but the longer string "Part XXX up to date from eCFR"

EREGCSC-1484 -- Clearer eCFR link text

---

solution/backend/resources/v3serializers.py
solution/backend/resources/v3views.py
solution/ui/regulations/eregs-vite/src/utilities/api.js
solution/ui/regulations/eregs-vite/src/views/Resources.vue

Resolves #
EREGCSC-101
Fixes issue where FRDOCS got grouped together and would replace the linked documents with the most recent one.
When you sort supplemental content by oldest it should all be in order again
Go to the resources page.  Sort by oldest.  Within the first 20 they should all be in order.
Search for "36443".  This should pull up the FR doc realated to 36443.  Before it would pull up 33209

EREGCSC-1501 Fix issue with resource page

---

solution/ui/prototype/Dockerfile

Resolves #
For new users, make prototype would fail due to python not being installed inside the docker container. To resolve this we added a line to install python in the dockerfile to fix this problem. 
add python installation in the Dockerfile
run `make prototype` 
expected results: no errors.

update prototype dockerfile to install latest python

---

solution/backend/regulations/views/reader.py
solution/backend/resources/models.py
solution/backend/resources/v3views.py

Resolves #n/a
Reader view is not showing grouped FR docs because reader.py isn't annotating `is_fr_doc_category` on the Category queryset.
- Uses an `InheritanceQuerySet` to add method `contains_fr_docs()` method to the queryset
- `contains_fr_docs()` added to querysets in reader.py and also in resources/v3views.py
1. Clear your cache and visit a reader view page known to have grouped FR docs (e.g. 42 CFR 433 Subpart A)
2. Verify docs are grouped in the sidebar

Fix reader view FR Doc grouping

---

solution/ui/regulations/js/src/components/RelatedRuleList.vue
solution/ui/regulations/js/src/components/SupplementalContentList.vue

Resolves #
EREGCSC-1507  Missing FR Docs in sidebar
Some FR-DOCS are missing on the sidebar.  This will allow them to appear if not there.
If there are more FRDOCS than the limit it will show a show more button allowing more federal documetns to appear.  Before there was a hardcoded 10 in there with a limit of 5.  So if it was less than 10 FR docs but more than5 you had no way of showing them.  Threw in the bonus of it not working in supplemental content as well :D.
Go to title 42 part 400 section 200.  Before you were missing a bunch of them such as Medicare Program; Hospital Insurance Entitlement and Benefits.  you should see a show more button now with the …

Eregcsc 1507

---

solution/backend/resources/utils.py
solution/backend/resources/v3serializers/categories.py
solution/backend/resources/v3serializers/locations.py
solution/backend/resources/v3serializers/mixins.py
solution/backend/resources/v3serializers/resources.py
solution/backend/resources/v3urls.py
solution/backend/resources/v3views/categories.py
solution/backend/resources/v3views/locations.py
solution/backend/resources/v3views/mixins.py
solution/backend/resources/v3views/resources.py
solution/backend/resources/v3views/utils.py

Resolves #1262
FR endpoints are fully moved to V3, and resources app V3 serializers and viewsets are split into more manageable files.
1. Verify Pythin Lint (flake8) tests pass (no import errors etc)
2. Verify cypress tests pass (200 OK on all API endpoints)

EREGCSC-1262 Implement endpoints for managing FR data

---

solution/backend/cmcs_regulations/settings.py
solution/backend/regcore/serializers/contents.py
solution/backend/regcore/serializers/parser.py
solution/backend/regcore/v3views/contents.py
solution/backend/regulations/views/homepage.py
solution/backend/resources/v3serializers/categories.py
solution/backend/resources/v3serializers/locations.py
solution/backend/resources/v3serializers/mixins.py
solution/backend/resources/v3serializers/resources.py
solution/backend/resources/v3serializers/utils.py
solution/backend/resources/v3views/categories.py
solution/backend/resources/v3views/locations.py
solution/backend/resources/v3views/mixins.py
solution/backend/resources/v3views/resources.py
solution/static-assets/requirements.txt
solution/ui/e2e/cypress/integration/api.spec.js

Resolves #1460
As a developer integrating with eRegs' API, I want accurate OpenAPI documentation available to me. Currently, when a field may return more than one data type, this is not accurately reflected in Swagger. Using drf-spectacular's "PolymorphicProxySerializer", we can include this information.
_For V3 only_:
- Fixes serializer name conflicts between regcore and resources apps
- Serializers in ALL apps must be named differently to not confused Swagger.
- Resources viewsets use PolymorphicProxySerializer to properly serialize endpoints. These changed:
- /v3/resources
- /v3/resources/locations
- /v3/resources/categories
- Fixed Swagger conflicts (i.e. duplicate component names, etc.)
- Fixes bugs caused by drf-spectacular updates
- …

EREGCSC-1460 Convert polymorphic serializers into fields for Swagger docs

---

solution/backend/regulations/templates/regulations/resources.html
solution/backend/regulations/views/homepage.py
solution/ui/e2e/cypress/fixtures/no-resources-results.json
solution/ui/e2e/cypress/fixtures/resources-page-2.json
solution/ui/e2e/cypress/fixtures/resources.json
solution/ui/e2e/cypress/integration/resources.spec.js
solution/ui/e2e/cypress/support/commands.js
solution/ui/regulations/eregs-vite/src/components/SearchEmptyState.vue
solution/ui/regulations/eregs-vite/src/components/custom_elements/CategoryList.vue
solution/ui/regulations/eregs-vite/src/components/custom_elements/FancyDropdown.vue
solution/ui/regulations/eregs-vite/src/components/custom_elements/SectionList.vue
solution/ui/regulations/eregs-vite/src/components/custom_elements/SubpartList.vue
solution/ui/regulations/eregs-vite/src/components/custom_elements/TitlePartList.vue
solution/ui/regulations/eregs-vite/src/components/navigation/NavBtn.vue
solution/ui/regulations/eregs-vite/src/components/pagination/PageNumber.vue
solution/ui/regulations/eregs-vite/src/components/pagination/PagesList.vue
solution/ui/regulations/eregs-vite/src/components/resources/ResourcesFilters.vue
solution/ui/regulations/eregs-vite/src/components/resources/ResourcesNav.vue
solution/ui/regulations/eregs-vite/src/components/resources/ResourcesResults.vue
solution/ui/regulations/eregs-vite/src/components/resources/ResourcesSelections.vue
solution/ui/regulations/eregs-vite/src/views/Resources.vue
solution/ui/regulations/js/src/components/SupplementalContent.vue

Resolves [EREGCSC-1536](https://jiraent.cms.gov/browse/EREGCSC-1536)
The Resources page needs some TLC to get it closer to/within 508 and screen reader compliance.  This PR will ensure that all parts of the page are accessible via keyboard navigation.
- Adds Skip to Main Content tab-navigable button to Resources page
- Adds and updates Cypress fixtures for Resources API call results:
- adds fixture that mocks no/zero results
- updates fixture that mocks page 1 of paginated results
- adds fixture that mocks page 2 of paginated results
- Re-enables all existing tests in Resources test suite that were previously being skipped
- Adds additional resources test to provide coverage for a11y, pagination, loading state, and empty state
- adds …

EREGCSC-1536 Keyboard navigability on resources page

---

solution/backend/serverless.yml

Resolves #
Access to production base url with out /prod that was causing issues with cypress tests. 
To allow the code to know the base_url with out it being hardcoded, we add it to AWS param store. 

add env variable for base_url paths so we do not hard code them anymore

---

solution/backend/cmcs_regulations/settings.py
solution/static-assets/requirements.txt

Resolves #1520
In order to fulfill best practices that (1) scans like OWASP ZAP usually look for (2) are helpful in minimizing risk, we want to implement CSP tags on our site that add some directives about where content is supposed to come from, which should prevent XSS.
CSP is in place to limit requests to external sources except for those explicitly allowed
**Limitations**
This PR currently allows `unsafe-inline` and `unsafe-eval`, which is considered bad practice but the site will not work without seemingly significant changes to the way Vue is managed.
Still this is likely better than not having CSP at all. See https://security.stackexchange.com/a/232329 for why. This should be looked into further but is likely a bigger ticket.
**Steps …

EREGCSC-1520 Put in place Content Security Policy

---

solution/backend/regulations/templates/regulations/about.html

This is @brittag on an old test account being curious about #1581 - seeing what happens if an external contributor creates a PR.
Update a minor typo on the "about" page that I noticed recently.

Fix text of eCFR link on About page

---

solution/backend/cmcs_regulations/settings.py

Follow-up to #1520
`https://images.federalregister.gov/*` was not in the CSP, so images loaded directly from that site were blocked.
- Add the above URL to the CSP
1. Visit `/42/433/Subpart-A/2021-03-01/#433-10-c-8` on the experimental deploy and verify the image within the reg text loads

EREGCSC-1520-B Add Federal Register images to CSP policy

---

solution/backend/cmcs_regulations/settings.py
solution/backend/regulations/templates/regulations/base.html

Resolves EREGCSC-1520
Follows django-csp documentation to add nonces to script tags for GTM scripts in base template.
See: https://django-csp.readthedocs.io/en/latest/nonce.html
- Adds nonce to script tags for GTM scripts in base template.
1. Go to Experimental Deployment and View Source.
- Paste this into a new tab: `view-source:https://lxs2ofoctb.execute-api.us-east-1.amazonaws.com/dev587` or
- Press Option + CMD-U on Mac or
- Right click and select "View Page Source"
3. Check GTM script tags for a nonce
> **Note**
> You can only see the nonce if you View Source for the page.  Nonces are stripped from the DOM inspector in Chrome/FF devtools by design: …

EREGCSC-1520c -- GTM CSP nonces

---

solution/backend/cmcs_regulations/settings.py

Resolves EREGCSC-1520
Follows recommendations from official Google link below:
https://developers.google.com/tag-platform/tag-manager/web/csp#google_analytics_4_google_analytics

EREGCSC-1520d -- Better handle GTM CSP paths

---

solution/backend/resources/v3serializers/resources.py
solution/backend/resources/v3views/mixins.py
solution/ui/prototype/src/views/Resources.vue

Resolves #eregcsc-1597
FR doc grouping is causing issues this is to resolve that.
Grouped FR Docs will display appropriately on the sidebar, the resources page, adn the front page.

Potential fix for fr_grouping issues

---

solution/ui/e2e/cypress/integration/print.spec.js

An intercept and assertion was added to the print test suite to test the format of the date in the footer. 
The problem: it is very flaky and unreliable.
- Moves intercept into `beforeEach` block as suggested in one of the many Github Issue comments about this issue
1. Run print test suite a bunch of times and see if it is more reliable than before

Tech Debt: Update print API test to be less flaky

---

solution/backend/regcore/admin.py
solution/backend/resources/admin.py
solution/backend/resources/v3serializers/resources.py
solution/backend/resources/v3views/resources.py

Resolves #1578
FR doc post endpoint needs to be updated to not overwrite any data exception locations, and apply the changelog after locations are updated (ideally done in one step, because this is an atomic endpoint).
- FR doc post endpoint parses and applies the changelog if a doc is updated
- Everything else about an FR doc is maintained if it already exists (`create` variable passed through to serializer context)
- `update` method of FR doc create serializer is simplified (sections of code moved to class methods)
- Semi-related: improved location key retrieval method on admin panel changelog representation
_Testing is best done locally so that you can re-run the FR parser immediately, or mock …

EREGCSC-1578 Re-running FR parser: Endpoints

---

solution/backend/resources/v3views/locations.py

Resolves #
Holdover from old FR parser behavior where locations were uploaded to a different endpoint. `/v3/resources/locations` was a ModelViewSet instead of a ReadOnlyModelViewSet.
- `/v3/resources/locations` is now a ReadOnlyModelViewSet
1. Verify lock icon appears next to `/v3/resources/locations` in `/api/swagger`

Make locations endpoint read only

---

solution/ui/e2e/cypress/integration/homepage.spec.js
solution/ui/e2e/cypress/integration/print.spec.js

Cypress tests were added to test the response from actual API within the app.  These tests were added in response to an incident that broke production: a change to our Content Security Policy blocked all API calls by response.  The after action report illuminated a lack of integration test coverage: we did not have any integration tests that tested actual API responses in the app -- all API responses were being mocked with Cypress fixtures.
Unfortunately, these new tests are very flaky and are causing delays and frustration when attempting to deploy to all environments.  As a result, they are being removed for now.
- Removes all tests and assertions related to the `parser_last_updated` API endpoint.
**Steps to manually verify this …

Hotfix: remove flaky API tests

---

solution/ui/regulations/css/scss/partials/_search.scss
solution/ui/regulations/eregs-vite/src/views/Resources.vue

Resolves [EREGCSC-1609](https://jiraent.cms.gov/browse/EREGCSC-1609)
On the Search page, the space between the search box and the helper text is too small/non-existant.  There should be more space below the search box to add separation between the search box and the helper text.
- Adds 16px margin below `.search-box`
- 16px matches the space above the search box
- Since margins collapse, this will not affect the spacing between the search box and the results count if there is no helper text
1. Visit the experimental deployment and make three searches:
- medicaid management information system
- nursing home
- "medicaid management information system"
2. Ensure the search box has 16px bottom margin
3. …

EREGCSC-1609 -- Increase Search Field bottom space

---

.github/workflows/deploy-experimental.yml
.github/workflows/deploy-prototype.yml
.github/workflows/deploy.yml
.github/workflows/load-regulations.yml
.github/workflows/load-supp-content.yml
.github/workflows/parser-checks.yml
.github/workflows/pythonLint.yml
.github/workflows/remove-experimental.yml
.github/workflows/remove-prototype.yml
.github/workflows/remove.yml
solution/ui/e2e/cypress.json
solution/ui/e2e/cypress/integration/homepage.spec.js

Another strategy to help mitigate flaky tests: allow up to two additional retries for every test that fails.  This may help with tests that fail for unknown reasons.   Also bumps up a timeout value from eight seconds to ten seconds.
See documentation here: https://docs.cypress.io/guides/guides/test-retries
This PR also changes all references to `ubuntu-latest` in our Github Action workflow yml files to `ubuntu-20.04` to fix a deployment issue.  See this link for more information:
https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/
- adds global `retries` config variable and sets it to `2`
- bumps `defaultCommandTimeout` from `8000` to `10000`
- changes `ubuntu-latest` to `ubuntu-20.04` in …

Hotfix -- add two retries to failing Cypress tests

---

solution/ui/regulations/js/main.js
solution/ui/regulations/js/utils.js

Resolves [EREGCSC-1596](https://jiraent.cms.gov/browse/EREGCSC-1596)
When executing a search, scroll down to the first instance of the  highlighted term when clicking through to the regulations text.
- adds `scrollToElement` utility function for scrolling to specific elements
- refactors logic to scroll to selected section
- scrolls to first highlighted term if exists.  If no highlighted terms, scrolls to section.  If no section hash in URL, doesn't scroll.
1. Visit a URL that has a highlighted term that doesn't appear until deep into section to ensure site scrolls to first highlighted term
- Ex: https://c0hdgvpw35.execute-api.us-east-1.amazonaws.com/dev615/42/433/Subpart-B/2021-03-01/?highlight=test#4 …

EREGCSC-1596 -- Scroll to first highlighted term

---

solution/ui/regulations/js/src/components/SupplementalContent.vue

Resolves #1652
Issue is that location hash for appendices is, e.g. `#Appendix-to-Subpart-F-of-Part-441`. When parsed into a location string, it is `42.Appendix.to` which is not valid. Since we are not currently linking resources to appendices, this PR just disables the right sidebar from requesting resources from an appendix.
- If location hash contains the word "appendix", the right sidebar defaults to resources for the entire part or subpart.
1. Visit `/42/441/Subpart-F/2021-11-05/#Appendix-to-Subpart-F-of-Part-441` on the experimental deploy and verify the right sidebar loads and displays "Subpart F Resources" instead of "Appendix.to resources".

EREGCSC-1652 Going to appendix of 441 subpart F returns error

---

solution/backend/regcore/urls.py

Resolves #616 
So when you do a search it errors out not because of search but because of synonyms.  We pass in synonyms as a parameter and if it has a character like "/" it thinks that there is another paramater in django.  The solution is just to add <path: synonym> on the url.
Searching wont error out anymore with a "/" in the search.
Search for ICF/IID.  There should be no error on the Synonym endpoint.

EREGCSC-1642  Error on search

---

solution/ui/regulations/package-lock.json

Bumps [qs](https://github.com/ljharb/qs) and [express](https://github.com/expressjs/express). These dependencies needed to be updated together.
Updates `qs` from 6.10.1 to 6.11.0
- [Release notes](https://github.com/ljharb/qs/releases)
- [Changelog](https://github.com/ljharb/qs/blob/main/CHANGELOG.md)
- [Commits](https://github.com/ljharb/qs/compare/v6.10.1...v6.11.0)
Updates `express` from 4.17.1 to 4.18.2
- [Release notes](https://github.com/expressjs/express/releases)
- [Changelog](https://github.com/expressjs/express/blob/master/History.md)
- [Commits](https://github.com/expressjs/express/compare/4.17.1...4.18.2)
---
updated-dependencies:
- dependency-name: qs dependency-type: indirect
- dependency-name: express dependency-type: indirect ...
Signed-off-by: dependabot[bot] …

Build(deps): bump qs and express in /solution/ui/regulations

---

solution/backend/serverless.yml

Resolves deployment issue
When deploying the two column search story, a new API endpoint created to find and return reg text results is behaving unreliably when deployed to the `dev` environment.  It appears that the request can take longer than six seconds, and when it does, it times out and returns an error.  If the request takes fewer than six seconds, it successfully returns the results.
Looking at the logs on AWS and searching around the web a bit, it appears that the serverless library that we are using in this project caps the timeout value at six seconds.  See this stackoverflow conversation for a very similar issue:
https://stackoverflow.com/questions/47594168/aws-lambda-task-timed-out-after-6-00-seconds
And see the serverless library documentation to read about …

[HOTFIX] Increase serverless function timeout from 6s to 10s

---

solution/parser/serverless-ecfr.yml
solution/parser/serverless-fr.yml

Resolves #
- blocks public access to the fr and ecfr parsers
1. Log into aws and check the fr and ecfr buckets, make sure that they are set to not being public. 
2. Visit experimental website and check everything looks like its working.
3. Make sure that the deployment went ok.

EREGCSC-1665-public-access-parsers

---

solution/ui/regulations/eregs-vite/src/components/SearchEmptyState.vue
solution/ui/regulations/eregs-vite/src/components/resources/ResourcesResultsContainer.vue
solution/ui/regulations/eregs-vite/src/utilities/api.js
solution/ui/regulations/eregs-vite/src/utilities/utils.js
solution/ui/regulations/eregs-vite/src/views/Search.vue
solution/ui/regulations/js/main.js
solution/ui/regulations/rollup.config.js

Resolves [EREGCSC-1615](https://jiraent.cms.gov/browse/EREGCSC-1615) and [EREGCSC-1657](https://jiraent.cms.gov/browse/EREGCSC-1657)
Adds pagination to combined search page.  Updates Search Empty State/Explore More call to action with new styling and new links.
Figma comp [here](https://www.figma.com/file/iZFh6UhvGVEHw1D4IAt3Bw/eRegs-Combined-Search?node-id=3295%3A11315&t=gKSa5jdbnSNEPCRK-0)
- Restyles and refactors `SearchEmptyState` component used in Resources Search and Combined Search to match "Expand Your Search" box in Figma Comp (EREGCSC-1657)
- Adds `PaginationController` to combined search page and paginates results from Reg Search and Resources Search (EREGCSC-1615) to 50 results per page
> **Note**
> If the columns have an unequal …

EREGCSC-1615 and EREGCSC-1657 -- Combined Search Pagination and Empty State updates

---

solution/ui/e2e/cypress.json
solution/ui/e2e/cypress/integration/resources.spec.js
solution/ui/e2e/cypress/integration/search-new.spec.js

Resolves recent issue where resources tests are no longer reliable
Over the past few weeks, the resource test suite has become unreliable.  This PR will attempt to genericize/improve test coverage to be more reliable
- Removes matcher for very specific string of text
1. Resources test suite passes on deploy

[HOTFIX] Better handle flaky resources tests

---

solution/ui/e2e/cypress/integration/resources.spec.js

Resolves issue where resources test suite fails consistently
Removing a `wait` in the resources test suite because it causes extra flake

[HOTFIX] remove wait in resources test

---

solution/backend/serverless.yml

Resolves # wrong db instance in yml file
yml file had the wrong db instance. We are on r6 now. 
1. Go to yml file check that the db instance is r6 not r5
2. Go to dev and val and see that the db instance is now r6 not r5

update db instance to correct version r6

---

solution/backend/regulations/templates/regulations/partials/header/search-input.html
solution/ui/e2e/cypress/integration/search.spec.js

Resolves [EREGCSC-1694](https://jiraent.cms.gov/browse/EREGCSC-1694)
The search input in the header searches more than just regulations, so the placeholder text and aria-label should be shortened to "Search" to remove the inaccurate emphasis on searching within regulations.
- changes input placeholder text and aria-label from "Search Regulations" to "Search"
1. Visit experimental deployment and ensure the header input placeholder text and aria-label say "Search" everywhere in the app

EREGCSC-1694 -- Trim header input placeholder text

---

solution/backend/regcore/serializers/history.py
solution/backend/regcore/tests/test_api_view.py
solution/backend/regcore/urls.py
solution/backend/regcore/v3views/history.py
solution/static-assets/requirements.txt
solution/ui/e2e/cypress/integration/api.spec.js

Resolves #1712
This endpoint takes a title, part, and section combination and queries GovInfo's link service to determine which years have valid historical PDFs associated with them.
- New endpoint exists, `/v3/title/<title>/part/<part>/history/section/<section>`.
- Endpoint returns a list of valid years and links to PDF versions of the reg for that year.
- Queries are performed asynchronously which should be fine as the number of requests (per request) is small.
1. Visit `/v3/title/<title>/part/<part>/history/section/<section>` and plug in valid values like `title=42`, `part=433`, `section=50`.
2. Verify the data returned is returned quickly, and contains valid years and PDF links.

EREGCSC-1712 API endpoint for retrieving a list of valid years for GovInfo display

---

solution/ui/e2e/cypress/integration/search.spec.js
solution/ui/regulations/eregs-vite/src/components/SearchEmptyState.vue

Resolves #EREGCSC-1699
Updates the medicaid.gov url on both resources search page for blank results and combined search resutls.  Url format is 
https://www.medicaid.gov/search-gsc?&gsc.sort=#gsc.tab=0&gsc.q=${this.query}&gsc.sort=
Go to combine search.  Search for something.  New url will use the new search URL
Go to resources.  Do a search and make it have 0 results.  New url should be there for medicaid search.

EREGCSC-1699 Update "Expand Search" new url

---

.github/workflows/remove-experimental.yml
solution/backend/serverless-experimental.yml

Resolves #EREGSCSC-1713
Remove experimental was failing when invoked.  Django was trying to establish a connection to a db of "Main" on the instance.  Since Main no longer existed on our new DB it couldnt connect.  To fix this db_name was just changed to eregs.
Another change is to ensure on failure it can be reran to remove the database.  If the parser.yml file gets removed successfully but the db is not, you cannot simply just rerun the github action(though you can just try executing the lambda directly).  This will say "Ok this failed to remove the create parser stack, lets just remove the database directly.
Create a branch off of this one …

Fix destruction of db issues

---

solution/backend/serverless.yml

Resolves #1678
As part of the process for enabling pgaudit, 2 parameters need to be added to the RDS parameter group.
- `pgaudit.log` is set to "none" for now.
- `pgaudit.role` is set to "rds_pgaudit".

EREGCSC-1678 Add pgaudit params to RDS parameter group

---

solution/backend/serverless.yml

Resolves #
Switches pgaudit to log all transactions of any type.
- `pgaudit.log` is set to `ALL`.
1. Once deployed to dev, reboot the dev RDS instance and run `show pgaudit.log;` in psql to verify it is set correctly.
2. Do this for val and prod next.

EREGCSC-1678-B Switch default logging mode to ALL

---

.github/workflows/deploy.yml

Resolves #
Cypress-test is failing due to it being assigned an incorrect version of node.  Breaking cypress steps into a separate step, should fix this.  tested by copying the behavior in an experimental branch to cause it to break and getting the same error as it was before.
When deployed to dev, val , and prod cypress test should run.

Cypress-fix deployment

---

.github/workflows/deploy-experimental.yml
.github/workflows/deploy.yml
README.md
solution/ui/regulations/eregs-vite/package-lock.json
solution/ui/regulations/eregs-vite/package.json

Resolves [EREGCSC-1648](https://jiraent.cms.gov/browse/EREGCSC-1648)
Cypress was recently updated to v12.  The end to end tests worked well, were much faster, and much less flaky on our Experimental Deployments, which use `deploy-experimental.yml` as a config file.
However, the tests would not run when deploying to `dev`/`val`/`prod` (known as the "production deployment").  This deployment uses a different config file -- `deploy.yml`.  
It was noted that our experimental deployments use Node v16, while our production deployments were using Node v14.  A likely explanation is that the Cypress v12 upgrade installed or upgraded dependencies that need Node 16+ to run successfully.
As such, this pull request updates Node to v18 for both the Experimental Deployments and the …

EREGCSC-1648 -- Cypress 12 Deployment Issues

---

.github/workflows/deploy-experimental.yml
.github/workflows/deploy.yml
solution/backend/package-lock.json
solution/backend/package.json
solution/backend/serverless-experimental.yml
solution/backend/serverless.yml

Resolves #EREGCSC-1702
Previous version of adding changesets is failing since our versioning is screwed up in github actions.  Previous library for changesets does not have serverless v-3 support and has a dependency on v-1 only.  This is a forked repo to allow version 3 and above to work for it.  As of this time only v-3 exist so might not be supported in future releases.
- The version for adding changesets to cloudformation in serverless.
After code is deployed to environment, there will be a changeset created for dev, val, and prod for yml file changes on serverless backend.

EREGCSC-1702 Fix changeset library

---

solution/static-assets/serverless.yml

Resolves #1688
As part of our ATO, we're required to have server-side encryption on all S3 buckets. Serverless deployment buckets are already encrypted by default, so all that remains is our static assets bucket.
- `serverless.yml` for static assets is changed to enable encryption.
1. Log into our dev environment and find the `eregs-dev704-site-assets` S3 bucket.
2. Click "Properties" and scroll down to "Default encryption".
3. You should see "Encryption key type" is set to "Amazon S3-managed keys (SSE-S3)", whereas before it was "None".

EREGCSC-1688 Encrypt static assets bucket by default

---

solution/backend/serverless.yml

Resolves # EREGCSC-1702
Adding database instance and cluster to the serverless file with encrypted on and deletion protection on.  Does not impact anything on the application since this is just getting serverless in line with our application.
- Adds the resource to the file.  Does not add anything to the application
1. After deployed to dev, check dev to see that the stack does not change the resources.
2. After deployed to val same thing
3. After deployed to prod same thing.

EREGCSC-1702 Adding resources to serverless

---

solution/backend/regulations/rss_feeds.py

Resolves #[EREGCSC-1737](https://jiraent.cms.gov/browse/EREGCSC-1737)
We want the RSS feed to be match up with our resource data. The resource data name field will be equivalent to title for the rss feed. However we do not always have a name value. Since RSS requires the title field its been decided to return a string "none" instead. That way when we use the search.gov api we get the raw data and can build the correct title on our side. 
Visit the RSS feed to this pull request /latest/feed and see that the title is "none" in some cases when we do not have a name value for resources.

EREGCSC-1737 - update code to return title as "-"

---

solution/static-assets/serverless.yml

Resolves #1682
As part of our ATO, all S3 buckets must require SSL. Due to a lack of serverless config, the `static-assets` bucket did not enforce this.
Note that due to the nature of this change, it will affect both experimental and production deployments without the need for additional serverless code.
- `serverless.yml` for static assets explicitly enforces SSL.
1. Go to the AWS console for dev.
2. Under S3, go to `eregs-dev710-site-assets` and click "Permissions".
3. Verify the following code is present in the Bucket Policy, and that it matches the [AWS remediation docs](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#s3-5-remediation):
```
{ …
```

EREGCSC-1682 Buckets should require requests to use Secure Socket Layer

---

solution/backend/resources/v3views/resources.py
solution/static-assets/serverless.yml

Resolves # 1689 & 1690
Description- Enable WAF/ACL on Cloudfront.   Ticket was originally just for 1689 but when adding the WAF/ACL resource to serverless, it requires you to say if you want logging or not. To make it simple, logging was added.
- All new experimental deploys have waf/acl enabled as well as dev, prod and val.  
- 
Steps to manually verify this change...
Go to the resource for this PR in Cloudfront,
See that aws/waf has a value there.
When deployed to dev, verify it gets added.  ONce its deployed to dev it takes about 15 minutes to create the resource.
Same as above for val and prod.

EREGCSC-1689: Cloudfront associated with WAF ACL

---

solution/backend/serverless-experimental.yml
solution/backend/serverless.yml

Resolves #1684
To satisfy our ATO, we are required to have execution logging enabled for API Gateway and WebSocket API.
- Logging is enabled with an externally-managed role (requires one-time setup per environment, described in internal runbook.)
1. Verify this PR has successfully deployed.
2. Go to CloudWatch for dev and check for the existence of a log group titled `API-Gateway-Execution-Logs_98he0f5e87/dev713`.

EREGCSC-1684 API Gateway REST and WebSocket API execution logging should be enabled

---

.github/workflows/deploy-experimental.yml
.github/workflows/deploy.yml

Resolves #1738
`set-output` is deprecated in Github Actions, this PR updates it to the new syntax.
- `set-output` is replaced with environment files in deploy.yml and deploy-experimental.yml
1. Verify this PR deploys successfully

EREGCSC-1738 Update set-output in Github Actions files

---

solution/backend/regulations/templates/regulations/partials/node_types/Citation.html
solution/ui/regulations/eregs-component-lib/src/utils.js
solution/ui/regulations/eregs-vite/src/components/reg_search/RegResults.vue
solution/ui/regulations/eregs-vite/src/components/reg_search/RegResultsItem.vue
solution/ui/regulations/eregs-vite/src/utilities/utils.js
solution/ui/regulations/eregs-vite/src/views/Search.vue

Resolves [EREGCSC-1755](https://jiraent.cms.gov/browse/EREGCSC-1755)
Parentheses and other special characters cause problems when using them to highlight text in the reg text reader view.
- Updates regex logic to handle parens and other special characters
- limits highlightable terms to strings with a length greater than one (1)
- Adds actual user-defined query as a highlightable string in the URL
- Ignores citation node at bottom of section when highlighting text
1. Search for "1903(r)", click a result to visit the reader view, and make sure "1903(r)" is highlighted in the reg text
2. Make sure all previous searches work

EREGCSC-1755 -- Highlighting Bug

---

solution/ui/regulations/eregs-component-lib/src/api.js
solution/ui/regulations/eregs-component-lib/src/components/SupplementalContent.vue

Resolves #1758
Turns out getSupplementalContentByCategory isn't used after all, if you pull the thread. The function is only called if `requested_categories.length > 0` in SupplementalContent.vue, which is never true because `requested_categories` is never assigned anything other than an empty string.
- Remove getSupplementalContentByCategory
- Remove references to it from SupplementalContent.vue, as well as `requested_categories`
1. Verify PR deploys properly
2. Make sure the right sidebar still works in reader view

EREGCSC-1758 Convert the remainder of V2 calls to V3

---

.github/workflows/parser-checks.yml

Resolves #n/a
Parser checks were failing due to configuration that recently became invalid. Also we were receiving set-output and save-state deprecation warnings.
- Packages are updated to remove set-output and save-state warnings
- `install-go: false` removed to fix failures
1. Go to [this most recent run](https://github.com/CMSgov/cmcs-eregulations/actions/runs/4357203064) to see that parser checks succeeded
2. After merging to main, verify it succeeds again

Fix failing parser checks

---

solution/backend/resources/admin.py

No JIRA ticket number, since this is too small for a ticket.
In the admin panel, there's a tiny typo in helper text on supplemental content editing pages, so I'd like to fix it.
"seperated" to "separated"
- Go to the admin panel
- Check out the "add" page for supplemental content
- Under "Bulk locations", you should see "Add a list of locations separated by a comma." instead of "Add a list of locations seperated by a comma."

Fix typo in admin panel help text

---

solution/backend/regulations/templates/regulations/homepage.html
solution/backend/regulations/templates/regulations/homepage/child.html
solution/ui/regulations/css/scss/partials/_site_homepage.scss

Resolves # EREGCSC-1744
Minimum updates to make the homepage ready for title 45
-Adjust the spacing between the end of Title 42 and the start of Title 45 (it's a bit squished)
-Remove all of the hardcoded "preceding" and "subsequent" notes from the homepage – they're outdated anyway, and probably not super effective; we should deal with that problem in a different way
1. Go to the homepage
2. Scroll down to title 45.  Spacing should be more than it was before.  Will look less squished.  Margin for top of h1 was changed from 0px to 16px.  This was taken from margin-top of the toc so that the first title doesn't move from where it was previously while adding padding for subsequent titles.
4. There …

EREGCSC-1744: Minimum viable homepage updates for 45

---

solution/backend/regcore/models.py
solution/backend/regulations/templates/regulations/partials/sidebar_left/base.html
solution/backend/regulations/views/reader.py
solution/backend/regulations/views/regulation_landing.py
solution/ui/regulations/css/scss/partials/_sidebar_left.scss

Resolves # EREGCSC-1548
Removing jump -to from right sidebar replace with text for part and subchapter
- Right sidebar jump to is gone and replaced with text

EREGCSC 1548- Reg page left nav shows part info 

---

solution/backend/regulations/templates/regulations/about.html
solution/backend/regulations/templates/regulations/homepage.html
solution/backend/regulations/templates/regulations/reader.html
solution/backend/regulations/templates/regulations/regulation_landing.html
solution/ui/regulations/eregs-vite/src/components/JumpTo.vue
solution/ui/regulations/eregs-vite/src/components/reg_search/RegResultsItem.vue
solution/ui/regulations/eregs-vite/src/components/resources/ResourcesResults.vue
solution/ui/regulations/eregs-vite/src/views/Resources.vue
solution/ui/regulations/eregs-vite/src/views/Search.vue

Resolves [EREGCSC-1708](https://jiraent.cms.gov/browse/EREGCSC-1708)
Our unique production environment has two URLs that can cause headaches for tests and api calls.  This PR will attempt to mitigate these issues to cause fewer headaches.
- Removed complicated and brittle logic that determines the proper `base` URL on the front end
- Pass in `homepage` URL from Django instead, which should always just know if the URL for the site has a subdirectory or not
1. Build locally and make sure the Jump To in the header works from every route (`/`, `/resources`, `/search`, `/about`, ToC for a part, reader view for a subpart)
2. Build locally and make sure highlighting in a Subpart section works when visiting …

EREGCSC-1708 -- fix prod cypress failures

---

solution/backend/regulations/templates/error_base.html

Resolves bug introduced in [EREGCSC-1547](https://jiraent.cms.gov/browse/EREGCSC-1547) -- global header
Error page templates (404, 500, etc) did not have feedback banner or header.
- updated `error_base` template to include everything it needs for a working feedback banner and header.
1. Go to a page that would trigger a 404 error and make sure it has a header and feedback banner that works
- ex: https://qx0atg8izb.execute-api.us-east-1.amazonaws.com/dev751/asdfas

Hotfix: add feedback banner and header back to error pages

---

solution/backend/regcore/search/migrations/0007_populate_index.py

Resolves # EREGCSC-1823
Certain part versions are missing in regulations search due to the index not containing all of them particularly the most recent version.  This is a data migration to just save each part as it currently is.  Whenever a part is saved it updates in the index
- More results will appear in serach
1. Pull the branch onto your local.  Run the data migrations.  Search for FMAP.  You should get more than 3 results.  
2. Cant really properly test until its in dev.  In dev search for FMAP.  Should get more results
3. In val as well should get more than 3 results
4. In prod should get part 431 appearing in search.

EREGCSC-1823 Missing results in regs search

---

solution/backend/resources/serializers/resources.py

Resolves #1780
We want new Federal Register documents to be automatically approved as the FR parser has proven to be reliable enough.
- Incoming FR docs get approved automatically
1. Locally, run the FR parser on a clean database
2. Verify in the admin panel that the docs that came in are approved

EREGCSC-1780 Enable new FR documents to be automatically approved

---

solution/backend/regcore/tests/test_api_view.py
solution/backend/regcore/urls.py
solution/backend/regcore/views/synonyms.py
solution/ui/e2e/cypress/e2e/api.spec.cy.js
solution/ui/regulations/eregs-vite/src/utilities/api.js

Resolves #1779
Searching for some characters caused search to fail with an error popup. This was due to the synonyms endpoint using a path parameter (e.g. `/v3/synonym/X`) which prevented special characters from being encoded properly. (E.g. `%` should be encoded to `%25` but wasn't). This PR changes it to use a query parameter (`/v3/synonyms?q=X`) which is encoded properly.
- Synonyms endpoint uses query parameter
- Cypress test updated
- api.js file updated
1. Visit the experimental deploy and search for the following: `%`, `138% FPL`, `138 % FPL`, `"`, `""`, `#`, `.`, `..` , `?` 
2. Verify for each of the above, there are no errors

EREGCSC-1779 Searching for certain characters causes error

---

solution/backend/regulations/templates/error_base.html
solution/ui/e2e/cypress/e2e/error-page.cy.js
solution/ui/e2e/cypress/e2e/homepage.spec.cy.js

Resolves error pages not having any end to end test coverage
The header for every page on the app was recently redesigned and refactored (see [EREGCSC-1547](https://jiraent.cms.gov/browse/EREGCSC-1547) ).  Unfortunately, the Error pages did not get the updated header and for the past several days these error pages did not have a header at all.  
The header was added back to the error pages via a hotfix pull request (see [here](https://github.com/CMSgov/cmcs-eregulations/pull/751) ).
This pull request will add tests so that if header functionality or body text should change (like if the header disappears again), then the tests will fail.
- adds new test suite for 404 error page
1. Make sure tests pass on …

Add Cypress test suite for Error Page

---

.github/workflows/deploy-experimental.yml
.github/workflows/deploy.yml
.github/workflows/load-regulations.yml
.github/workflows/load-supp-content.yml
.github/workflows/parser-checks.yml
.github/workflows/pythonLint.yml
.github/workflows/remove-experimental.yml
.github/workflows/remove.yml

Resolves #
Some of the steps were using different versions of github actions.  All processes should work fine.  We updated node for other steps but missed a couple and some are outdated using deprecated github commands and newer versions removed that.
- Set output is no longer used.  Some of the older libraries used it still
1. Close the PR.  Removal step should most likely work properly.  There is a weird bug there that might stop it but it should work if it since it was fully built.
2. Reopen the PR.  The build steps should all execute(make sure the removal step is finished running first)

Syncing up github actions

---

solution/backend/resources/views/mixins.py

Resolves #1829
Due to inconsistencies with the default setting of the `fr_grouping` parameter in the resources endpoint, duplicate groups were appearing. Also, unapproved related docs were showing up because they were not filtered out.
- Fix `fr_grouping` default so that duplicate groups don't appear
- Filter by `approved=True` on related resources prefetch
1. Visit `/42/447/Subpart-C/2023-01-01/` and `/42/447/Subpart-B/2023-01-01/` and verify that no duplicate groups or unapproved items appear

EREGCSC-1829 Duplicate groups in sidebar rules + unapproved items showing

---

.github/workflows/pythonLint.yml
solution/backend/regcore/tests/fixtures/depth.json
solution/backend/regcore/tests/fixtures/part.json
solution/backend/regcore/tests/test_api_view.py
solution/backend/regcore/tests/test_models.py

Resolves #EREGCSC-1825
Adds a unit test for creating the search objects
None just added a unit test
Run "make python.unittest" all test should pass

EREGCSC-1825: Unit test for creating search object

---

solution/backend/serverless.yml

Resolves #
Creates or adds postgres 14 db to the environments.  The custom paramter groups are causing issues with just replacing the database the stacks refer too.  So a database is being added to the serverless file, which will be blank in prod and val and they will be removed by the replaced db when it is done.
In dev no changes should occur, resource is already imported
in val and prod a blank database will be created  that is postgres 14
Once deployed to dev, no database is added but the 14 dev is there(as well as the 12)
In val a new database is added for 14
In prod a new databasse is added for 14

EREGCSC-1689Updated serverless file to include postgres14

---

solution/backend/serverless.yml

Resolves # EREGCSC-1695
This is updating the serverless file for the site stack.  Changes have already been applied in AWS this will just keep our serverless file in sync with the environments.
- Removal of Aurora Postgres 14the serverless file.  Changing it to 15
- Removal of parameter group 13 and switching it to 15.
- Adding of Postgres db instance and cluster to serverless file, databases will not be created since they already exist
1. After deployment to dev, no changes to the stack as far as database creation
2. After deployment to Val, no changes to the stack as far as database creation
3. After deployment to Prod, no changes to stack as far as database creation

EREGCSC-1695 Update serverless with new db

---

solution/backend/serverless.yml

Resolves #1689
Parameter group for postgres 14 was tried to be assigned to a postgres 15 db, serverless got mad and it broke.  This just fixes it to be the one for 15.
1. Check that the version of the postgres parameter group matches 15.

Paramter group was incorrect on serverless,

---

solution/backend/regcore/tests/test_models.py

Resolves # none
Removes a failing python unittest due to retired models
All current python unittest should pass
- Run make python.unittest.  All test should pass

Removing failed unittest

---

solution/backend/serverless.yml

Resolves #1800
To satisfy ATO requirements, we must have a minimum database backup period of 7 days.
- Sets `BackupRetentionPeriod` and `BackupRetentionMinimum` to 7
1. Run `serverless package --stage dev` and verify no errors
2. Run `serverless package --stage val` and verify no errors
3. Run `serverless package --stage prod` and verify no errors
4. Deploy this PR and check AWS console to make sure backups are being retained for 7 days

EREGCSC-1800 Medium - dev,prod,val RDS.11 RDS instances should have automatic backups enabled

---

solution/backend/serverless.yml

Resolves #1800
Despite https://docs.aws.amazon.com/securityhub/latest/userguide/rds-controls.html#rds-11 and https://docs.aws.amazon.com/config/latest/developerguide/db-instance-backup-enabled.html making direct references to `BackupRetentionMinimum`, Serverless complains that this is an extraneous key.
Let's see if just setting `BackupRetentionPeriod` meets the ATO requirements.
- Remove `BackupRetentionMinimum`
You can run `serverless package` locally if you want, but just like the previous PR, it _will_ succeed but deployment could fail. No damage will be done in this case.

EREGCSC-1800-B Remove extraneous key

---

solution/backend/resources/admin.py

Resolves # EREGCSC-1837
Allows doc_type to be editable for FR-documents in django admin.  Admin is only editable as a drop down value.  If there is an already existing value, that value will still appear in the drop down until it is changed.
Options are:
RFI
NPRM
Final Rule
None
- Doc-type is editable in fr-documents
Log into django admin
Select an FR-document
Doc Type will be editable through a drop down.
Select a different doc type
reopen FR-document to verify it changed.

EREGCSC-1837 Make FR-type an editable field

---

solution/backend/scripts/delete_cloudformation_stack

Resolves #
There was a bug in the script instead of fi it had 'end' which is wrong syntax for a shell script
1. run the script manually on your local and notice it does not give an error anymore.

instead of end needs to be fi

---

solution/ui/regulations/eregs-component-lib/package-lock.json
solution/ui/regulations/eregs-component-lib/package.json
solution/ui/regulations/eregs-vite/package-lock.json
solution/ui/regulations/eregs-vite/package.json

Upgrades our two Vite build pipelines to Vite 4.3, which was recently released:
https://vitejs.dev/blog/announcing-vite4-3.html
- Edits `package.json` file for each Vite project to change Vite version to `"vite": "^4.3"`
1. Make sure everything works locally and builds experimental deployment properly

Upgrate to Vite 4.3

---

SECURITY.md

No Jira ticket number.
GitHub recommends [setting up a security.md file](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository).
This PR adds a security.md file that links to the HHS/CMS vulnerability disclosure policy, because that's where a member of the public should go if they wanted to report a vulnerability.
No impact on our application.
When you click the link, it should go to the relevant page.

Add simple security policy to the repo

---

solution/backend/resources/serializers/resources.py
solution/ui/regulations/eregs-component-lib/src/components/SupplementalContentList.vue

Resolves # EREGCSC 1868
Description-
Outbound links on show more are using the redirects instead of the url for the abstract resources. Needs to be fixed.
Supplemental content on showmore will just go to the outbound site instead of a redirect
Steps to manually verify this change...
steps to view and verify change
Go to a subpart for regulations.
Go to the sidebar and pick a resource category  that has a show more.
Url should be a normal url not one for a generic piece of supplemental content.

EREGCSC-1868: Outbound link don' use redirects

---

solution/ui/regulations/css/scss/partials/_search.scss

Resolves bug where long strings (URLs) can make the two search columns different widths.
There is one `searchgov` search result that returns a snippet that's one [long incredibly unbroken](https://www.youtube.com/watch?v=5YOVN2BTSmI&t=18s) URL string without any dashes.  This is causing the combined search page's Resources column's width to stretch to be 80% of the page, and it is compressing the reg search column width to be 20% of the page.
This is because we're not setting a max width on the columns and we're not setting the overflow correctly.  This PR addresses both issues.
- Adds styles to prevent search results columns from expanding wider than half the page
- Adds overflow style to break long URL strings so they overflow within …

[Quickfix] Better handle long strings in search results columns

---

README.md

Part of resolving #EREGCSC-1865
This repository was previously in the CMSGov organization, and we moved it to the Enterprise-CMCS organization. The old links should auto-redirect, but I updated our links in our readme to reduce any potential confusion.
Look at the readme and ensure the links work.

EREGCSC-1865 - Updated org name in readme

---

solution/ui/regulations/eregs-vite/src/components/search/RegResults.vue

Resolves #EREGCSC-1879
Adding title to part name on regulations search
- On regulations search the part name for each result should have the title name in it.  Ex.  42 CFR Part 441 - Services: Requirements And Limits Applicable To Specific Services
1. Make a regulations search
2. Title number cfr should be in the part search results

EREGCSC1879- Adding Title to Part name on reg sear

---

README.md
solution/Dockerfile.template
solution/backend/cmcs_regulations/settings.py
solution/backend/resources/views/resources.py
solution/backend/serverless-experimental.yml
solution/backend/serverless.yml

Resolves #site_name needs to be passed for prod thats different from dev
**Note**
This ticket is a blocker for [EREGCSC-1878](https://jiraent.cms.gov/browse/EREGCSC-1878) . 
We have created a production search.gov site and plan to use the other as a sandbox. The production site has its own key and sitename. The previous pull request did not take into account that on prod, and val the sitename is different
- expected change 4
-  yml files that set the environment variables in serverless. 
- code to reference the environment variable instead of hard coded site name
- updated Dockerfile template that requires to add the site_name as a environment variable locally …

update code to use site_name as well

---

solution/backend/regulations/templatetags/link_statutes.py
solution/backend/regulations/tests/fixtures/section_link_tests.json
solution/backend/regulations/tests/test_statute_links.py

Resolves #1845
To enhance the regulation reading experience, section links with paragraphs (e.g. 1902(a)) should link to that paragraph directly. Please note that this PR does not support deeply-nested paragraph links, and for now "Section 1902(a)(1)(C)" will link only to paragraph (a). This is due to the unreliable nature of generating links for any reference below the top level of a paragraph. See discussion in Jira for more info.
- Where a statute ref has a paragraph identifier, `#substructure-location_{paragraph}` is appended to the link.
- Tests are updated with this in mind.
- Test data is moved to a JSON file for better readability.
1. Navigate to a part in eRegs that has linked sections …

EREGCSC-1845 Implement linking directly to SSA paragraphs

---

.github/workflows/remove-experimental.yml
solution/backend/cmcs_regulations/settings.py
solution/backend/dropdb.py

Resolves #EREGCSC-1882
DB not being removed on remove_experimental action
dropdb.py to not fail the entire removal just because the database is not there.
- expected change 2
1. create a pull request
2. close the pull request check that db is cleaned up properly. 
Connect to the database:
psql -h <hostname> -p 3306 -U <username> -d <databasename>  
(Note to find the hostname, username, database name. Go look at the lambda function configuration and use those values)
run \l 
You should see a list like this
Notice the database name dev829. 
Now close this pull request
You will notice your database connection is lost because you had signed into dev829 that is no longer there. You can sign in again …

EREGCSC-1882-db_not_being_removed_on_remove_experiment

---

solution/ui/e2e/cypress/e2e/part.spec.cy.js

Resolves failing Cypress assertion in `part.spec`
We have an assertion that relies on data returned from an actual API call.  That data has changed -- it has been updated and includes a new value in the 0 index position of an array.  We should not assert on data that may change.
- Comments out assertion that relies on data that may change.
1. Make sure Cypress tests pass.

HOTFIX: Disable assertion that relies on changing data

---

solution/backend/regulations/templatetags/link_statutes.py
solution/backend/regulations/tests/fixtures/section_link_tests.json

Resolves #1940
Now that the house.gov team has fixed the majority of their deeply-nested links, we can more reliably link to paragraphs like 1902(a)(1)(C) and so on.
- Textual links to deeply-nested substructures will link directly there instead of the top-level paragraph.
- Tests are updated.
1. Import statute link converters and verify they are linking to the correct depth
2. Run unit tests for regulations

EREGCSC-1940 Link statute refs to full paragraph depth

---

solution/Makefile

Resolves # EREGCSC-1974
Make file had back slashes that caused issues.  This corrects it
- Allows the docker-compose commands to run properly
1. On your local, run "make local.seed".  There should be no errors
2. On your local run "make local.dump".  There should be no errors.

EREGCSC-1974 - Correct make file

---

solution/backend/regulations/templates/regulations/homepage.html
solution/ui/e2e/cypress/e2e/homepage.spec.cy.js
solution/ui/e2e/cypress/fixtures/categories.json
solution/ui/regulations/eregs-component-lib/src/components/RecentChangesContainer.vue
solution/ui/regulations/eregs-component-lib/src/components/RecentResources.vue

Resolves issue where Subregulatory Guidance category names were hard coded in the "View More Guidance" link, resulting in a missing category (ARA Memos) and incomplete results on the Resources page when clicking "View More Guidance."
On the new homepage, the "Recent Subregulatory Guidance" tab shows items that are part of a Subregulatory Guidance subcategory.  Examples of these subcategories include: FAQs, CIBe, SMDLs, etc.
We are already programmatically getting the IDs for each of these subcategories so that the home page will display only items that are part of a Subregulatory Guidance subcategory.
See [this commit](https://github.com/Enterprise-CMCS/cmcs-eregulations/pull/844/commits/2b0e32d8f23675afb9bbdf722771123fc0f0c171) for more information on how this was …

Fix: programmatically get Resource Category IDs for "View More Guidance" link

---

solution/backend/regulations/tests/fixtures/statute_link_api_test.json
solution/backend/regulations/tests/test_statute_links.py
solution/backend/regulations/views/statutes.py

Resolves #2002
I forgot to actually do ordering on the statute endpoint. This PR implements it. The tests that I wrote should have caught it, but didn't, so I modified it to insert the test objects in the reverse order so that it is guaranteed to fail if ordering isn't working.
- Add ordering to statute endpoint
- Update test to check for this
1. Check `/v3/statutes` and make sure objects are ordered by act name, then statute title respectively.
2. Run unit tests. If you want proof, go to `backend/regulations/views/statutes.py` and remove `.order_by("act", "statute_title")` on line 41. Then run the test again and it will fail.

EREGCSC-2002 Fix statute endpoint ordering

---

solution/backend/regulations/templatetags/link_statutes.py
solution/backend/regulations/tests/fixtures/section_link_tests.json

Resolves #1988
Some statute refs use "§" (or worse, unicode HTML `&#xA7;`) instead of the word "section" and its variations. This PR handles that as well as adds more edge cases.
- `§ 1903` will now match.
- `Sec. 1903` will also match.
- Additional edge cases should also be covered, with variations in spacing, plurality, and punctuation. 
1. Check `/42/431/Subpart-A/2023-01-01/#431-15`. "Sec." ref should be linked.
2. Check `/45/75/Subpart-B/2021-11-15/#75-101-e-1-v`. "§" ref should be linked.
3. Run unit tests.

EREGCSC-1988 Link to citations when section symbol is used instead of the word "section"

---

solution/backend/regulations/templatetags/link_statutes.py
solution/backend/regulations/tests/fixtures/section_link_tests.json

Resolves #n/a
Quick fix so no JIRA ticket for this. "5 U.S.C. 552(a) and 1 CFR part 51" would match "552(a)" and "1" as sections of title 5. This was a failure of the negative lookahead which was only looking for additional U.S.C. sections.
- "1" no longer matches and is not linked
- Tests are updated to check for this 
1. Run unit tests
2. Visit `/42/460/Subpart-E/2023-06-05/#460-72-e` and see that "5 U.S.C. 552(a) and 1 CFR part 51" is matching correctly

Fix negative lookahead to include CFR in ignored list

---

solution/backend/cmcs_regulations/settings/local.py
solution/backend/serverless-experimental.yml
solution/backend/serverless.yml

Resolves # EREGCSC-2018
In order to set up independent settings files per environment an environment variable for django_settings_module needs to be set.
The value of "cmcs_regulations.settings.deploy" is set in each environment and is called in the two serverless files.  This will not change anything about how the application currently behaves since if now envrionment variable is passed in, it defaults to cmcs_regulations.settings.deploy.
- Adds environment variables to serverless and serverless-experimental
- A new variable located in eregulations/django_settings_module was added in aws for dev, val and prod. 
1. The experimental deployment site works correctly
2. Log into aws for dev, val and …

EREGCSC-2018 Adding django settings module config

---

solution/ui/e2e/cypress/fixtures/statutes.json
solution/ui/regulations/eregs-component-lib/src/components/shared-components/Statutes/table-elements/BodyCell.test.js
solution/ui/regulations/eregs-component-lib/src/components/shared-components/Statutes/table-elements/BodyCell.vue
solution/ui/regulations/eregs-component-lib/src/components/shared-components/Statutes/table-elements/__snapshots__/BodyCell.test.js.snap
solution/ui/regulations/eregs-component-lib/src/components/shared-components/Statutes/utils/urlMethods.js
solution/ui/regulations/eregs-component-lib/src/components/shared-components/Statutes/utils/urlMethods.test.js
solution/ui/regulations/eregs-vite/src/views/Statutes.vue

Resolves `prod` issue where some items returned from the `v3/statutes` endpoint have a `null` `source_url` field; this is not being handled appropriately and is throwing an error in the console and not rendering some rows correctly.
- updates `statuteCompilationUrl` utility method to expect `null` prop and to early return `null` in response
- updates `BodyCell.vue` component to handle `null` response from `statuteCompilationUrl` and render "None" instead of an anchor
- Extends unit tests and snapshot tests to add coverage for new functionality
1. All Vitest tests pass
2. All Cypress tests pass

[HOTFIX] Null source_url in statute response item causing console/rendering error

---

solution/backend/regulations/admin.py
solution/backend/regulations/tests/fixtures/statute_link_data.xml
solution/backend/regulations/tests/fixtures/statute_link_golden.json

Resolves #2005
Post-hyphen words in section descriptions were being cut off. This was due to the section append regex substituting it for blank.
- Only substitute first section append regex match with blank (fixes this case)
- Tests updated
1. Run unit tests
2. Import https://www.govinfo.gov/content/pkg/COMPS-8768/uslm/COMPS-8768.xml on the admin panel
3. Check `Title 42 section 1860D-22 → 42 USC 1395w-132` and verify the description is "Special rules for employer-sponsored programs." and not "Special rules for employerprograms.".

EREGCSC-2005 Section descriptions with hyphens get abbreviated

---

.github/workflows/git-secrets.yaml
solution/backend/cmcs_regulations/settings/base.py
solution/backend/cmcs_regulations/urls.py
solution/static-assets/requirements.txt

Resolves # EREGCSC-2041
In order for us to set up oAuth we need a call back url.  This is getting us set up.
- A call back url is set up for our app at {{host}}//oidc/callback/
1. Go to https://gqhz3je798.execute-api.us-east-1.amazonaws.com/dev914/oidc/callback  .  You will see a forbidden message.  We do not have a client secret yet so it wont work.
2. Go to the admin panel and log in.  You should be able to log in still with the old method of django.  You can do this either through your local or the dev site.  We expanded the django auth backends to include a new method as well as the old method.  Without explicitly adding the old method in settings it will not work.

EREGCSC-2041 -- Set up url and configs for OIDC

---

solution/backend/cmcs_regulations/settings/base.py
solution/backend/cmcs_regulations/settings/eua_settings.py
solution/backend/cmcs_regulations/urls.py

Resolves #
There seems to be an issue with django admin when someone changes their password.  We arent to sure the cause but it might have something to do with the OIDC login not being fully set up yet.  We are seprating the OIDC settings to its own file.  OIDC settings will not be used yet.  This was going to be done in a later stage but this might fix the issue we are seeing.
- OIDC settings are split into its own settings file.  This will not be used yet.
1.  Go to the dev admin site for the experimental branch: https://x3l5zt4in1.execute-api.us-east-1.amazonaws.com/dev921/admin/
2. login with the account
3. change the password
4. log out and log back in.
1. Prod login for admin is working.

oidc removal

---

solution/backend/regulations/templatetags/citation.py

Resolves # ERGCSC-2046
The external link icon is missing on citations for sections in the reader view.  This is to add the icon
- An external link icon will appear on citations in sections
1. Go to any subpart view that has a sections in it that have citations.
2. All hyperlinks will have the external link icon in it.

EREGCSC-2046 -- Add external link icon to citation

---

.pre-commit-config.yaml
solution/backend/regulations/templates/regulations/partials/header.html
solution/ui/e2e/cypress/e2e/part.spec.cy.js

Resolves [EREGCSC-2086](https://jiraent.cms.gov/browse/EREGCSC-2086)
This PR fixes a regression where the Title and Part dropdown selects are not pre-populated with the correct title and part when the user is at the Part ToC or the Part Reader view.
This feature was originally implemented as part of [EREGCSC-1564](https://jiraent.cms.gov/browse/EREGCSC-1564) but was broken some time after that; likely during additional header work.
- Passes in `title` and `part` as props to the JumpTo Vue component if those values exist in the context of the Django view
1. Go to the reader view for a part and make sure the Jump To selects in the header are populated with the correct title and part

EREGCSC-2086 -- Jump To fixes

---

solution/ui/regulations/eregs-component-lib/src/components/SupplementalContent.vue

Resolves [EREGCSC-2112](https://jiraent.cms.gov/browse/EREGCSC-2112)
The default page size when requesting supplemental content from the `resources` API endpoint is 100 items.  Some sections have more than 100 items attached to them.  As a result, some resource items were not being returned or displayed in the resources sidebar.
- overrides default `pageSize` parameter to be `1000` instead of `100`
1. Visit [Part 440 Section 180](https://47kar1x2vj.execute-api.us-east-1.amazonaws.com/dev927/42/440/Subpart-A/2020-12-16/#440-180) 
2.  In the right sidebar, expand "Subregulatory Guidance" and then expand "State Medicaid Director Letter (SMDL)" subcategory 
3. Scroll to the "Show More" button and note how …

EREGCSC-2112 -- Resources sidebar in reader view missing items

---

solution/backend/regulations/templates/error_base.html
solution/backend/regulations/templates/regulations/statute.html
solution/backend/regulations/views/statute.py
solution/ui/e2e/cypress/fixtures/statute-dates.json
solution/ui/regulations/css/scss/partials/_statutes.scss
solution/ui/regulations/eregs-component-lib/src/components/shared-components/Statutes/StatuteTable.vue
solution/ui/regulations/eregs-component-lib/src/components/shared-components/Statutes/schemas/tableSchemas.js
solution/ui/regulations/eregs-component-lib/src/components/shared-components/Statutes/table-elements/HeaderCell.test.js
solution/ui/regulations/eregs-component-lib/src/components/shared-components/Statutes/table-elements/HeaderCell.vue
solution/ui/regulations/eregs-component-lib/src/components/shared-components/Statutes/table-elements/__snapshots__/HeaderCell.test.js.snap
solution/ui/regulations/eregs-component-lib/src/components/shared-components/Statutes/utils/dateMethods.js
solution/ui/regulations/eregs-component-lib/src/components/shared-components/Statutes/utils/dateMethods.test.js

Resolves [EREGCSC-2113](https://jiraent.cms.gov/browse/EREGCSC-2113)
Pulls dates from site configuration in admin panel into front end for Statute Table column header labels.
- Adds statute table site configuration labels and dates into Statutes template using [best practice](https://adamj.eu/tech/2022/10/06/how-to-safely-pass-data-to-javascript-in-a-django-template/)
- Only shows dates if both label and date exist, and if date is a valid date
- Updates snapshot tests and adds unit front end unit test coverage
1. Go into [admin panel for experimental deployment](https://1ghm0p11p3.execute-api.us-east-1.amazonaws.com/dev929/admin/) > Regulations > Site Configuration
2. Edit Date Type and Date
3. Try …

EREGCSC-2113 -- Reflect edited statute dates in frontend

---

solution/backend/regulations/templates/regulations/partials/sidebar_right.html
solution/backend/regulations/views/reader.py
solution/ui/regulations/eregs-component-lib/src/components/SupplementalContent.vue
solution/ui/regulations/eregs-component-lib/src/components/SupplementalContentCategory.vue
solution/ui/regulations/msw/mocks/categories.js
solution/ui/regulations/test/unit-test/SupplementalContent.test.js
solution/ui/regulations/test/unit-test/__snapshots__/SupplementalContent.test.js.snap
solution/ui/regulations/utilities/utils.js

Resolves[ EREGCSC-2111 ](https://jiraent.cms.gov/browse/EREGCSC-2111)
The right sidebar of the reader view has resources categories that can have or not have children.  We should have the ability to show or hide these categories even if they are empty.  Unfortunately, this was being incorrectly filtered in the Django view and wasn't working properly.  
This PR will move the logic to determine showing or hiding an empty category to the front end.
- No longer passes `sub_categories` into the template from the Django view.  This was refactored long ago to just pass in an empty object; we don't need to do that, so it has been removed.
- Removes code and logic everywhere (Vue component, utility function, unit tests) that assumed an empty …

EREGCSC-2111 -- Determine ShowIfEmpty status for sidebar items on the front end

---

solution/backend/pyproject.toml
solution/backend/regcore/models.py
solution/backend/regulations/tests/test_statute_links.py
solution/backend/regulations/views/utils.py
solution/backend/resources/admin.py
solution/backend/resources/tests/test_queryset_functions.py
solution/backend/resources/views/mixins.py

Resolves # EREGCSC-2027
Rule E for Ruff has some rules that are not included in the E by default.  In order for us to eventually remove flake8 these rules will need to be added.  
The rules for E were put after the rest of the rules for readability.  Not many of these rules have autofix currently.
https://beta.ruff.rs/docs/rules/#error-e
- Adds missing "E" rules for ruff.
- A couple spaces were added for  compliance to the rules
1. Ruff runs correctly on the branch.
2. Experimental deploys correctly.

EREGCSC-2027 -- Adding ruff rules for E

---

solution/backend/regulations/templates/regulations/base.html
solution/backend/regulations/templates/regulations/partials/login_indicator.html
solution/backend/regulations/templates/regulations/reader.html
solution/backend/regulations/urls.py
solution/backend/regulations/views/reader.py
solution/ui/regulations/css/scss/_layout.scss

Resolves [EREGCSC-2144](https://jiraent.cms.gov/browse/EREGCSC-2144)
We need to shown authenticated-only content on eRegs *outside* of the admin panel.  
- Adds `login_indicator.html` template partial that indicates if user is logged in and provides link to log out
1. Go to [experimental deployment](https://v77jx88gn1.execute-api.us-east-1.amazonaws.com/dev934/)
2. Log in using the admin panel
3. Return to experimental deployment.  In the bottom right corner of the screen you should see a little sticky div that contains a green indicator and a "Hello!" Greeting that includes your username.
- There should also be a "Log Out" link to the right of your username
5. Make sure the logged in indicator at the …

EREGCSC-2144 -- Show authenticated-only content in eRegs

---

.github/workflows/deploy-experimental.yml
.github/workflows/deploy.yml
solution/backend/cmcs_regulations/context_processors.py
solution/backend/cmcs_regulations/settings/base.py
solution/backend/regulations/templates/error_base.html
solution/backend/regulations/templates/regulations/about.html
solution/backend/regulations/templates/regulations/base.html
solution/backend/regulations/templates/regulations/cache.html
solution/backend/regulations/templates/regulations/homepage.html
solution/backend/regulations/templates/regulations/reader.html
solution/backend/regulations/templates/regulations/regulation_landing.html
solution/backend/regulations/templates/regulations/resources.html
solution/backend/regulations/templates/regulations/search.html
solution/backend/regulations/templates/regulations/spa_base.html
solution/backend/regulations/templates/regulations/statute.html
solution/backend/serverless-experimental.yml
solution/backend/serverless.yml

Resolves [EREGCSC-1848](https://jiraent.cms.gov/browse/EREGCSC-1848)
We want to be able to push CSS and JS updates to the site at any time of day and have users transparently download the newest, latest CSS/JS files even if they've already visited the site that day. This should not require any action from the user. They should just be served the newest, freshest JS/CSS files by the browser as soon as they have been deployed.
This means the browser must be told that something has changed and that it should fetch a new copy of the CSS/JS files from the server instead of using a cached local copy.
We are going to grab an [artifact from the Github Action workflows called `run_id`](https://docs.github.com/en/actions/learn-github-actions/contexts#about-contexts), which is …

EREGCSC-1848 -- better JS/CSS cache busting, take two

---

.github/workflows/deploy.yml

Resolves [EREGCSC-1848](https://jiraent.cms.gov/browse/EREGCSC-1848)
The `dev`/`val`/`prod` `deploy.yml` file is constructed a bit differently than our `deply_experimental.yml` file.  What was all encapsulated in a single step in `deploy_experimental.yml` is spread across two steps in `deploy.yml`, but the new environment variable `RUN_ID` was only added to the first step.
- adds `RUN_ID` to the `env` of the "Populate Content for {{ environment }}" step
1. Merge this PR to main and make sure `dev`/`val`/`prod` deployments work as expected.

[Hotfix] EREGCSC-1848 -- hotfix to add github.run_id to deploy step that needs it

---

.github/workflows/remove-experimental.yml

Resolves [EREGCSC-1848](https://jiraent.cms.gov/browse/EREGCSC-1848)
The `remove-experimental.yml` file needs the new environment variable RUN_ID that was recently added to the deploy `yml` files.
- adds `RUN_ID` to the `env` to the remove steps that need it
1. Make sure the `remove_experimental` step works for this PR once it has been merged to `main`
2. Note that Remove Experimental was successful when this PR was previously closed: https://github.com/Enterprise-CMCS/cmcs-eregulations/actions/runs/5964740287

[Hotfix] EREGCSC-1848 -- hotfix to add github.run_id to Remove Experimental step that needs it

---

solution/backend/serverless-experimental.yml
solution/backend/serverless.yml

The deploy step failed for deploy on expermimental.  This is because s3 bucket names need to be GLOBALLY unique, beyond just our application.
- Deploy.yml will work correctly.  The s3 bucket name is now presumably more unique to our app.
1. Deploy works in our environments

Fixing issue with deploy

---

solution/backend/serverless-experimental.yml
solution/backend/serverless.yml

Resolves # EREGCSC-2193
The api gateway needs to allow media types to process in order for our file repo to work properly.  Without it the gateway will cause files to not uplaod properly.
- Configurations for the api gateway at deploy
1. The api gateway for the dev branch will have the correct settings.
2. FIle upload will allow files to upload and not be blank.

EREGCSC-2193 API gateway configurations for file upload

---

README.md
solution/Makefile
solution/backend/cmcs_regulations/fixtures/auth.permission.json
solution/backend/cmcs_regulations/fixtures/contenttypes.contenttype.json
solution/backend/common/functions.py
solution/backend/file_manager/fixtures/file_manager.documenttype.json
solution/backend/file_manager/fixtures/file_manager.subject.json
solution/backend/regcore/management/commands/emptyseedtables.py
solution/backend/regcore/search/fixtures/search.synonym.json
solution/backend/regulations/fixtures/regulations.regulationlinkconfiguration.json
solution/backend/regulations/fixtures/regulations.statutelinkconfiguration.json

Resolves # EREGCSC-2196
Sets up seed data for  subjects and document types for file uploads
- Seed data will populate for these in our basic seed commands as well as our environments.
Make sure your database is up to date in main and run "make local.seed"
Log into the admin panel, you should see document types and subjects populated.
On the environment you should see the same.

EREGCSC-2196 Seed data for file manager

---

solution/backend/file_manager/admin.py
solution/backend/serverless-experimental.yml
solution/backend/serverless.yml

Resolves # EREGCSC-2217
Security scan issue on our S3 bucket due to it not requiring SSL.   This merely adds it.
- SSL is required for accessing the bucket
1. Bucket upload works successfully as well as retrieval.  Upload and download a doucment.  Full verification wont be done until it hits prod.
2.  Bucket was first created with the ticket without SSL.  Item was uploaded.  Then SSL was added.  Item was still accessible.  This test was done to make sure it wouldnt rewrite the existing bucket.

EREGCSC-2217 - Buckets use SSL

---

solution/backend/serverless.yml

Resolves # EREGCSC- 2217
Indention was off in serverless.yml.  This is to fix it.

fix indent in serverless.yml

---

.github/workflows/schedule-jira-sync.yml
.github/workflows/snyk-test.yml

Added Slack notification for security scan job failure 
Description-
Added a slack notification step to allow notification to be sent to shared-eregs-dev-bots channel  for both nightly snyk security scan and Sync Security Hub and Jira workflows  
This pull request adds 
Alert Slack On Failure step for both workflow
steps to manually verify this change
In this GitHub repo under .github/workflows/snyk-test.yml and .github/workflows/schedule-jira-sync.yml
comment one of the fields in the steps i.e jira-host: ${{secrets.JIRA_HOST}}
Specifically, the workflow to trigger when there is a push
on:
push:
branches: [ branchName ]
save the yaml file, that should trigger workflow to run 
save the file

EREGCSC-1562 - Slack notifications for Snyk scan & Sync Security Hub and Jira

---

solution/backend/cmcs_regulations/settings/base.py
solution/ui/e2e/cypress/e2e/homepage.spec.cy.js

Resolves [EREGCSC-2296](https://jiraent.cms.gov/browse/EREGCSC-2296)
The "sign up for a session" link in the homepage footer goes to the homepage.  It should go out to a signup google doc.
- Adds `SIGNUP_URL` back to `base.py`.
1. Visit the [experimental deployment](https://y1wso3q2b2.execute-api.us-east-1.amazonaws.com/dev985)
2. The "Sign up for a session" link on the homepage takes you to a google doc and does not refresh the eregs homepage.

EREGCSC-2296 -- "Sign up for session" link fix

---

.github/workflows/schedule-jira-sync.yml

Followup to PR #972 to resolve [EREGCSC-1562](https://jiraent.cms.gov/browse/EREGCSC-1562)
Fixed the indentation that was creating an error and failing the Slack notification step in Sync Security Hub and Jira workflows.
**This pull request adds**
Corrected syntax
Verify line 40-42 indentation is correct.
See also the manual verification steps from PR #972.

EREGCSC-1562 - Fixed the indentation on Slack integration step

---

solution/backend/cmcs_regulations/settings/base.py

Resolves #[EREGCSC-2257](https://jiraent.cms.gov/browse/EREGCSC-2257)
We recently introduced a new domain, 'eregulations.cms.gov,' into our system and configured our API Gateway to accommodate it. However, we encountered an error in our AWS logs that reads: "ERROR Invalid HTTP_HOST header: 'eregulations.cms.gov.' The resolution to this issue involves adding 'eregulations.cms.gov' to the list of allowed hosts in our Django settings file, which, in our case, is 'base.py.' This adjustment will enable our application to properly handle requests from the 'eregulations.cms.gov' domain.
- base.py
This may not be easy to verify if it fixes the issue till we push to prod. But we should check make sure it …

EREGCSC-update-allowed-hosts

---

solution/ui/e2e/cypress/e2e/policy-repository.spec.cy.js
solution/ui/e2e/cypress/fixtures/policy-docs.json
solution/ui/regulations/eregs-vite/src/components/policy-repository/PolicyResults.vue

Resolves bug where Policy Repository result item does not properly link to the regulation section
When the Results Item was refactored a few stories ago, changes were made to how the `baseUrl` for API calls is injected into the appropriate components.  
Previously, `base` was provided in the `PolicyRepository.vue` view and injected directly into the `RelatedSections.vue` component.
Now, `RelatedSections.vue` and all of the `ResultItem`'s child components are controlled components that only accept passed in props from a parent.  Injected parameters (via provide/inject) are injected to the closest "container" ancestor and then passed in to the controlled child components.
- Injects `base` where needed
- Passes `base` into `RelatedSections.vue` …

[HOTFIX]  Policy Result citation link fix

---

solution/backend/file_manager/serializers.py
solution/backend/file_manager/tests/fixtures/sample_supplemental.json
solution/backend/file_manager/tests/test_urls.py
solution/backend/file_manager/views.py

Resolves # EREGCSC-2295
To easily list how many resources are associated to a subject we want the endpoint to reveal in a count how many are related to the subject.  There are two fields added that will list the counts:
external_resources
uploads
Go into swagger.
make sure you have resources of internal and external assigned to some subjects.
Call the subjects endpoint.  
Uploads field will relfect how many internal_resources are associated to the subject.
external_resources will refer to how many abstract resources are assigned to the subect.
New unit test will pass.

EREGCSC-2295 Add sort count to subjects

---

solution/backend/content_search/functions.py
solution/backend/content_search/tests/test_functions.py
solution/backend/content_search/views.py
solution/backend/index_resources.py

Resolves # Issue regarding non approved content in the index
This will make it so only approved FRDocs and supplemental content are indexed.  If a piece is marked to false, it will remove it from the index.
- Anything not approved will not appear in the index.
1. Click this link and you should get no results
https://3mkeajv1n1.execute-api.us-east-1.amazonaws.com/dev1011/v3/content-search/?q=bibbity
2. In the admin go to the supplemental content with the name of bibbity and switch it to approved.
3. redo the search and it will return just that piece of content
4. Switch it back to not approved and redo the search
5. It will now no longer appear in the search

Hotfix approved only index

---

solution/backend/serverless-experimental.yml
solution/ui/e2e/cypress/e2e/policy-repository.spec.cy.js
solution/ui/regulations/eregs-vite/src/components/policy-repository/SubjectSelector.vue
solution/ui/regulations/eregs-vite/src/components/policy-repository/SubjectTOC.vue

Resolves issue on production where wrong data type is being pushed into router state. A string is being treated as an array, which is splitting the string into characters when updating the route's query params.
The flow to reproduce this bug consistently:
1. Visit `/policy-repository`
2. Click on a subject near or at the bottom of the Table of Contents (so the subject ID has a high number with more than one digit. ex: 190)
3. Add one more subject using the sidebar subject selector
Expected result:
Two subjects will be selected
Actual result:
Three or more subjects will be selected
- ToC click will push a string wrapped in an array into router state instead of just a string so all existing functionality will work as expected
- Adds Cypress …

[HOTFIX] Clicking ToC and then adding subjects

---

solution/ui/e2e/cypress/e2e/policy-repository.spec.cy.js
solution/ui/regulations/eregs-vite/src/components/policy-repository/SubjectSelector.vue
solution/ui/regulations/eregs-vite/src/views/PolicyRepository.vue

Resolves [EREGCSC-2330](https://jiraent.cms.gov/browse/EREGCSC-2330)
If you follow a link to a subject with a multi-digit ID number and then add another subject, you end up with unexpected subjects selected.
**Steps to reproduce:**
1. Visit the `prod` site using a link that already has a subject with a multi-digit id selected.  
- Ex: https://eregulations.cms.gov/policy-repository/?subjects=219
2. Add another subject by clicking on any subject in the Subject Selector in the sidebar
- Ex: Access to Services (id: 3)
**Expected result:**
- `&subjects=3` is appended to the end of the URL and the URL should look something like: `https://eregulations.cms.gov/policy-repository/?subjects=219&subjects=3`
**Actual result:**
- `?subjects=219` is split into …

EREGCSC-2330 -- Fix unexpected subjects [BUGFIX]

---

solution/backend/serverless-experimental.yml

Resolves # HOTFIX lambda resource
The text extractor arn is different on normal environments and needs to be the one for main dev.  Right now its trying to grab one that doesnt exist.
- the permission granted to the lambda is correct.
1. Deploy experimental builds properly

hotfix deployexperimental lambda perm fix

---

solution/ui/regulations/package.json

Resolves regression introduced with updated version of CMS Design System
[Snyk created a Pull Request](https://github.com/Enterprise-CMCS/cmcs-eregulations/pull/1042) that bumped CMS Design System's NPM package from v2.5.0 to 2.13.0.  This was merged into `main` before it was discovered that it introduced a regression where the focus styles (outline and background) were changed and did not always look good.
- Reverts CMS Design System package version to 2.5.0
1. Tab around the homepage and make sure the focus styles aren't pink outlines and sometimes white backgrounds

[Hotfix] Revert CMS Design System back to v2.5

---

solution/ui/regulations/css/scss/partials/_search.scss

Resolves regression involving external link icon on the Resources results on the combined search page.
See this link: https://eregulations.cms.gov/search/?q=%22Electronic%20Visit%20Verification%22
When styling the policy repository results and adding the Download File chip, some styles leaked into the Combined Search page's Resources column and the external link icon was out of place:
The description of the result item would also become split unexpectedly.
- Tweaks resources page result item style so that it is not affected by Policy Repository style
1. Visit the [experimental deployment's Search Page using the same query string as used in the prod link …

[Hotfix] Search page resources external link style regression

---

solution/backend/content_search/models.py
solution/backend/content_search/serializers.py
solution/backend/content_search/tests/test_search.py

Resolves # EREGCSC-2339
Adds headline for content for contentsearch.
- A content field will be returned in the api for contentsearch.
- 
1. Make sure a value in the index has something for content.  Do a search for "dummy" on the policy repository api.
2. A piece of content with dummy will appear in the content search headline.

EREGCSC-2339 Add content search headline

---

solution/ui/e2e/cypress/e2e/policy-repository.spec.cy.js
solution/ui/regulations/eregs-vite/src/components/policy-repository/SubjectSelector.vue

Resolves [EREGCSC-2354](https://jiraent.cms.gov/browse/EREGCSC-2354)
If I'm viewing a subject and choose another subject, replace the current materials with the new materials. (No other changes to persistence of search query, etc.)
- When clicking on a subject in the subject selector, the clicked subject overwrites any existing subject(s) in the URL
- Updates cypress tests to reflect this new reality
1. Visit the experimental deployment
2. Start clicking on subjects using the left sidebar's Subject Selector
3. There the subject you click should always replace the existing subject.  There should never be a time where two subjects are selected at once (unless you manually edit the URL to do so).

EREGCSC-2354 -- only allow one subject to be selected at a time

---

solution/ui/e2e/cypress/e2e/policy-repository.spec.cy.js
solution/ui/regulations/eregs-vite/src/components/policy-repository/SubjectSelector.vue

Resolves [bug found during usability session](https://macbis.dovetailapp.com/data/4Q3jRiivCOibNIGnbN6eMq#:v:h=40GrWiVxS6z4zD3ZWqwWlo&s=1) where pressing enter in the subject typeahead input refreshes the page and removes all query parameters.
The subject typeahead filter is a form input.  Forms fire a `submit` event when enter is pressed in an input.  This `submit` event is not what we want -- it is refreshing the page when we don't want it to refresh the page.
**Steps to Reproduce**
1. Visit the [policy repository on `prod`](https://eregulations.cms.gov/policy-repository/)
2. type something into the subject typeahead filter input in the right sidebar
3. Press enter
Expected result: Nothing happens
Actual Result: The entire page reloads with all query/filter parameters …

[Hotfix] Prevent submit on subject typeahead form input

---

solution/backend/content_search/models.py
solution/text-extractor/serverless.yml

Resolves # HOTFIX
Removed hightlight all from content_headline.  Was returning the full content and ignoring minimum words
- All of content wont be returned on content_headline.

Hotfix:  All of content is being returned

---

solution/ui/e2e/cypress/e2e/policy-repository.spec.cy.js
solution/ui/regulations/eregs-vite/src/components/policy-repository/SubjectChip.vue
solution/ui/regulations/eregs-vite/src/components/policy-repository/SubjectChips.vue

Resolves [EREGCSC-2351](https://jiraent.cms.gov/browse/EREGCSC-2351)
The subject chips underneath each internal Policy Document item should have a `title` attribute that contains the full name of the subject, so when users hover over the chip with their cursor, it acts like a tooltip.  This is useful for chips that display the short name or the abbreviated name; the full name always exists, and it can add clarity and context as a tooltip.
- Passes `subject.full_name` into `SubjectChip.vue` as `title` prop, and then uses that prop as the `title` attribute for each subject chip.
1. Visit the [experimental deployment](https://1uc01wqwla.execute-api.us-east-1.amazonaws.com/dev1064) and go to the policy …

EREGCSC-2351 -- Tooltip for subject chip with full name

---

solution/ui/e2e/cypress/e2e/policy-repository.spec.cy.js
solution/ui/regulations/css/scss/partials/_policy_repository.scss
solution/ui/regulations/eregs-vite/src/components/policy-repository/PolicyResults.vue

Resolves [ERERGCSC-2344](https://jiraent.cms.gov/browse/EREGCSC-2344)
External documents on the Policy Repository page (the Public documents) are external resources that, when clicked, take the user away from eRegs.  As such, these links should have the [external link icon](https://d147x1jcgm8uq1.cloudfront.net/images/external-link.svg) appended at the end to indicate to the user that they will leave eRegs if the click the link.
- Adds `external` class to Policy Repository result items if they have a document type of "external"
- Tweaks style so that the external link icons appear inline with the link
- Adds a few Cypress assertions to ensure the `external` class is only applied where expected
1. …

EREGCSC-2344 -- External link icon on Public policy repository repo links

---

solution/ui/regulations/eregs-component-lib/package-lock.json
solution/ui/regulations/eregs-component-lib/package.json
solution/ui/regulations/eregs-vite/package-lock.json
solution/ui/regulations/eregs-vite/package.json
solution/ui/regulations/eregs-vite/vite.config.js
solution/ui/regulations/package-lock.json
solution/ui/regulations/package.json

Vite 5 was [released on 16 November 2023](https://vitejs.dev/blog/announcing-vite5).  This major version release mostly introduces a changes under the hood, mainly performance upgrades via upgrading to Rollup4.  It also refactors some things to "future proof" this version of Vite.  [See here for more details](https://vitejs.dev/guide/migration).
We are currently on Vite ^4.5.
- Changes Vite version numbers in `package.json` files from `^4.5` to `^5.0`
- Handles CJS/CommonJS deprecation based on Migration Guide 
- add `"type": "module"` in `package.json`
- `import` instead of `require` in vite config
- Upgrade Vite's official Vue2 plugin to the [latest version that has Vite v5 support](https://github.com/vitejs/vite-plugin-vue2/blob/main/CHANGE …

[Tech Debt] Upgrade to Vite 5

---

solution/ui/e2e/cypress/e2e/policy-repository.spec.cy.js
solution/ui/regulations/css/scss/partials/_policy_repository.scss
solution/ui/regulations/eregs-vite/src/components/policy-repository/SubjectSelector.vue

Resolves [EREGCSC-2370](https://jiraent.cms.gov/browse/EREGCSC-2370)
Move explicit label into input as a placeholder to better prompt users to use the subject filter. Based on user research session.
- Removes explicit label and its associated styles
- adds label contents into input's `placeholder` attribute
- adds `aria-label` attribute for a11y
- asserts that `placeholder` attribute exists and is correct in e2e test suite
1. Visit policy repository on the experimental deployment
2. Make sure the subject filter input only has a placeholder and not an explicit label (compare to prod)

EREGCSC-2370 -- Move "Filter the subject list" into input field

---

solution/ui/e2e/cypress/e2e/policy-repository.spec.cy.js
solution/ui/regulations/css/scss/partials/_results_item.scss
solution/ui/regulations/eregs-component-lib/src/components/shared-components/results-item-parts/CategoryLabel.vue
solution/ui/regulations/eregs-component-lib/src/components/shared-components/results-item-parts/DocTypeLabel.test.js
solution/ui/regulations/eregs-component-lib/src/components/shared-components/results-item-parts/DocTypeLabel.vue
solution/ui/regulations/eregs-component-lib/src/components/shared-components/results-item-parts/__snapshots__/DocTypeLabel.test.js.snap
solution/ui/regulations/eregs-vite/src/components/policy-repository/DocumentTypeSelector.vue
solution/ui/regulations/eregs-vite/src/components/policy-repository/PolicyResults.vue
solution/ui/regulations/utilities/utils.js

Resolves [EREGCSC-2371](https://jiraent.cms.gov/browse/EREGCSC-2371)
Before the Category and SubCategory labels, we need to add a new label that indicates if a result is an Internal document or a Public document.
- adds new `DocTypeLabel` Vue component and related styles
- slightly amends `DOCUMENTS_TYPE_MAP` to exclude the "resources" suffix so that it is more portable
1. Visit policy repository on experimental deployment and add some filters
2. Public documents should have a "Public" label with a "users" icon
3. Internal documents should have an "Internal" label with a "key" icon
4. Make sure it reasonably matches the labels on [this Figma comp](https://www.figma.com/file/D6uem0JreimXr433ttqKwR/Doc-t …

EREGCSC-2371 -- Add Document Type labels to Policy Repo search results

---

solution/backend/content_search/models.py

Resolves # Hotfix- max words up to 400!
Max words is at 400 right now.  Needs to be less.  lowering max words to 51.  Max has to be more than min which is 50.
- Lowers max words from 400 to 51.
1. https://pv4sk34lu6.execute-api.us-east-1.amazonaws.com/dev1080/policy-repository?q=covid no long descriptions will appear.
2. https://pv4sk34lu6.execute-api.us-east-1.amazonaws.com/dev1080/policy-repository?q=document no long snippets will appear.

hotfix - max words limit

---

.github/workflows/schedule-jira-sync.yml
.github/workflows/snyk-test.yml

Resolves #
Configured a new Environment in GitHub [prod-security-hub](https://github.com/Enterprise-CMCS/cmcs-eregulations/settings/environments/1673789773/edit) to allow the nightly security hub to jira integration workflow to run successfully with out manual approval
Created OIDC AWS IAM role in prod account with a limited permission (permission only to Security Hub) and configured it in the new environment as a secret 
For Security hub workflow changed the environmental value under matrix to  ["prod-security-hub"]
Also configured jira credential as a secret in the new environment 
Updated snyk security scan workflow action to Enterprise-CMCS/macfc-security-scan-report@v2.7.4
For snyk test …

updated environment value and action version

---

solution/backend/file_manager/admin.py

Resolves # EREGCSC-2267 Sanitize file names
We want to make sure filenames dont have weird characters in it.  Before we only did commas but now we are just adding a slew of them
- Use djangos slugify to clean out characters. https://docs.djangoproject.com/en/4.2/ref/utils/#django.utils.text.slugify
1. Log into the admin panel.
2. Upload a file with a bunch of weird characters. Quotes, underscores, hyphens etc.
3. Characters will be cleaned out after saving.  Should be mostly alphanumeric.

EREGCSC-2267 Sanitize filenames

---

.github/workflows/deploy-experimental.yml
.github/workflows/remove-experimental.yml
solution/backend/serverless-experimental.yml

Resolves # None.  An idea I came up with
Its very annoying working with the text extractor.  Commenting and uncommenting out code on deploy is tedious and just awful.  A much simpler solution is to have a conditional on a github action that determines if it should run.  
On line 84 on deploy-experimental it just has if: false. Change it to if: true if you want a text extractor.
Then on line 122 change the needs to be the commented out portion.  Needs cant actually be a conditional. Thanks github.
1. The intieal deployment deploys sucessfully.
2. Change the deploy to true for deploying the text extractor on line 84 and on 122 change it to needs: [deploy-static, deploy-text-extractor]
3. A text extractor will deploy to the …

Extractor conditonal deploy

---

solution/backend/cmcs_regulations/settings/base.py
solution/backend/content_search/views.py

Resolves # Textract ARN not being picked up properly
The default for textract arn should be dev unless one is being created by the environment.  The conditional for working on it is changed to pull in both at deployent
The logic for the textextractor arn being pulled in correctly.  Now it pulls both so it will just check if the value is blank or not.
- Default of using textetractor for dev works fine.
1. Upload a file into the s3 bucket through the admin page. https://sif8c3kmp9.execute-api.us-east-1.amazonaws.com/dev1103/admin/
2. Get content of the file. 
3. Should use the dev text extractor.

Textract ARN hotfix

---

solution/backend/file_manager/admin.py
solution/backend/file_manager/tests/test_admin.py

Resolves # EREGCSC-2267
Sanitize file names was working a little  weird with the django library in place so we are doing a more custom solution.
Certain characters will be removed from file names on a small list.  This is similar to the previous method we used.
- File name sanitation
1. Upload a file name with 'bad' characters to the file repository.  Try things like semicolons, exclamation points, *, ?, commas.  windows doesnt let you put these in there.  Try with any of the characters in this list. ";", "!", "?", "*", ":", ",", '"', '“', "'", r'/', '\\', '-'
After uploading the file on upload it will remove those characters in the file name.
new unit test pass.

EREGCSC-2267 sanitize file names

---

.github/workflows/snyk-test.yml
SnykReadMe.md

Resolves #[EREGCSC-2416](https://jiraent.cms.gov/browse/EREGCSC-2416)
Just finishing off the secret cleanup effort by updating the Snyk Workflow to use the same JIRA variables as the SecHub Workflow so that there can be less Jira secrets in all the environments as well as in the general section.
the Snyk workflow to reflect the secret name changes as well as the Snyk ReadMe to do the same.
Verify in the Snyk workflow that the jira token name was changed from JIRA_TOKEN_FOR_SNYK to JIRA_TOKEN.
In the Readme, Verify the same name change for the token and also the HOST secret name was changed to JIRA_HOST. Also the Username references were removed as Username is no longer used.

EREGCSC-2416 - Secret cleanup test

---

.github/workflows/deploy-experimental.yml
solution/ui/regulations/eregs-vite/src/components/policy-repository/PolicyResults.test.js
solution/ui/regulations/eregs-vite/src/components/policy-repository/PolicyResults.vue

Resolves [EREGCSC-2410](https://jiraent.cms.gov/browse/EREGCSC-2410)
Ellipses need to be visible when the displayed text snippet is taken from a search result match and no other times.
- Adds ellipses surrounding `summary_headline` and `content_headline` entries when displayed 
1. Visit [experimental deployment](https://otqgrzx0h2.execute-api.us-east-1.amazonaws.com/dev1112)
2. Upload docs and populate indices for some internal and external documents
3. Search against those indices, as well as against keywords in item summaries
4. Ensure that only snippets based on text searches are surrounded by ellipses

EREGCSC-2410 -- Updated snippet ellipses logic

---

.github/workflows/deploy-experimental.yml
solution/backend/serverless-experimental.yml
solution/text-extractor/extractors/email.py
solution/text-extractor/extractors/outlook.py
solution/text-extractor/extractors/tests/fixtures/eml_pdf_expected.txt
solution/text-extractor/extractors/tests/test_email.py
solution/text-extractor/extractors/zip.py
solution/text-extractor/text_extractor.py

Resolves #2252
Text extractor was failing for some files with other files contained within them. This PR fixes it.
- Attachment files that fail to extract will not cause the entire extractor lambda to fail.
- Failures are instead logged to Cloudwatch. (using Python logging library)
- Added support for Outlook "msg" files that contain embedded "msg" data. Previously this would cause a failure because this embedded data lacks a filename.
- Lambda return message is also logged to Cloudwatch.
**Follow up work**
- We need more fixture files to find edge cases with these types of files. We can't use policy repo files since they may contain sensitive information including private email addresses etc. So we need someone with Outlook to create test …

EREGCSC-2252-B Fix attachment extraction for zip, eml, and msg files

---

solution/ui/regulations/css/scss/partials/_search.scss

Resolves issue on `prod`
From Slack: "Looks like extra newlines have sometimes slipped into our formatting of reg search result section names"
This regression was introduced in [EREGCSC-2293](https://jiraent.cms.gov/browse/EREGCSC-2293): using flexbox with a gap for results items is not working well with the reg text results on the search page.
- Adds `display: block` to `.result__link a` when on the search page to override flexbox styles on the reg text column of the search page only
1. Search for "direction" on prod and compare the left column search results to screenshot in a comment below.  This is the bug -- there is extra spacing between the wrapped lines of the reg result section name
2. …

[Hotfix] Extra newlines in reg search result section names

---

solution/backend/cmcs_regulations/settings/deploy.py
solution/backend/common/serializers/mix.py
solution/backend/content_search/views.py
solution/backend/file_manager/serializers/groupings.py

Resolves #2345
The v3 content-search endpoint was failing with a 500 error if an uploaded file was assigned to a category. The cause of this was twofold:
1. Repository categories were not prefetched with `select_subclasses()`, causing the type to be `AbstractRepoCategory`.
2. When passed to the relevant polymorphic serializer, the use of `Serializer(object).data` caused a failure because the parent serializer was returning "Serializer not available" (due to `object` being an `AbstractRepoCategory`), which was not serializable as a _dict_. Instead, using `Serializer().to_representation(object)` allows for arbitrary data types.
- These issues are resolved.
1. Upload a file (with a name or …

EREGCSC-2345-B Fix 500 error during content search

---

solution/backend/regulations/logout.py

Resolves #hotfix for logout eua session
when deployed to prod the logout redirect url adds prod in the url which does not match with what okta is configured. To fix it we remove the word prod out of that url
test pass then on prod check that the logout works

hotfix-update the logout url to remove the subdomain "prod" out of the url.

---

solution/backend/regulations/logout.py

Resolves #1117 - bugfix 
On prod when the logout happens it gets a 400 error.
To test it go to eregulations.cms.gov
sign in with EUA
Click logout
redirects to a 400 error. 
- updates logout.py to redirect to /admin.
1. sign in with EUA
2. click logout
3. should redirect to /admin/login with out any errors.

bugfix - logout redirect url to go to admin.

---

solution/text-extractor/test_text_extractor.py
solution/text-extractor/test_utils.py
solution/text-extractor/text_extractor.py
solution/text-extractor/utils.py

Resolves #2465
Extraction was failing for some files because unicode control characters were not being stripped from the output text. This is a valid string in Python, but when uploaded to eRegs it would cause a 500 error because some of these control characters can't be stored in the database (for example `\0`).
- Strips control characters from output text. (Done after text extraction itself is complete, but before uploading.)
- Wrote unit tests for this functionality and also config retrieval.
- Moved some function from `text_extractor.py` to `utils.py` to avoid import errors during unit testing.
1. Ensure unit tests pass.
2. Go to the JIRA ticket and download the 2 RTF files that failed to …

EREGCSC-2465-B Fix rtf extraction failure and add tests

---

solution/backend/cmcs_regulations/settings/base.py
solution/backend/cmcs_regulations/templates/admin/login.html

Resolves # EREGCSC-2322
When a user sings in to eua after authentication they should be redirected to where they were going. 
login.html to pass the hidden value for next so that mozilla_django_oidc knows where to redirect the user back to after authentication. 
1. visit /policy-repository
2. sign in using eua
3. notice you are redirected to /policy-repository
4. logout
1. visit /admin
2. sign in using eua
3. notice you are redirected to /admin

EREGCSC-2322-Fix login to redirect correctly

---

solution/ui/regulations/eregs-vite/src/components/policy-repository/PolicyResults.test.js
solution/ui/regulations/eregs-vite/src/components/policy-repository/PolicyResults.vue
solution/ui/regulations/package-lock.json

Resolves [EREGCSC-2480](https://jiraent.cms.gov/browse/EREGCSC-2480)
When deciding what to display in the text snippet section of a Results Item on the Policy Repository, the logic should be reordered to the following:
`item.content_headline || item.summary_headline || item.summary_string`
In other words: if there is a match on the extracted content of a document, it should be displayed as the snippet.  Handwritten summary text should never be displayed instead of `content_headline` text.
- Reorders snippet display logic
- Updates unit tests
1. Visit [experimental deployment](https://6ns3sdhttb.execute-api.us-east-1.amazonaws.com/dev1148)
2. Make sure an internal document has been uploaded, it has a …

EREGCSC-2480 -- Snippet display logic III

---

solution/text-extractor/serverless.yml

Resolves #n/a
This PR should permanently fix the "out of IPs" error we receive when having more than a couple deploys of the text extractor.
- Removes the text extractor from the private VPCs.
- Removes REST API logging since we aren't using that anyway.
1. Verify this PR deploys.
2. Go through the normal steps to extract a random supported file on the experimental deploy (admin -> uploaded files -> upload a file -> "Get content" -> refresh until "index populated" is populated). This check makes sure that removing the text extractor from the VPC doesn't impede its functionality (like S3 access).

[Hotfix] Remove text extractor from VPC

---

solution/backend/regulations/logout.py

Resolves #hotfix for logout not redirecting correctly
on production when logging out it is redirecting to localhost:8000 
1. login to https://5trxu4mf3i.execute-api.us-east-1.amazonaws.com/dev1141/policy-repository, then log out. Ensure that the page is redirected correctly. 
2. visit https://5trxu4mf3i.execute-api.us-east-1.amazonaws.com/dev1141/login/ make sure that is correct.

HOTFIX - fix the logout redirect link

---

solution/backend/regulations/templates/regulations/partials/sidebar_right.html
solution/ui/e2e/cypress/e2e/part.spec.cy.js
solution/ui/regulations/eregs-component-lib/src/components/SupplementalContent.vue

Resolves [EREGCSC-2506](https://jiraent.cms.gov/browse/EREGCSC-2506)
When looking at a regulation reading page (subpart page), there should no longer be a button in the sidebar for "search these resources".
- Removes Search Resources button from `SupplementalContent` Vue component
- Removes associated props and methods that are no longer necessary
- Updates cypress test to assert that button no longer exists
1. Visit the reader view on the experimental deployment
- Ex: [42 CFR 433 Subpart A](https://8gn42hd15j.execute-api.us-east-1.amazonaws.com/dev1156/42/433/Subpart-A/2024-01-01/)
3. The right sidebar should no longer contain a "Search These Resources" button
4. Compare to same subpart/section on …

EREGCSC-2506 -- Remove "search these resources" button in reader view sidebar

---

.github/workflows/deploy-experimental.yml
solution/parser/ecfr-parser/Dockerfile
solution/parser/fr-parser/Dockerfile
solution/parser/serverless-ecfr.yml
solution/parser/serverless-fr.yml

Resolves #2221
Makes parsers use Docker instead of the deprecated Go runtime.
- Parsers now are built using Docker instead of relying on the deprecated Go runtime.
1. Verify deployment succeeded (including Go parsers steps)
2. Verify cypress tests passed
3. Check the experimental deploy and make sure regulation content exists (titles, parts, etc.)

EREGCSC-2221 Work around deprecation of Go runtime on Lambda

---

solution/static-assets/serverless.yml

Resolves #[EREGCSC-2484](https://jiraent.cms.gov/browse/EREGCSC-2484)
Netsparker security scan reported the following:
Invicti Enterprise detected that weak ciphers are enabled during secure communication (SSL).You should allow only strong ciphers on your web server to protect secure communication with your visitors.
Remedy:
Configure your web server to disallow using weak ciphers.
Updates the serverless for static-assets so that when it creates the cloudfront distribution it also assignes the correct ssl cert. The SSL Cert ARN Value is stored in parameter store. 
1. Sign into cloud tamer. 
2. Go to cloudfront for this pull request. …

EREGCSC-2484 - Weak Ciphers Enabled

---

solution/ui/e2e/cypress/e2e/policy-repository.spec.cy.js
solution/ui/e2e/cypress/fixtures/policy-docs.json
solution/ui/regulations/eregs-vite/src/components/policy-repository/PolicyResults.vue
solution/ui/regulations/test/unit-test/__snapshots__/SupplementalContent.test.js.snap

Resolves [EREGCSC-2461](https://jiraent.cms.gov/browse/EREGCSC-2461)
Display new internal document categories and subcategories instead of internal Document Type when displaying internal documents on the Policy Repository.  This will match how public resources are displayed.
- Updates `PolicyResults.vue` logic to display `category.name` or `category.parent.name` instead of `category.document_type.name`.
1. Visit the [Policy Repository on the experimental deployment](https://uihabfjjnl.execute-api.us-east-1.amazonaws.com/dev1161/policy-repository)
2. View internal docs and note the category labels above each internal result item
3. Click through to a related citation and make sure the internal …

EREGCSC-2461 -- Use new category/subcategory model on repository

---

solution/backend/cmcs_regulations/settings/base.py
solution/backend/regulations/middleware.py

Resolves #EREGCSC-02310
HTTP Strict Transport Security (HSTS)            
Update the middleware to include ProcessResponse method. 
Update settings file to add it as a middleware
1. from your local terminal call this command
`curl -I https://7s1cyobtej.execute-api.us-east-1.amazonaws.com/dev1165`
2. look for this in the output "strict-transport-security: max-age=63072000; includeSubDomains; preload"

EREGCSC02310*enable-htt-strict-transport-security

---

solution/backend/content_search/tests/test_search.py
solution/backend/content_search/views.py
solution/backend/regulations/templates/regulations/policy_repository.html
solution/backend/regulations/views/policy_repository.py
solution/ui/e2e/cypress/e2e/policy-repository.spec.cy.js
solution/ui/regulations/css/scss/_application_settings.scss
solution/ui/regulations/css/scss/partials/_sidebar_right.scss
solution/ui/regulations/eregs-vite/src/App.vue
solution/ui/regulations/eregs-vite/src/components/policy-repository/DocumentTypeSelector.vue
solution/ui/regulations/eregs-vite/src/components/policy-repository/PolicySidebar.vue
solution/ui/regulations/eregs-vite/src/components/policy-repository/SubjectTOC.vue
solution/ui/regulations/eregs-vite/src/main.js
solution/ui/regulations/eregs-vite/src/views/PolicyRepository.vue

Resolves [EREGCSC-2499](https://jiraent.cms.gov/browse/EREGCSC-2499)
Allow unauthenticated users visit the Policy Repository and view Public documents.
See [Figma comp](https://www.figma.com/file/RonM8dMInKz3ZliDACzr96/Logged-Out?type=design&node-id=1-55&mode=design&t=Wu320m7eM1GZhNrJ-0) for design.
- Disables Public/Internal document checkboxes and makes "Public" the only checked box.
- Adds login Call to Action in the left sidebar with a log in link if user is not logged in.
- Only public item counts are shown in the Subject Table of Contents.
- Internal items are not returned or displayed from the API until user logs in.
1. Visit [experimental …

EREGCSC-2499 -- Enable subject lookup for non-logged in users

---

.github/workflows/ruff-action.yml
solution/Makefile
solution/backend/createsu.py
solution/backend/file_manager/models.py
solution/backend/pyproject.toml
solution/backend/regcore/serializers/parser.py
solution/backend/regcore/views/parser.py
solution/lambda-proxy/pyproject.toml
solution/text-extractor/pyproject.toml

Resolves #EREGCSC-2534-fix-ruff 
Ruff depregated running the rules with out the --preview. Also it is now required to have [lint] infront of certain rules. 
Updated makefile and github actions to run ruff check with --preview. 
Updated the configuratiaons to use lint as it had asked.
Updated the pre-existing violations with a #no qa  but moving forward these have to be fixed.
- expected change 9 files.
some ruff violations fixed in this pull request as well as updating the ruff configurations. 
1. check that ruff ran ok. 
2. download branch and run `make ruff` and `make ruff-fix` make sure these are running correctly.

EREGCSC-2534-fix-ruff

---

solution/backend/serverless.yml

Resolves #
[EREGCSC-2471](https://jiraent.cms.gov/browse/EREGCSC-2471)
[EREGCSC-2470](https://jiraent.cms.gov/browse/EREGCSC-2470)
[EREGCSC-2472](https://jiraent.cms.gov/browse/EREGCSC-2472)
[EREGCSC-2530](https://jiraent.cms.gov/browse/EREGCSC-2530)
Found that the pgaudit parameters were not setup appropriately accordingly to your security policy.
The following were changed
pgaudit.log_level: "LOG"
pgaudit.log_parameter: 1
pgaudit.log_statement_once: 0
pgaudit.log_catalog: 1
1. When merged to main we can check dev rds and ensure that the values are set correctly.

EREGCSC-2471 update pgaudit parameters

---

solution/ui/e2e/cypress/e2e/subjects.spec.cy.js
solution/ui/regulations/eregs-vite/src/components/subjects/PolicySidebar.vue

Resolves issue on `prod`
If the user is at the Subjects page and has not yet logged in, the Sign In link does not contain the proper `next` parameter unless a subject is selected and/or a text query has been entered.  This `next` parameter ensures a redirect back to the Subjects page after a successful login
- Updates logic to ensure the `next` parameter is included in the Sign In URL at all times and contains query parameters if they exist
1. Visit [Subjects page on the experimental deployment](https://tflob23l1j.execute-api.us-east-1.amazonaws.com/dev1171/subjects/)
2. Click "sign in" without selecting a subject or performing a text query
3. Ensure that the URL of the Custom login page contains a …

[HOTFIX] Ensure login link on Subjects page includes `next` path for redirect after login

---

solution/backend/cmcs_regulations/settings/euasettings.py

Resolves #EREGCSC-2522
cleaned up eau_settings.yml it had localhost:8000 as default which is a bug.
1. Make sure tests passing.
2. Visit [this site](https://5trxu4mf3i.execute-api.us-east-1.amazonaws.com/dev1141)
3. Sign in and then sign out, make sure you are logged out correctly and redirected to the right page.

EREGCSC-2522-Make-prod-logout-behavior-match-other-env

---

solution/text-extractor/README.md
solution/text-extractor/extractors/binary.py
solution/text-extractor/extractors/email.py
solution/text-extractor/extractors/excel.py
solution/text-extractor/extractors/extractor.py
solution/text-extractor/extractors/image.py
solution/text-extractor/extractors/markup.py
solution/text-extractor/extractors/old_excel.py
solution/text-extractor/extractors/outlook.py
solution/text-extractor/extractors/pdf.py
solution/text-extractor/extractors/powerpoint.py
solution/text-extractor/extractors/rtf.py
solution/text-extractor/extractors/tests/__init__.py
solution/text-extractor/extractors/tests/test_extractor.py
solution/text-extractor/extractors/tests/test_pdf.py
solution/text-extractor/extractors/text.py
solution/text-extractor/extractors/textract.py
solution/text-extractor/extractors/word.py
solution/text-extractor/extractors/zip.py
solution/text-extractor/text_extractor.py

Resolves #2542
We want to be able to limit the maximum size that the text extractor will extract, and offer an override functionality.
- The `Extractor` class now has an attribute, `max_size`, which is disabled (`-1`) by default. If set to a positive integer, the extractor will refuse to extract any file larger than `max_size` in megabytes.
- This is configurable per-extractor because some extractors are slower than others.
- Callers of the text extractor lambda may pass in `ignore_max_size: true` in the config dict to override this behavior.
- Additionally, all extractor's `extract` methods are renamed to `_extract` to support the template method of function overriding. (`extract()` checks the size first, and then calls the child class's …

EREGCSC-2542 Don't extract extra large PDFs

---

solution/text-extractor/backends/web.py

Resolves #n/a
Adds a user agent for the text extractor: `CMCSeRegsTextExtractorBot/1.0`.
- Adds a user agent for the text extractor: `CMCSeRegsTextExtractorBot/1.0`.
1. Go to the admin panel of the experimental deploy.
2. Go to a supplemental content item with a scrapable URL and click "Get content".
3. Click back and refresh the page until "Index populated" is populated.
4. Go to CloudWatch and view the log group for the text extractor associated with this PR (1187).
5. Go to the most recent log stream and search for "Sending GET request to..." and validate the header contains the "User-Agent" string "CMCSeRegsTextExtractorBot/1.0".

[Hotfix] Add user agent for the text extractor

---

solution/ui/regulations/eregs-vite/src/views/Search.vue

We recently retired Search.gov search on the Combined Search page and replaced it with the `content-search` endpoint used on the Subjects page.
A defect was introduced: the `apiUrl` was no longer being properly passed to the internal results, and these links became broken.
- Provides `apiUrl` to `PolicyResults` component so that internal documents can be successfully downloaded
1. Visit [experimental deployment](https://03u4vhsho0.execute-api.us-east-1.amazonaws.com/dev1197) and log in
2. Try downloading internal documents on both the Combined Search page and the Subjects page
3. Internal document downloads should work on both pages

[Hotfix] Provide `apiUrl` to PolicyResults component in the combined search page

---

solution/backend/serverless_functions/prod_functions.yml

Resolves #n/a
Content search is failing due to a timeout. This is a bandaid fix to hopefully avoid that.
- Prod's lambda timeout is increased to 20 seconds.
1. Verify that `/v3/content-search?q=test` no longer times out. You should refresh it several times to make sure.

[Hotfix] Increase prod lambda timeout to 20 seconds

---

solution/backend/serverless-redirect.yml

Resolves # serverless not creating redirect api
This is to fix the issue of serverless not creating the redirect api on val, prod. Because it's referencing a vpc that is not there on val and prod. 
Due to this being a simple lambda function that is just redirecting a url, we do not need vpc. So I removed it and hopefully it will still build the api. 
Update the redirect-serverless.yml file.
Make sure api is created with the lambda function

HOTFIX - remove vpc

---

solution/backend/common/filters.py
solution/backend/common/tests/test_filters.py
solution/backend/file_manager/admin.py
solution/backend/resources/admin.py

Resolves #2549
This PR allows for filtering on the admin panel by whether the content index has content for a particular item.
- Removed filter by title, part, subpart, etc. on supplemental content and FR docs.
- Added filter by "Index Populated" to files and resource models.
- Moved filters to `common/filters.py`.
1. Go to the admin panel.
2. Upload 2 new files under "Uploaded Files".
3. Click "Get content" on ONLY ONE of the files, click back, and refresh until the "Index Populated" field is populated. Note: if it never populates, try a different file.
4. Go back to the change list (click on "Uploaded Files").
5. Observe the new filter on the right sidebar: "By index populated".
6. Click "Yes" …

EREGCSC-2549 Enable populated filter on admin panel

---

solution/backend/serverless-redirect.yml

Resolves #
On production the api-gateway for the redirect function has the path /redirect. To make it similar to our api gateway that hosts our django website, I am change it to use / and /proxy
serverless.yml file updated
You can see it in the serverless.yml file but wont see the changes till its merged to dev.

hotfix - change the handler path

---

.github/workflows/deploy-experimental.yml
solution/backend/redirect_lambda.py

Resolves # 
We want to redirect to eregulations but also the redirection should include the path. 
for example if we visit 
regulations-pilot.cms.gov/43/430 it should redirect to eregulations.cms.gov/42/430 not eregulations.cms.gov
expected change 1
- Update the lambda function to retain the path. 
1. Visit https://8t3teirzae.execute-api.us-east-1.amazonaws.com/dev1206/42/430
2. Notice it redirects to http://eregulations.cms.gov/dev1206/42/430
3. This does not impact our api gateway django code as it has its own api. So if you visit 
https://y0hrkjjdek.execute-api.us-east-1.amazonaws.com/dev1206/42/430/
it stays the same.

update code to redirect dynamically

---

.github/workflows/deploy-experimental.yml
.github/workflows/deploy.yml
.github/workflows/pythonLint.yml
.github/workflows/remove-experimental.yml
.github/workflows/remove.yml
solution/Dockerfile.template
solution/backend/serverless-experimental.yml
solution/backend/serverless-redirect.yml
solution/backend/serverless.yml
solution/serverless-test-files/serverless-backend.yml
solution/static-assets/serverless.yml

Resolves #2561
We are currently on Django 3.2 which supports up to Python 3.10. In order to unblock migrating to the latest versions of Django we can upgrade to Python 3.10 which unblocks up to Django 5.0.
Once we have upgraded Django, we can revisit upgrading again to an even newer version of Python.
- Update Python to 3.10 locally and on deployment.
- In one case, downgrade from 3.11 to 3.10 for consistency.
1. Green check marks on this deployment (unit tests good, no cypress errors, no seed data errors, no migration errors, etc.)
2. Visit the experimental deploy and click around to make sure the site is working as expected.
3. Create a new instance locally (rebuild, either with `docker system …

EREGCSC-2561 Update Python to unblock Django upgrade

---

solution/backend/serverless-experimental.yml
solution/backend/serverless.yml

The `subjects` endpoint is consistently failing every few tries.  The logs indicate that it is running out of memory, which is currently set to the default allotment of 1024MB (1GB).
As more memory is allotted for each lambda, they are also given increased CPU power at roughly one vCPU per GB of memory:
https://aws.amazon.com/blogs/aws/new-for-aws-lambda-functions-with-up-to-10-gb-of-memory-and-6-vcpus/
https://stackoverflow.com/questions/68852520/increasing-the-memory-of-a-lambda-function
This will increase the cost, but the requests will also likely be faster, so the consensus in the discussions above is that the total cost per million invocations would be roughly the same so long as we don't allot more than 4GB of RAM.
- adds `memorySize` …

[Hotfix] Increase memory allotment for lambda functions

---

solution/backend/regulations/templates/500.html
solution/backend/regulations/templates/error_base.html
solution/backend/regulations/templates/regulations/about.html
solution/backend/regulations/templates/regulations/base.html
solution/backend/regulations/templates/regulations/homepage.html
solution/backend/regulations/templates/regulations/login.html
solution/backend/regulations/templates/regulations/search.html
solution/backend/regulations/templates/regulations/statute.html
solution/backend/regulations/templates/regulations/subjects.html
solution/backend/regulations/views/subjects.py
solution/ui/e2e/cypress/e2e/title-tags.spec.cy.js
solution/ui/regulations/eregs-vite/src/components/subjects/SubjectChip.vue
solution/ui/regulations/eregs-vite/src/components/subjects/SubjectSelector.vue
solution/ui/regulations/eregs-vite/src/components/subjects/SubjectTOC.vue
solution/ui/regulations/eregs-vite/src/main.js
solution/ui/regulations/eregs-vite/src/router/index.js
solution/ui/regulations/eregs-vite/src/views/Subjects.vue

Resolves [EREGCSC-2313](https://jiraent.cms.gov/browse/EREGCSC-2313)
Tidy up page title tags to help make analytics more meaningful.
- Updates Django templates where appropriate to match expected title text
- Uses template `block`s for title parts to stay DRY
- gets `subject_name` from Django `Subject` model if page is loaded with a subject query parameter and adds it to title
- Updates Subjects page title using a Vue Router navigation guard as the user interacts with the Subjects page single page app
- Adds Cypress test suite to assert various app states display the expected title text
1. Visit [experimental deployment](https://e782e3ue2e.execute-api.us-east-1.amazonaws.com/dev1207)
2. See [JIRA …

EREGCSC-2313 -- Update `<title>` tags

---

.github/workflows/pythonLint.yml

Resolves failing `Python-Lint` action
Python was just upgraded to version 3.10.  See [PR here](https://github.com/Enterprise-CMCS/cmcs-eregulations/pull/1209).
Since that upgrade, the Python-Lint action has been failing with the following message:
```
Version 3.1 was not found in the local cache
Error: The version '3.1' with architecture 'x64' was not found for Ubuntu 20.04.
```
In the `pythonLint.yml` workflow config file, the `python-version` property is set as follows:
```
with:
python-version: 3.10
```
It's likely that this version is being interpreted as a float and the trailing zero is being ignored, which is causing the version number to be interpreted as `3.1` when the Github Action is being set up.
- Surrounds `3.10` with quotes in …

[Hotfix] Python `version-number` needs to be string in pythonLint workflow .yml

---

solution/backend/cmcs_regulations/context_processors.py
solution/backend/cmcs_regulations/settings/base.py
solution/backend/regulations/templates/regulations/base.html
solution/ui/e2e/cypress/e2e/analytics.spec.cy.js

Resolves [EREGCSC-2563](https://jiraent.cms.gov/browse/EREGCSC-2563)
In order to create meaningful reports about user behavior, we don't want to count logged-in people with admin roles (job codes) as part of our Google Analytics.
- Creates `IS_ADMIN_USER` variable that can be used in all templates
- Adds logic to base template that will only render Google Tag Manager/Analytics `script` tags in the page `head` if `IS_ADMIN_USER` is `False`
1. Visit [experimental deployment](https://sascih35oc.execute-api.us-east-1.amazonaws.com/dev1210)
2. Ensure you are NOT logged in
3. Open DevTools and inspect the `head` element of any page.  
- You should see the following comment: ``
- Underneath the comment, you …

EREGCSC-2563 -- Omit admins from analytics

---

solution/ui/e2e/cypress/e2e/subjects.spec.cy.js

Resolves failing test on `dev` environment due to data being synced with `prod`
We're syncing up database data for `dev`, `val`, and `prod` environments.  So far, we've taken a dump of `prod` data and used it to populated `dev`.  Now, `dev` behaves like `prod` -- which, in our case, means that certain search queries will now fail.
This is causing a test to fail on `dev`, which is blocking deployment to `prod`.
For future discussion: this failing test is one of the few tests that does not intercept a request and use fixtures for the results. Instead, it waits for the actual response from the server.
- Replaces the search query `test`, which fails, which search query `streamlined modular certification`, which passes.
**Steps to manually verify …

[Hotfix] In test, add user search query that is guaranteed to succeed

---

.github/workflows/deploy-experimental.yml
.github/workflows/deploy.yml
.github/workflows/pythonLint.yml
.github/workflows/remove-experimental.yml
.github/workflows/remove.yml
solution/Dockerfile.template
solution/backend/pyproject.toml
solution/backend/serverless-experimental.yml
solution/backend/serverless-redirect.yml
solution/backend/serverless.yml
solution/lambda-proxy/pyproject.toml
solution/serverless-test-files/serverless-backend.yml
solution/static-assets/serverless.yml
solution/text-extractor/pyproject.toml

Resolves #2581
To increase future maintainability and support newer Python features/enhancements, we want eRegs to be running on the latest stable version of Python, which as of now is 3.12.
- Update Python to 3.12.
- Thoroughly tested the site, ran unit tests, checked Cypress, etc to ensure nothing has broken.
- Checked for deprecations using `python -wa`.
1. Green check marks for this experimental deployment.
2. Rebuild your regulations container locally and verify it builds and runs successfully using Python 3.12 (verify it's running 3.12 with `docker compose exec regulations python --version`.)
3. Run unit tests locally (`make test.pytest`).

EREGCSC-2581 Upgrade Python to 3.12

---

solution/backend/regulations/templates/regulations/search.html
solution/backend/regulations/templates/regulations/subjects.html
solution/ui/regulations/css/scss/partials/_search.scss
solution/ui/regulations/css/scss/partials/_subjects.scss
solution/ui/regulations/eregs-component-lib/package-lock.json
solution/ui/regulations/eregs-vite/src/App.vue
solution/ui/regulations/eregs-vite/src/components/SearchErrorMsg.test.js
solution/ui/regulations/eregs-vite/src/components/SearchErrorMsg.vue
solution/ui/regulations/eregs-vite/src/components/__snapshots__/SearchErrorMsg.test.js.snap
solution/ui/regulations/eregs-vite/src/views/Search.vue
solution/ui/regulations/eregs-vite/src/views/Subjects.vue
solution/ui/regulations/utilities/api.js

Resolves [EREGCSC-2592](https://jiraent.cms.gov/browse/EREGCSC-2592)
It's confusing if the search times out and gives 0 results. Let's tell the reader what's actually happening, so that they know to look elsewhere for the information they need.
See Figma comps here:
[Search Page](https://www.figma.com/file/iZFh6UhvGVEHw1D4IAt3Bw/eRegs-Combined-Search?node-id=4652%3A7064&mode=dev)
[Subjects Page](https://www.figma.com/file/KiWw729Nct6tY9gzmvEkVO/Browse-by-Subject?node-id=818%3A16156&mode=dev)
- Adds new `throwGenericError` method that returns an error after two seconds
- This method is being used for validation purposes -- initially, all Search and Subjects page requests will fail on purpose to validate the different error message states
- …

EREGCSC-2592 -- Return a better error message when search times out

---

README.md
solution/backend/cmcs_regulations/settings/deploy.py
solution/backend/cmcs_regulations/settings/local.py
solution/backend/resources/admin.py
solution/backend/scripts/backup_db.sh
solution/backend/scripts/restore_db.sh
solution/docker-compose.yml
solution/static-assets/requirements.txt

Resolves #[EREGCSC-2576](https://jiraent.cms.gov/browse/EREGCSC-2576)
This script allows a developer to easily dump the data from prod and then restore whatever database they want with it. 
It consists of 2 scripts : 
backup_db.sh
restore_db.sh
**backup_db.sh**
User is prompted with database user, database host, database port, database name, and password. 
After the user answers all the prompts a pg_dump command is executed and it creates a backup file that is the databasename_date. For example if my database is eregs, it would create a file named eregs_20240338232930.sql. 
**restore_db.sh**
User is prompted with database user, database host, database port, database name and password and database file. 
After the user answers all the prompts pgsql command is executed. 
1) …

EREGCSC-2576 - Sync dev, val and local with prod

---

solution/ui/e2e/cypress/e2e/search.spec.cy.js
solution/ui/regulations/css/scss/partials/_search.scss
solution/ui/regulations/eregs-vite/src/views/Search.vue

On the Combined Search page, a single column failure (e.g. Reg Results are returned successfully but Resources fail), the "Expand Your Search" box is not shown.
- Adds logic to show "Expand Your Search" box in each column is that column, and only that column, returns an error
- Adds Cypress tests to validate error states
3. Normal searches work as expected (with results, with zero results, etc)

[Hotfix] show Expand Your Search box on single column failure

---

solution/static-assets/serverless.yml

Resolves #CMCS eRegulations[EREGCSC-2571](https://jiraent.cms.gov/browse/EREGCSC-2571)
Security Hub control checks whether an Amazon S3 general purpose bucket has a policy that requires requests to use SSL. The control fails if the bucket policy doesn't require requests to use SSL.
- Update serverless.yml file to change the s3 bucket for cloudfront logs policy to require SSL 
Visit AWS S3 buckets. 
Look at [eregs-dev1235-cloudfront-logs](https://us-east-1.console.aws.amazon.com/s3/buckets/eregs-dev1235-cloudfront-logs?region=us-east-1&bucketType=general)
Click on Permissions tab
Look at the [cloudfront bucket …

EREGCSC-2571-s3-bucket-ssl

---

.github/workflows/deploy-experimental.yml
.github/workflows/deploy.yml
.github/workflows/git-secrets.yaml
.github/workflows/load-regulations.yml
.github/workflows/load-supp-content.yml
.github/workflows/parser-checks.yml
.github/workflows/pythonLint.yml
.github/workflows/remove-experimental.yml
.github/workflows/remove.yml
.github/workflows/ruff-action.yml
.github/workflows/schedule-jira-sync.yml
.github/workflows/snyk-test.yml

In our Github Action config files, we use `jobs.<job_id>.runs-on` to define the type of machine on which to run the job.
More info: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
We're currently specifying Ubuntu 20, which will be supported through 2025.  However, Ubuntu 22 is the latest LTS and should be supported through 2027.  If we can stay current and upgrade to Ubuntu 22 without any issues, we should.
- changes `runs-on` image label from `ubuntu-20.04` or `ubuntu-latest` to `ubuntu-22.04` in all `.github/workflows/*.yml` files

Upgrade Github Action runner images to Ubuntu 22

---

solution/backend/empty_bucket.py
solution/backend/serverless-experimental.yml
solution/static-assets/serverless.yml

Resolves # EREGCSC-2595
Description-
This pull request updates the empty_buckets.py to delete the cloudfront logs bucket. The cloudfront logs bucket also has versioning switched on which was not necessary and causing issues deleting the bucket.
After the bucket is emptied, github actions will run serverless remove the bucket. Which will in turn delete the bucket.
solution/backend/empty_bucket.py
The script is modified to not only empty the file storage bucket but also to empty cloudfront logs bucket. 
solution/static-assets/serverless-experimental.yml
update permissions for emptying the logs bucket that it did not have permissions to. 
Steps to manually verify this change...
Go to aws s3 buckets and take note of …

EREGCSC-25595-auto-remove-s3-log-buckets

---

solution/ui/regulations/css/scss/partials/_site_homepage.scss
solution/ui/regulations/package.json

Resolves [EREGCSC-1765](https://jiraent.cms.gov/browse/EREGCSC-1765)
A pull request to fix any issues found after Vue 3 upgrade has been merged into `main`.
- Adjusts position of homepage Menu button in mobile view (i.e. narrow widths) when ToC is closed
2. Manual validation/comparison of [experimental deployment](https://coimg2r73m.execute-api.us-east-1.amazonaws.com/dev1263) to `prod`

EREGCSC-1765-A -- Tweaks and fixes based on prod validation

---

solution/ui/regulations/eregs-component-lib/package-lock.json
solution/ui/regulations/eregs-component-lib/package.json
solution/ui/regulations/eregs-vite/package-lock.json
solution/ui/regulations/eregs-vite/package.json
solution/ui/regulations/package-lock.json
solution/ui/regulations/package.json
solution/ui/regulations/utilities/utils.js

Resolves several [Dependabot issues](https://github.com/Enterprise-CMCS/cmcs-eregulations/security/dependabot)
Vite's version was not defined specific enough to ensure the latest version is always installed.  This PR pegs the vite versions to the latest patch (5.2.9) in all places that vite is used.
- Updates vite version from `^5.0` to `^5.2.9` in all three places where it is used
- Fixes syntax error that is now enforced as a breaking error instead of an ignorable warning
1. Green check markes
2. Experimental Deployment works as expected
3. Site builds and can be watched locally as expected
4. Once merged to `main`, Vite-specific Dependabot alerts go away

Vite Upgrade

---

.github/workflows/deploy-experimental.yml
.github/workflows/deploy.yml
solution/backend/cmcs_regulations/settings/local.py
solution/backend/cmcs_regulations/settings/test_settings.py
solution/backend/common/fields.py
solution/backend/common/tests/test_fields.py
solution/backend/content_search/models.py
solution/backend/content_search/serializers.py
solution/backend/content_search/tests/test_search.py

Resolves #2602
By default, `SearchHeadline` will return the beginning of the text of the field of interest if the search term is not contained within that field. Although this can be useful behavior, in our case we want to display nothing instead. This PR solves that by adding a boolean option to the `HeadlineField` field we created, `blank_when_no_highlight`. When set to `True` the field will check for the existence of the `<span>` in the headline results, and if it doesn't exist, it will set the resulting field to `None`.
- Added option `blank_when_no_highlight` to `HeadlineField`.
- `blank_when_no_highlight` is set to `True` for the `content_headline` field.
- Added a test for both conditions (when `blank_when_no_highlight` is true and …

EREGCSC-2602 If SearchHeadline can't generate a highlighted headline, show nothing

---

solution/backend/cmcs_regulations/settings/base.py
solution/backend/file_manager/serializers/groupings.py
solution/backend/file_manager/tests/test_views.py
solution/backend/file_manager/urls.py
solution/backend/file_manager/views.py
solution/backend/resources/views/mixins.py

Resolves #EREGCSC-2518 - List related subjects
Given a regulation part, subpart, or section, we want to be able to display the top X subjects associated with resources in that part, subpart, or section. We imagine we could do this by taking the associated resources for the part, subpart, or section (FR docs and supplemental content) and counting the subjects attached to those documents.
We want to look into whether we could calculate this reasonably fast for display in sidebars. It could be cached, since it probably wouldn't change very often.
endpoints to include top_x and min_count parameters
top_x will determine the top of the given number of subjects. For example if you pass top_x=5, it will display the top 5. Default value is 5.
min_count will return subjects that …

EREGCSC-2518 - list related subjects

---

solution/ui/e2e/cypress/e2e/title-tags.spec.cy.js
solution/ui/regulations/eregs-vite/src/components/subjects/SubjectSelector.vue
solution/ui/regulations/eregs-vite/src/views/Subjects.vue

Resolves [EREGCSC-2667](https://jiraent.cms.gov/browse/EREGCSC-2667)
Document title is sometimes incorrect on load when visiting the subject page with a subject included in the URL.
The issue: 
- Fixes bug where only the first digit of a subject ID was used on page load to set the Document Title (ex: 25 Dental would be interpreted as 2 ABP)
- Adds Cypress end to end test to validate this change
- Fixes issue with Subject Selector highlighting/bolding where multiple subjects could be bolded
2. Visit the [Subjects page on the experimental deployment](https://tuncmlts43.execute-api.us-east-1.amazonaws.com/dev1287/subjects/)
- select and deselect a few subjects from both the Table of …

EREGCSC-2667 -- Reloading a subject page causes it to have the wrong <title> value

---

solution/backend/regulations/templates/regulations/partials/header.html
solution/backend/regulations/templates/regulations/search.html
solution/backend/regulations/templates/regulations/statute.html
solution/backend/regulations/templates/regulations/subjects.html
solution/ui/e2e/cypress/e2e/sign-in-out.spec.cy.js
solution/ui/regulations/css/scss/partials/_header.scss
solution/ui/regulations/eregs-vite/src/App.vue
solution/ui/regulations/eregs-vite/src/components/header/HeaderUserWidget.vue
solution/ui/regulations/eregs-vite/src/views/Search.vue
solution/ui/regulations/eregs-vite/src/views/Statutes.vue
solution/ui/regulations/eregs-vite/src/views/Subjects.vue

Resolves [EREGCSC-2672](https://jiraent.cms.gov/browse/EREGCSC-2672)
When signed in, the top right menu should have a "Manage Content" link that goes to the admin panel homepage.
[Figma design](https://www.figma.com/file/kGg6wtaPK2yxtAayP6JZUb/Authentication-status?node-id=534-23425&mode=dev)
[Figma prototype](https://www.figma.com/proto/kGg6wtaPK2yxtAayP6JZUb/Authentication-status?page-id=1%3A57&type=design&node-id=102-18030&t=iIASmNGP7zeQo5yx-0&scaling=min-zoom&starting-point-node-id=259%3A24273)
- Adds "Manage Content" link to account dropdown menu and styles per Figma design
2. Visit [experimental deployment](https://h32gdnvzu2.execute-api.us-east-1.amazonaws.com/dev1290) and …

EREGCSC 2672 -- Add "Manage Content" link to Account dropdown menu

---

solution/ui/e2e/cypress/e2e/subjects.spec.cy.js
solution/ui/e2e/cypress/fixtures/policy-docs-50-p1.json
solution/ui/e2e/cypress/fixtures/policy-docs-50-p2.json
solution/ui/regulations/eregs-vite/src/components/subjects/DocumentTypeSelector.vue
solution/ui/regulations/eregs-vite/src/components/subjects/PolicyResults.vue
solution/ui/regulations/eregs-vite/src/components/subjects/PolicySelections.vue
solution/ui/regulations/eregs-vite/src/components/subjects/SubjectSelector.vue
solution/ui/regulations/eregs-vite/src/views/Subjects.vue
solution/ui/regulations/utilities/utils.js
solution/ui/regulations/utilities/utils.test.js

Resolves [EREGCSC-2403](https://jiraent.cms.gov/browse/EREGCSC-2403)
Add Pagination Controls to Subjects page with a default `page_size` of `50`.
- Hooks `PaginationController` up into Subjects page
- Adds `page` query parameter to Subjects page to control which page of results to display
- Adds Cypress tests and fixtures of paginated data
2. Visit [experimental deployment](https://bvswm5lqi3.execute-api.us-east-1.amazonaws.com/dev1295/) and poke around the subjects page
- Pagination controls should exist at the bottom of search results
- Searches with > 50 results should have multiple pages of results
- Results pages should be accessible via clicking "Previous/Next" buttons or …

EREGCSC-2403 -- Subjects page pagination

---

solution/ui/e2e/cypress/e2e/part.spec.cy.js

Resolves [EREGCSC-2460](https://jiraent.cms.gov/browse/EREGCSC-2460)
The original PR for EREGCSC-2460 included Cypress end to end tests to validate that individual items were displayed alongside item subcategories under a single category.  
Tests were written to validate public AND internal documents.
However, internal document tests are flaky and are preventing deployment to `prod`.  Since the functionality of this PR has been manually validated for both public and internal documents, and because the code changes are already being validated in Cypress using public documents, the flaky internal document tests are being removed as unnecessary.
- Remove internal document test logic …

EREGCSC-2460 -- Remove flaky Cypress test

---

solution/backend/content_search/tests/test_search.py
solution/backend/content_search/views.py

Resolves #2674
Due to the recent change (https://github.com/Enterprise-CMCS/cmcs-eregulations/pull/1231) that made it so that search headlines were only generated for the current page instead of the entire queryset, we were losing the `sort_by("-rank")` from the search query.
Upon feeding the rank-sorted, paginated results back into a second `ContentIndex` `pk__in` filter, the default sort by `pk` was occurring instead. Since the rank is lost by the time the second query occurs, there is no way to simply include a second `sort_by`.
Instead we have to use the ranked-sorted list of pk's to sort the output of the second query immediately before serialization.
- Store `ranked_results` list (renamed from `results`) at the function level for use …

EREGCSC-2674 Fix for bug "Resource search results seem to be sorted by ID"

---

solution/ui/e2e/cypress/e2e/api.spec.cy.js

Resolves issue where our deployments depend on Search.gov having 100% uptime
In order to return a successful response, one of our unused and soon-to-be-deleted endpoints, `v3/resources/search`, needs a valid response from Search.gov.
Unfortunately, right now Search.gov is having some issues and requests are timing out. Our `v3/resources/search` endpoint is not equipped to gracefully handle a Search.gov timeout, and as a result this endpoint is returning a 500 error that is causing a Cypress test to fail.  This failing test is preventing us from deploying anything.
- Removes test for `v3/resources/search` endpoint
2. Successful deployments all the way to `prod`

[Hotfix] Remove `resources/search` endpoint from Cypress API test suite

---

solution/ui/regulations/composables/fetch.js
solution/ui/regulations/utilities/api.js

Turn off frontend caching for resources
Resolves #2709
Modified the code to disable frontend caching by introducing a constant, DEFAULT_CACHE_RESPONSE, set to false. This approach centralizes the caching configuration, allowing us to easily adjust the default caching behavior in one place in the future without needing to update every instance in the code.
Modifies the api.js file to set the default cache response to false.
**Steps to view and verify change**
update a resource item in the admin panel, 
Notice the changes right away on the front end of the site, even if previously loaded that page recently

EREGCSC-2709 - Turn off frontend caching for resources

---

solution/ui/regulations/eregs-vite/src/components/dropdowns/Categories.vue
solution/ui/regulations/eregs-vite/src/components/subjects/PolicySelections.vue
solution/ui/regulations/eregs-vite/src/components/subjects/SubjectChip.vue
solution/ui/regulations/eregs-vite/src/components/subjects/SubjectSelector.vue
solution/ui/regulations/eregs-vite/src/components/subjects/SubjectTOC.vue
solution/ui/regulations/eregs-vite/src/main.js
solution/ui/regulations/eregs-vite/src/views/Subjects.vue

Resolves [EREGCSC-2711](https://jiraent.cms.gov/browse/EREGCSC-2711)
We've had some issues where some query parameters from the Vue Router `route` are arrays sometimes and strings other times.  Specifically, this has been happening to `subjects`.
The reason for this issue turns out to be: we are explicitly setting `subjects` as an array when we programmatically set it via `router-link` or `$router.push`.  Whoops!
This was likely left over from the initial implementation of the Subjects page, where we briefly allows users to select more than one subject to view results from all subjects.  This was quickly changed to the current implementation, which only allows one subject to be selected at a time.
As such, we've removed the instances where we are programmatically setting …

EREGCSC-2711 -- Update Vue Router navigation guard to ensure query params are not an array (except `type`)

---

solution/static-assets/requirements.txt

Resolves #EREGCSC-2678-remove-zappa-django-utils
Snyk [reports](https://app.snyk.io/org/eregs-x7s/project/95496066-f240-4403-b97d-ae11557a04ce) that our [requirements file](https://github.com/Enterprise-CMCS/cmcs-eregulations/blob/main/solution/static-assets/requirements.txt) includes a transitive dependency on Django version 1, apparently through [zappa-django-utils](https://github.com/Miserlou/zappa-django-utils/blob/master/requirements.txt).
Therefore, we should remove this dependency. If we still require its functionality, we should replace it with an alternative solution.
So we should remove it. If we still need something it did, let's replace it with something else.
updated requirements.txt to remove this plugin …

EREGCSC-2678-remove-zappa-django-utils

---

solution/backend/package.json
solution/serverless-test-files/package.json
solution/static-assets/custom-cf-invalidate-plugin/LICENSE
solution/static-assets/custom-cf-invalidate-plugin/index.js
solution/static-assets/package.json

Resolves #EREGCSC-2478
We integrated the serverless-cloudfront-invalidate plugin into our project in the previous update (#1326). This pull request adds the MIT license from the original repository and removes references to the old package.
Adds license text
Removes references to old package
Ensure tests pass
Ensure license is there

EREGCSC-2478 Add license + remove old dependencies for serverless-cloudfront-invalidate

---

solution/ui/regulations/eregs-vite/src/views/Search.vue
solution/ui/regulations/utilities/utils.js
solution/ui/regulations/utilities/utils.test.js

Resolves [EREGCSC-2713](https://jiraent.cms.gov/browse/EREGCSC-2713)
If you search for something with a # in the query (from the combined search page or from the subjects page), you get a few unexpected effects:
- In the results, the “related regulation citations” show as “none”
- In the results, the category and subcategory labels are missing ("Subregulatory Guidance" etc)
- Anything after # in the query seems to be ignored
- If you're on the subjects page and run this kind of query, the filters don't work as expected. For example, if I uncheck "public", public items are still displayed. 
- Encodes `q` query parameter before it is included `content-search` API call
- We're creating the `content-search` query string two different wants in …

EREGCSC-2713 -- Encode hash marks and other characters so `content-search` endpoint returns successfully

---

.github/workflows/ruff-action.yml

Resolves deployment blocker
The Ruff Github action began failing last week.  This PR fixes the issue.
- Adds `check` argument to Ruff Github action config to fix failing action
- This `check` argument requirement was enforced in [Ruff 0.5.0](https://github.com/astral-sh/ruff/releases/tag/0.5.0), which was released Thursday 27 June. Our Ruff Github actions have been failing since then.

[Hotfix] Ruff Github action

---

README.md
solution/Dockerfile.template

Resolves error when pulling down, installing, and running project for the first time on a new machine.  Also adds link to clone project with SSH in addition to HTTPS.
Running through the project's installation process on a new machine, it was discovered that our Dockerfile template does not contain reference to a needed library.  As such, an error was being thrown and the Docker containers were unable to be created.
The error:
```
158.1       src/c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
158.1          15 | #include <ffi.h>
158.1             |          ^~~~~~~
158.1       compilation terminated.
158.1       error: command '/usr/bin/gcc' failed with exit code 1
158.1       [end of output]
158.1
158.1   note: This error originates from a …
```

[Onboarding] Updates to config files and documentation based on recent setup experience

---

solution/ui/e2e/cypress/e2e/part.spec.cy.js
solution/ui/e2e/cypress/e2e/subjects.spec.cy.js
solution/ui/e2e/cypress/fixtures/42.431.internal.json
solution/ui/e2e/cypress/fixtures/policy-docs-search.json
solution/ui/regulations/css/scss/partials/_supplemental_content.scss
solution/ui/regulations/eregs-component-lib/src/components/SupplementalContentObject.vue
solution/ui/regulations/eregs-vite/src/components/subjects/PolicyResults.vue

Resolves [EREGCSC-2223](https://jiraent.cms.gov/browse/EREGCSC-2223)
Internal links are a new type of document: they go to Sharepoint URLs that are external to eRegs.  As such, we would like to indicate that these links will open a new tab and go to an external site.  We already do that with other external links by adding an External Link icon at the end of the styled link.
- Updates logic needed to add `external` class to internal links
- Updates CSS style rules where needed to properly position external link icon at the end of Internal Links
- Adds tests
2. Visit experimental deployment
3. Create an internal link and upload a file
4. Visit the Search page, the Subjects page, and …

EREGCSC-2223 -- Style internal links on frontend

---

solution/backend/resources/admin/internal_resources.py

Resolves #2772
On prod, internal files are failing to delete. This is because the old code used `get_key()` and the new code uses `key` as a computed property. Note that this code, along with all upload/download code, will be refactored in a near-future ticket, so even though this isn't the most elegant or resilient code it will change soon. This PR only fixes the immediate issue.
- Fix this naming error.
- Remove redundant exception.
1. Go to the admin panel of the experimental deploy.
2. Go to internal files, and upload a _new_ file (don't use an existing file for this test, since they don't actually exist in the S3 bucket for this deploy).
3. Save the new file, then go back to it and hit …

EREGCSC-2772 Fix for "Can't delete internal files"

---

.gitignore
solution/backend/content_search/models.py
solution/ui/regulations/eregs-vite/src/components/subjects/PolicyResults.vue

Resolves [EREGCSC-2771](https://jiraent.cms.gov/browse/EREGCSC-2771)
When displaying internal links and internal files on the Search and Subjects pages, we need to map the item field of the API response item to the proper display field on the front end of the application.
- Adds post-save hook that is specific to `internal_link`s to properly map DB fields to API response item fields
- Updates display logic on the front end to ensure fields are being displayed in their proper places
2. Log in to the [experimental deployment](https://nzfrr0fz11.execute-api.us-east-1.amazonaws.com/dev1378)
3. Visit the Subjects and Search pages and search for various internal documents.  Searching …

EREGCSC-2771 -- Updating front end field/display mappings

---

solution/backend/resources/admin/actions.py
solution/backend/resources/admin/public_resources.py
solution/backend/resources/admin/resources.py
solution/backend/resources/migrations/0005_reset_extract_url.py
solution/backend/resources/tests/test_admin_actions.py
solution/backend/resources/tests/test_fr_link_admin.py
solution/backend/resources/utils/general_purpose.py
solution/backend/resources/views/resources.py

Resolves #2796
We have a special field, `extract_url`, on AbstractResource that enables us to feed the raw text versions of FR links to our text extractor. We get this URL from the FR API. But we currently have somewhat inconsistent/unexpected behavior around this field, so let's fix that.
- For all non-FR resources, the `extract_url` field is blanked out for now.
- Admin panel save_model will try to retrieve `extract_url` from the FR API if `url` or `document_number` has changed.
- If it fails, a warning message is shown to the user and the event is logged, but saving continues unhindered.
- If `extract_url` is updated and `auto_extract` is true, the text extractor will be invoked even if `url` hasn't changed.
- Implemented `auto_extract` …

EREGCSC-2796 Fix extract_url behavior

---

solution/backend/resources/tests/test_resources_endpoints.py
solution/backend/resources/views/resources.py

Resolves #n/a
Forgot to include order_by("date") for the related_resources prefetch during the v4 refactor. This results in grouped documents appearing out of order.
- Added order_by statement to the related_resources prefetch.
- Add test for related_resources being in the correct order.
1. Go to /42/431/Subpart-A/2024-07-09/
2. Check the right sidebar under Proposed and Final Rules for an FR link with grouped documents.
3. Verify the grouped documents are in the correct order, with latest first.

[hotfix] Add missing order by date for related_resources prefetch

---

solution/ui/regulations/package-lock.json
solution/ui/regulations/package.json

[EREGCSC-2779](https://jiraent.cms.gov/browse/EREGCSC-2779) (Vitest fixes) introduced a regression where the CMS Design System npm package was updated to a newer minor version.  Our targeted version is `2.5.0`, but the [pull request for 2779](https://github.com/Enterprise-CMCS/cmcs-eregulations/pull/1404) rebuilt the `package-lock.json` file to install `2.13.0`.
We don't want `2.13.0` because it includes unwanted style changes.  Specifically, element `focus` styles are pink instead of blue.
We've previously attempted to upgrade to `2.13.0` based on a Snyk suggestion, but that upgrade [was reverted](https://github.com/Enterprise-CMCS/cmcs-eregulations/pull/1044) back to `2.5.0` for this same reason.
Except we didn't actually lock the version to `2.5.0`.  Note this line from …

[Hotfix] Ensure CMS Design System npm package version is 2.5.0

---

solution/Makefile
solution/backend/common/auth.py
solution/backend/content_search/serializers.py
solution/backend/content_search/views.py
solution/backend/regcore/views/parser.py
solution/backend/resources/serializers/categories.py
solution/backend/resources/serializers/groups.py
solution/backend/resources/serializers/resources.py
solution/backend/resources/views/categories.py
solution/backend/resources/views/citations.py
solution/backend/resources/views/groups.py
solution/backend/resources/views/resources.py
solution/backend/resources/views/subjects.py

Resolves # EREGCSC-2756
Update swagger so that it does not return an error anymore. The issue was that ResourceGroupSerializer needed to be updated to serialize the entire resource not just using the primary keys. 
visit : [swagger](https://fdc0l1ak6c.execute-api.us-east-1.amazonaws.com/dev1407/api/swagger)
notice error is no longer there. 
2. on your local go to this pull request branch.
3. on your local, run django app `make local`
4. run `run make local.spectacular`
5. check to see that there are no errors.

EREGCSC-2756 - Update swagger

---

solution/backend/content_search/tests/test_search.py
solution/backend/content_search/views.py

Resolves #2823
The `content-search` endpoint is not filtering out unapproved resources, resulting in unapproved resources showing in search results if indexed.
- Unapproved resources are filtered out from content-search results.
- Added a test to verify that this is the case.
- Removed an irrelevant content-search test that was testing the resources app.
1. Go to the search page and search for any term. Make note of the first result's ID.
2. Go to the admin panel and find the instance corresponding to the first result on the search page.
3. Mark that resource as unapproved and save it.
4. Refresh the search page. That result should now be missing, as expected.

EREGCSC-2823 Fix for unapproved resources showing in search

---

.github/CODEOWNERS

Resolves offboarding checklist item
Parissa has been offboarded from the team and this PR removes her Github account from the project's `CODEOWNERS` file.
- Removes Parissa's Github username from `CODEOWNERS`
- and then there were two
1. `CODEOWNERS` file is reduced to two current devs

[Offboarding] Remove Parissa from `CODEOWNERS` file

---

solution/backend/cmcs_regulations/utils/pagination.py
solution/backend/content_search/serializers.py
solution/backend/content_search/tests/test_search.py
solution/backend/content_search/urls.py
solution/backend/content_search/views.py
solution/backend/resources/tests/test_resources_endpoints.py
solution/backend/resources/views/resources.py

Resolves #2850
Counts were not properly displayed when one of the show_* flags was passed to the content-search endpoint, or from the subjects page if internal or public were unselected. This is because all filtering was done first before counting. To solve this problem (and reduce endpoint overhead), we decided to move counting to a separate endpoint dedicated to only this task (`/v3/content-search/counts`).
- New pagination function removed (`get_additional_attributes()` is retained).
- New endpoint `/v3/content-search/counts` exists and returns counts of public, internal, and reg text for given filters.
- Endpoint is linked to from the pagination header of the `/v3/content-search` and `/v3/resources` endpoints via `count_url`.
- For …

EREGCSC-2850 Enable querying for item counts when document type is not selected

---

solution/backend/cmcs_regulations/settings/base.py
solution/backend/resources/views/categories.py
solution/backend/resources/views/resources.py

Resolves #2774
Django Rest Framework, by default, allows authentication by Session Auth and Basic Auth. This conflicts with our experimental branch protection, unintentionally authorizing every API request as if a user were logged in. 
- Set DRF's `DEFAULT_AUTHENTICATION_CLASSES` to only use SessionAuthentication.
- Ensure places where basic (or other auth schemes) are needed have it set manually.
1. In the experimental deploy, ensure you are logged out of the admin panel.
2. Visit search/subjects page and make sure no internal resources show up.
3. For extra validation, go to `/v3/content-search/counts` and make sure `internal_resource_count` is set to zero.
4. Log in to the admin panel and …

EREGCSC-2774 Fix for branch access shouldn't enable internal access

---

.github/workflows/schedule-jira-sync.yml

Resolves #2805
This PR updates the SecurityHub JIRA sync action to the latest version.
- SecurityHub JIRA sync action is updated to the latest version.
1. Deploy to prod.
2. Cron is set to `cron: "25 1 * * *"`, so check GitHub's Actions tab the next day after 6:25am EST to verify that the action succeeds.

EREGCSC-2805 Update SecurityHub Jira sync

---

.github/workflows/schedule-jira-sync.yml

Resolves #2805
Update docs say: "You don't need to specify the Jira host if it's 'jiraent.cms.gov'. So you can remove this". Including this key causes an error message in the action, so better to remove it.
- Remove jira-host setting from jira sync github action
1. Deploy this to prod.
2. Wait until after 6:25am the following day.
3. Check the securityhub action and the action is successful with no errors.

EREGCSC-2805-B Remove jira-host setting

---

solution/ui/regulations/eregs-vite/src/components/subjects/PolicyResults.vue

Resolves issue on `prod`
When logged in as an admin, users have the ability to click an "Edit" button for any search result on the Subjects page.  This button will take the user directly to the admin panel and allow them to edit the document.
The edit button is not currently working on `prod`; the user is shown an error screen with a 404 error.
This error is being caused by a dangling and unnecessary apostrophe that is being erroneously added to the end of the Edit button's `href` attribute.
- Removes dangling apostrophe from Edit button link
2. Log in to experimental deployment with an admin account and visit Subjects page
3. Click Edit button and make sure it takes you to the …

[Hotfix] Edit button not working on policy results

---

.github/workflows/remove-experimental.yml
.github/workflows/remove.yml

Resolves #n/a
`solution/parser` no longer contains package.json because `serverless-go-plugin` was removed. We removed `npm install` for the deploy actions but forgot to remove it for the remove actions, causing remove to fail.
- Remove `npm install` under the parser section of the remove GitHub actions.
1. Deploy this to prod and verify that the remove action passes.
2. Try to fix previous failures: merge main into the failing PR branches and re-run the remove action.

[hotfix] Remove parser 'npm install' for remove actions

---

solution/backend/content_search/serializers.py
solution/backend/content_search/tests/test_search.py
solution/backend/content_search/views.py

Resolves #2323
To enable subject and category dropdowns to display accurate counts, we need the count API (`/v3/content-search/counts`) to display a list of relevant subjects and categories (filtered by search results) and the number of relevant resources associated with them.
- Count API displays `subjects` list: an array of dicts containing the subject PK and the count of resources within the search result set associated with that subject.
- Count API displays `categories` list: an array of dicts containing the category PK, the category's parent's PK (if applicable, or null), and the count of resources within the search result set associated with that category.
1. Head to …

EREGCSC-2323 Add counts for subjects and categories to counts API

---

solution/backend/regulations/templates/regulations/about.html

Resolves [EREGCSC-2865](https://jiraent.cms.gov/browse/EREGCSC-2865)
We updated our homepage demo video link at #1445, but I just noticed we have a link on the "about" page as well. Since this fix would take probably longer to describe in a Jira story than implement, I went ahead and did it.
This change only impacts the "about" page. It:
- Removes the redundant video link
- Fixes other outdated info on the about page
1. Visit the "about" page on the experimental branch
2. It should no longer say "View a 6-minute video demonstration."
3. Nothing should be broken

EREGCSC-2865 -- Remove old video link from "about" page

---

solution/ui/e2e/cypress/support/common-commands/policyDocs.js
solution/ui/regulations/css/scss/partials/_results_item.scss
solution/ui/regulations/css/scss/partials/_supplemental_content.scss
solution/ui/regulations/eregs-component-lib/src/components/CollapseButton.vue
solution/ui/regulations/eregs-component-lib/src/components/Collapsible.vue
solution/ui/regulations/eregs-component-lib/src/components/RelatedRuleList.vue
solution/ui/regulations/eregs-component-lib/src/components/SupplementalContent.vue
solution/ui/regulations/eregs-component-lib/src/components/SupplementalContentCategory.vue
solution/ui/regulations/eregs-component-lib/src/components/SupplementalContentList.vue
solution/ui/regulations/eregs-component-lib/src/components/shared-components/results-item-parts/RelatedSections.vue
solution/ui/regulations/eregs-vite/src/components/subjects/PolicyResults.test.js
solution/ui/regulations/eregs-vite/src/components/subjects/PolicyResults.vue

Resolves [EREGCSC-2812](https://jiraent.cms.gov/browse/EREGCSC-2812)
The "Related Regulations" information for each search result item can get very long.  We want to hide this information until the user clicks a "Show Related Citations" button, which will reveal the list of related citations.  Clicking the button again will collapse and hide the list of related citations.
- Uses existing `CollapseButton.vue` and `Collapsible.vue` components to hide and show `RelatedRegulations.vue` component on the Search page and the Subjects page
- Uses ESLint autofix on `Collapsible`/`CollapseButton` components to fix various linting issues (these components are old!)
- Adds CSS style rules to match [Figma …

EREGCSC-2812 -- Condense related citations on items

---

solution/ui/e2e/cypress/e2e/search.spec.cy.js
solution/ui/e2e/cypress/e2e/subjects.spec.cy.js
solution/ui/e2e/cypress/support/common-commands/policyDocs.js
solution/ui/regulations/css/scss/partials/_search.scss
solution/ui/regulations/css/scss/partials/_subjects.scss
solution/ui/regulations/eregs-vite/src/components/SearchErrorMsg.vue
solution/ui/regulations/eregs-vite/src/components/SearchInput.vue
solution/ui/regulations/eregs-vite/src/components/subjects/DocumentTypeSelector.vue
solution/ui/regulations/eregs-vite/src/components/subjects/PolicyResults.vue
solution/ui/regulations/eregs-vite/src/components/subjects/PolicySidebar.vue
solution/ui/regulations/eregs-vite/src/main.js
solution/ui/regulations/eregs-vite/src/views/Search.vue
solution/ui/regulations/eregs-vite/src/views/Subjects.vue

Resolves [EREGCSC-2685](https://jiraent.cms.gov/browse/EREGCSC-2685)
Removes ability to search by query string on the Subjects page.  The Search Input still exists on the page, but it is moved out of the left sidebar and to the top center of the Subjects page.  When a user searches by query string, they are redirected away from the Subjects page to the Search page with only their selected subject preserved.
- Moves Search Input element from left sidebar of Subjects page to top center of page with the other filters (Choose Category, Document Type selector)
- Removes `q` param from URL if user attempts to visit Subjects page with a link that includes `q` param
- Removes/refactors all logic on the Subjects page associated with search …

EREGCSC-2685 -- Move subject page search box to filter region

---

solution/ui/e2e/cypress/e2e/homepage.spec.cy.js
solution/ui/e2e/cypress/fixtures/recent-guidance.json

Resolves failing Homepage end to end test suite test on `prod`
The Cypress homepage test suite has a failing test on the `prod` environment.  The test is supposed to be using an `intercept` to replace the server response with a fixture file.
The issue: the intercept is incorrectly specifying the path to be matched. As a result, the test is being run against an actual response from the server, which is returning data that is not expected by the test.
- Updates the intercept path to add a glob (`**`) to the end of the intercept path so that the correct fixture file is returned by the API call instead of real data from the server
- Updates the fixture file to include a custom Subject name that does not and will never exist in prod to verify that …

[Hotfix] Ensure intercept is calling fixture for homepage test suite

---

.github/workflows/deploy.yml

Resolves #2860
Previous PR (#1473) fails to deploy to prod because "deploy.yml" was still looking for the experimental hello world stack.
- Removes the experimental hello world stack deploy action from "deploy.yml"
1. Approve and merge
2. Deploy through to prod
3. Verify green for each deploy

EREGCSC-2860-B [Hotfix] Remove "hello world" stack deploy from deploy.yml

---

.github/dependabot.yml

This is related to the ticket at [EREGCSC-2654](https://jiraent.cms.gov/browse/EREGCSC-2654) about refactoring our GitHub Actions, but does not resolve it. This is a followup to #1454 (Enable Dependabot to check for GitHub Actions updates).
We want to keep our GitHub Actions updated, but we want to prioritize major and minor version updates instead of all updates, to reduce unnecessary dev work to review and merge patch updates.
- Ignore patch-level updates for GitHub Actions - based on https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore-patch-updates
You could check the linked documentation to make sure this …

Ignore patch-level Dependabot updates for actions

---

solution/text-extractor/extractors/pdf.py
solution/text-extractor/extractors/tests/__init__.py
solution/text-extractor/extractors/tests/test_pdf.py
solution/text-extractor/serverless.yml

Resolves # 2900
We saw an increase in Textract charges this month and tracked it back using Lambda monitor charts to a period between 11/6-11/8 where there was a consistent number of extractor errors. Checking CloudWatch we saw the extractor continually attempting to process an object and timing out after 900 seconds (15 mins).
We were able to reasonably guess that it was the result of the extractor attempting to extract a 500 page PDF that was only 6 MB. Given that the max file size was 20 MB, it didn't exceed that threshold, but since each page is sent to Textract sequentially, we could guess that it would easily exceed 900 seconds. (Max processing time per page is 900/500 = 1.8 sec/page, which we are unlikely to beat.)
Additionally, since the Lambda orchestrator is …

EREGCSC-2900 Prevent text extractor from infinitely retrying, add max pages for PDF extraction

---

.github/workflows/deploy-experimental.yml
.github/workflows/remove-experimental.yml
cdk-eregs/bin/cdk-eregs.ts
cdk-eregs/config/stage-config.ts
cdk-eregs/lib/stacks/maintainance-stack.ts

Resolves #EREGCSC-2861
This pull request changes:
- Implements automated deployment of Maintenance API to ephemeral environments for PR testing
- Adds GitHub Actions workflow for PR-specific stack deployment
- Matches exact configuration from existing serverless deployment:
- Lambda: Python 3.12, 1024MB, 30s timeout
- API Gateway: Edge endpoint with binary media types
- IAM: Correct paths and permission boundaries
- Logging: Proper CloudWatch configuration
1. Open a new PR
- Verify GitHub Action triggers automatically
- Check CDK deployment logs show correct configurations
2. Test deployed endpoint
- Find API Gateway URL aws console
- Verify maintenance API responds correctly
- Check AWS Console for PR-specific resources (format: cms-eregs-eph-{pr-number}-maintenance-api)
3. Close PR to …

Add CDK configuration for maintainance stacks to experimental deployment

---

.github/workflows/deploy-experimental.yml
.github/workflows/remove-experimental.yml
cdk-eregs/bin/cdk-eregs.ts
cdk-eregs/cdk.context.json
cdk-eregs/lib/stacks/redirect-stack.ts
cdk-eregs/lib/stacks/text-extract-stack.ts

Resolves EREGCSC-2856
* Migrates text-extractor service from Serverless Framework to CDK TypeScript
* Implements environment-aware deployments (dev, val, prod, ephemeral)
* Maintains feature parity with existing CloudFormation template:
- Docker-based Lambda function
- SQS queue with DLQ
- IAM roles and policies
- VPC integration
- CloudWatch logging
Verify resources:
- Lambda function exists with Docker image
- SQS queues (main + DLQ) created
- IAM roles and policies set correctly
- VPC integration successful
Check GitHub Actions deployment:
Navigate to Actions tab
View successful deployment workflow
Verify resources created in AWS Console

EREGCSC-2856 - Add text extractor CDK stack

---

.github/workflows/parser-checks.yml

Resolves Static Check action failing since 1.3.1 upgrade
Dependabot created [pull request ](https://github.com/Enterprise-CMCS/cmcs-eregulations/pull/1477) that bumped [dominikh/staticcheck-action](https://github.com/dominikh/staticcheck-action) from 1.3.0 to 1.3.1.  Since the version was only incremented by a single patch value, we decided to approve the PR and merge it to `main`, assuming that there would be no breaking changes and that the Parse Checks action would continue to work and succeed as expected.
However, this update broke the Parser Checks action and the checks have consistently failed since this PR was merged.  As such, we are going to revert the action version back to 1.3.0 and to get the Parser Check actions working again.
- …

[Hotfix] Revert dominikh/staticcheck-action from 1.3.1 to 1.3.0 to address failures

---

solution/backend/resources/tests/test_subjects_endpoint.py
solution/backend/resources/views/subjects.py

Resolves #2901
**Note:**
Failing CDK deployments are not relevant to this bugfix, please ignore them as long as other tests and deployment steps are passing.
Bug discovered in `/v3/resources/subjects` where the `public_resources` and `internal_resources` fields included unapproved resources in their counts.
- Added an approved filter to the existing counts 
- Added a test case for this endpoint
1. Unit tests pass
2. Go to the experimental [subjects endpoint](https://pxovfcrbvl.execute-api.us-east-1.amazonaws.com/dev1493/v3/resources/subjects) and note in the first result, "Aged, Blind, Disabled", the `public_resources` count is 42.
3. Go to [this …

EREGCSC-2901 Fix for "Subject counts include unapproved items"

---

.github/workflows/remove-experimental.yml

Remove hello world stack that is not needed anymore

Remove Hello World stack

---

.github/workflows/remove-experimental.yml

Removed the --exclusively flag from CDK destroy commands as it was causing execution issues during PR-specific stack cleanup.

EREGCSC-2902 - Fix CDK remove command

---

solution/backend/resources/admin/resources.py

Resolves #2363
Pen-testing revealed a vulnerability in the admin panel where it is possible to execute arbitrary code by inserting the code into the title of a resource and saving it. This triggers a text extraction user message to be displayed with the title of the resource in the message.
- Use Django's `escape()` function around user-entered strings that are displayed in an HTML formatted user message.
1. In the experimental deploy, go to the admin panel and sign in.
2. Go to a public link and arbitrarily add junk to the end of the URL to trigger a text extraction event (e.g. if URL is http://google.com, add "/test" to the end).
3. Replace the `title` field with the following: `CCIC"><img …

EREGCSC-2363-B Fix escape vulnerability in text extraction user message on admin panel

---

solution/backend/serverless.yml

Resolves #2583
To stay ATO compliant we need to be on the latest patch release for our major PostgreSQL version, which is 15.8.
- Upgrades PostgreSQL engine version in Serverless config.
1. Backup the dev DB. (A snapshot will suffice.)
2. Perform manual engine upgrade on AWS console for dev.
3. Deploy this PR.
4. Verify Serverless does not create a new database or overwrite the existing dev DB.
5. Backup the val DB. (A snapshot will suffice.)
6. Manually upgrade the DB engine on the AWS console for val.
7. Approve deployment to val.
8. Verify Serverless does not create a new database or overwrite the existing val DB.
9. Backup the prod DB. (A snapshot will suffice.)
10. Set maintenance mode …

EREGCSC-2583 Update PostgreSQL engine to 15.8

---

solution/backend/cmcs_regulations/settings/deploy.py
solution/backend/serverless.yml

Resolves #2904
To be ATO compliant, our Postgres timeouts must be no greater than 10 seconds. Due to inefficiencies in prior API versions leading to DB timeouts, we increased this timeout to 20 seconds but never reset it back down.
- Set `statement_timeout` to 10000 (10 seconds) in Serverless config.
- Set `connect_timeout` to 10 seconds in deploy config.
To verify the cluster parameter group has the correct parameter value:
1. Log into AWS -> RDS.
2. Go to prod DB cluster, then click the Configuration tab.
3. Click the link under "DB cluster parameter group".
4. Under the "Filter parameters" text box, enter "statement_timeout".
5. You should see the `statement_timeout` setting with a value of …

EREGCSC-2904 Set statement_timeout back to 10 seconds

---

.github/dependabot.yml
.github/workflows/deploy-experimental.yml
solution/ui/regulations/eregs-vite/src/components/subjects/SelectedSubjectChip.test.js

Resolves [EREGCSC-2905](https://jiraent.cms.gov/browse/EREGCSC-2905)
Make Dependabot a bit more aggressive when it comes to upgrading our `npm` dependencies.  
To do this, we will allow dependabot to create pull requests every weekday, but will limit the number of open pull requests to one.  This way, we can move as fast as we want with these PRs -- we can have a new one every day if needed, or we can allow an open PR to sit for several days before being reviewed without worrying about new PRs being created.
- Adds section to `dependabot.yml` for `npm` ecosystem
- Sets pull request creation interval to `daily` (weekdays)
- Limits open PRs for `npm` ecosystem to `1` (one)
- Increase minimum required version in `package.json` to the recently …

EREGCSC-2905 -- Automate prompts for major updates for key components

---

solution/backend/regulations/templates/regulations/login.html
solution/ui/e2e/cypress/e2e/custom-login-page.cy.js
solution/ui/regulations/css/scss/partials/_login.scss

Resolves [EREGCSC-2739](https://jiraent.cms.gov/browse/EREGCSC-2739)
If a person visits our sign in page and doesn't have access to internal eRegs materials, we want to offer convenient instructions for how to get access. To do this, the sign page should give a brief bit of explanation with a link to the instructions.
- Refactors HTML markup in Custom Sign In page to match tag hierarchy found in `/about` and `/get-account-access` pages
- Updates copy text below CMS IDM button
- Removes email addresses
- Adds link to new "Get Account Access" page on eRegs
- Expands Cypress end to end test suite for custom login page to verify changes listed above
2. Visit [experimental …

EREGCSC-2739 -- Link sign-in page to account access instructions

---

.github/dependabot.yml

Resolves [EREGCSC-2905](https://jiraent.cms.gov/browse/EREGCSC-2905)
Further refinement of Dependabot configuration work.  The expectation was that each defined `package-ecosystem` would have a maximum of one PR open; with two `package-ecosystems` defined, the expected number of PRs open at any given time would be a maximum of two.
Instead, we're only seeing one pull request.  We'd like to tweak this setting to get two PRs open concurrently.
- updates `open-pull-request-limit` to `2` for each package ecosystem
- Adds `groups` option to group certain dependencies together into a single pull request
2. Merge to `main` and see if a second dependabot PR joins the currently open one

EREGCSC-2905-A -- Increment open Pull Request limit to 2

---

solution/ui/e2e/cypress/e2e/get-access-page.cy.js
solution/ui/regulations/eregs-vite/src/views/Statutes.vue
solution/ui/regulations/eregs-vite/src/views/Subjects.vue

Fixes defect found after deploying [EREGCCS-2734](https://jiraent.cms.gov/browse/EREGCSC-2734) to `prod`
The "Get Account Access" link in the top left corner of the header should only be visible if the user is not logged in.  Once the user logs in, the "Get Account Access" link should not exist.
Currently, the Subjects and Statutes pages are still showing the "Get Account Access" link in the header when logged in.
- Adds `v-if` directive to `AccessLink` component when used on Subjects and Statutes pages.
- The `v-if` directive conditionally renders the component if the directive's expression is truthy
- The `isAuthenticated` prop is being used in the directive's expression: `!isAuthenticated` must be truthy for the component to render.
- This …

[Hotfix] EREGCSC-2734 -- Hide Get Account Access link when logged in on Subjects/Statutes page

---

.github/dependabot.yml
solution/ui/e2e/cypress/e2e/part.spec.cy.js
solution/ui/e2e/cypress/fixtures/42.433.history.json

Resolves [EREGCSC-2905](https://jiraent.cms.gov/browse/EREGCSC-2905)
Further refinement of Dependabot configuration work.
Since we began updating the `dependabot.yml` file, we've been seeing some [failures of the Dependabot Github Action](https://github.com/Enterprise-CMCS/cmcs-eregulations/actions/workflows/dependabot/dependabot-updates).  The [error](https://github.com/Enterprise-CMCS/cmcs-eregulations/network/updates/952232478) is:
```
Dependabot couldn't find a package.json
Dependabot requires a package.json to evaluate your JavaScript dependencies. It had expected to find one at the path: /package.json.
```
To attempt to fix this error, `dependabot.yml` is being updated to use the `directories` option to specify locations of multiple `package.json` files.
See:
- …

EREGCSC-2905-B -- Add list of directories for npm ecosystem package.json locations in Dependabot config

---

solution/backend/content_search/models.py

Resolves #2687
A while back we noticed an issue where differing page sizes would be sorted differently. Today a bug popped up where two nearly identical searches are being sorted differently. The only difference was that `show_internal` and `show_regulations` were both changed from true to false, as public items were _always_ first in this particular search.
Noticed that the items in question had identical ranks (0.9999997) and realized that we are only sorting by rank and not specifying a secondary sort parameter for items with identical rank.
This PR fixes this (for now) by changing `order_by("-rank")` to `order_by("-rank", "-id")`. In theory this is a good approximation of sort by date as larger IDs should represent newer documents. In the future, we need to find a way …

EREGCSC-2687 Fix for items with identical ranks being sorted in an undefined way

---

solution/ui/e2e/cypress/e2e/api.spec.cy.js

Resolves failing Cypress test that is blocking deployment
The GovInfo Historical PDF Versions API endpoint (/v3/title/{title}/part/{part}/history/section/{section}) is returning zero results onexperimental deployments and a 502 error on `dev`.  This began happening yesterday (Thursday 23 January 2025).
The endpoint has been tested on `val` and `prod` and is working fine on both environments.
Until the issue on `dev` is triaged and fixed, we will simply not test this endpoint to unblock our deployment pipeline.
- Comments out endpoint that is failing on `dev`

[Hotfix] Remove history API endpoint from array of endpoints to be tested by Cypress API test suite

---

.github/dependabot.yml

Resolves [EREGCSC-2905](https://jiraent.cms.gov/browse/EREGCSC-2905)
Further refinement of Dependabot configuration work.
Recent changes to our `dependabot.yml` config file have made Dependabot more aggressive.  That's good!
However, we'd like it to be a tiny but less aggressive by restricting the number of open pull requests per package ecosystem (npm, GitHub actions, etc) to one.
- Reduces `open-pull-requests-limit` option for each package ecosystem to `1`
2. Merge to `main` and verify that no more than one `npm` pull request is open at a single time

EREGCSC-2905-C -- Reduce number of open pull requests per ecosystem to one

---

solution/backend/regulations/templates/regulations/get_account_access.html

Resolves [EREGCSC-2939](https://jiraent.cms.gov/browse/EREGCSC-2939)
We want to encourage potential repository users to request the EREGS_READER_PRD job code (which has been re-created), along with EREGS_EDITOR_PRD.
- Updates copy text on Get Account Access page with new nested ordered list with new job code and description.
2. Visit experimental deployment an click Get Account Access
3. Step 5 of "Request access for CMCS staff" now has two job codes with associated descriptions: reader and editor
4. Copy test matches text in JIRA story AC

EREGCSC-2939 -- Add reader job code to "Get Account Access" page

---

.github/workflows/deploy-cdk-dev.yml

Resolves #2859
Previous deploy to dev skipped the lambda invoke step (migrate, createsu) due to an accidentally copied `if` statement in the action that can't ever be true because it's not a pull request.
- Removed the `if` statement so lambda invoke can run.
1. Approve and deploy.
2. In the "Deploy CDK to DEV" action, verify the step "Invoke setup functions after site lambdas deployed" runs and has a green check.
3. Check the CDK dev site to make sure migration completed. (No 500 error.)

EREGCSC-2859-I Remove if conditions on dev deploy lambda invoke

---

.github/workflows/remove-experimental-cdk.yml
cdk-eregs/lib/constructs/database-construct.ts
solution/backend/serverless_functions/experimental_functions.yml

Description
Adds required security groups to the RDS cluster via SSM parameters to enable VPN access to the database.
Adds AWS SSM parameter lookups for required security groups
Imports and attaches three additional security groups to RDS cluster:
CMS Cloud Shared Services
CMS Cloud VPN
CMS Cloud Security Tools
Configures security groups via SSM parameters for flexible management
Steps to manually verify this change...
Deploy the stack and verify the RDS cluster has all security groups attached
Check AWS Console > RDS > DB Security Groups to confirm presence of:
Database-specific security group
cmscloud-shared-services
cmscloud-vpn
cmscloud-security-tools
Attempt to connect to the database via VPN to verify access is working
Reorders stack destruction sequence …

EREGCSC-2859-J Add SG for VPN access to the database, rearrange remove steps

---

.github/workflows/deploy-cdk.yml
.github/workflows/deploy-experimental-cdk.yml
.github/workflows/remove-experimental-cdk.yml

Resolves #2922
CDK is validated in dev, we want to advance to val for further testing and validation before deploying to prod.
- Rename action "Deploy CDK to Dev" to "Deploy CDK"
- Change matrix in action to permit Github Actions to deploy the CDK version of the site to val
- Semi-related fix: syntax for aws lambda invoke for CDK would silently fail if AWS CLI returned an error before invocation occured
1. Approve and merge this PR
2. Check the "Deploy CDK" action for success deploying to dev
3. On success, approve deploy to val
4. Validate successful deploy in val (check AWS console, check the site, etc.)

EREGCSC-2922 Advance CDK deploy to val account

---

.github/workflows/deploy-cdk-manager.yml
.github/workflows/deploy-cdk.yml

Resolves #2922
Matrix strategy attempted to run each job for all environments before moving to the next job. We want the opposite: run all jobs for one environment before moving onto all jobs for the next environment. To utilize a multi-job strategy we must use a "reusable workflow" implementation.
- Two actions: deploy-cdk-manager.yml and deploy-cdk.yml
- The manager action uses a matrix to call the deploy-cdk action for each environment
- `max-parallel: 1` ensures only one deploy at a time
1. Approve and deploy
2. Check out both new actions and ensure _all_ of the dev deploy happens before val attempts to start

EREGCSC-2922-B Fix workflow order for CDK deploy

---

.github/workflows/deploy-cdk.yml

Resolves #2922
The previous PR (#1567) failed because I forgot to replace `inputs.environment` with `matrix.environment`.
- Replace `inputs.environment` with `matrix.environment`
1. Verify it deploys (see #1567 steps)

EREGCSC-2922-D Replace inputs.environment with matrix.environment

---

.github/workflows/deploy-cdk.yml

Resolves #2922
We have successfully deployed the parallel CDK environment to both dev and val. Now we want to advance it to val for final validation.
- Permit deploy-cdk action to deploy to dev, val, and prod (with approval interim steps)
1. Approve and merge
2. Wait for dev to deploy, approve to val
3. Wait for val to deploy, approve to prod
4. Wait for prod to deploy, then validate

EREGCSC-2922-E Advance CDK deploy to prod account

---

cdk-eregs/lib/stacks/static-assets-stack.ts

Resolves #2922
Previous PR (#1569) failed because of a check only for prod that enforced a custom SSL cert for static assets. We don't need that for now so removing to test.
- Removed custom SSL cert check from static assets stack.
1. See previous PR's steps (#1569)

EREGCSC-2922-F Temporarily remove custom SSL cert requirement for CDK in prod

---

README.md

No associated Jira ticket.
Update the readme to make more sense for first-time developers trying to get the code running locally.
- Standardize headers
- Clarify prerequisites, including providing tips for getting them set up
- Updated Node requirement from v18 to v20 (we had a story for checking this more thoroughly at [EREGCSC-2627](https://jiraent.cms.gov/browse/EREGCSC-2627)...but it seems fine).
- Organize and clarify guidance for local install, including telling people to run the watch command as part of basic setup
- Make linting info more concise
- Add heading for development tips, to separate them from basic local setup
- Remove Serverless info that is going to be outdated very soon
Read …

Reorganize readme for better usability

---

.github/workflows/remove-experimental-cdk.yml
.github/workflows/update-cdk-bootstrap.yml
cdk-eregs/bin/docker-lambdas.ts
cdk-eregs/lib/stacks/ecfr-parser-stack.ts
cdk-eregs/lib/stacks/fr-parser-stack.ts
cdk-eregs/lib/stacks/text-extract-stack.ts

Resolves #2922
CDK validation in prod uncovered a few minor issues to fix. This PR fixes them.
- Memory size for eCFR/FR parsers were incorrectly set to 128MB instead of 1024MB.
- Fixed a typo in the Text Extractor -> File Repo Bucket access policy that prevented the text extractor from reading the S3 bucket.
- Remove accidentally copied if statement from remove-experimental-cdk.yml's static assets remove step, that was causing the step to be skipped.
- Related: Update CDK Bootstrap action failing because AWS moved the `bootstrap-template.yaml` file from [here](https://raw.githubusercontent.com/aws/aws-cdk/refs/heads/main/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml) to …

EREGCSC-2922-H Miscellaneous CDK bug fixes

---

solution/ui/regulations/css/scss/_application_settings.scss
solution/ui/regulations/css/scss/partials/_site_homepage.scss
solution/ui/regulations/css/scss/partials/_supplemental_content.scss

Resolves iteration bug caused by [EREGCSC-2932](https://jiraent.cms.gov/browse/EREGCSC-2932) ([pull request](https://github.com/Enterprise-CMCS/cmcs-eregulations/pull/1573))
Fixes a regression where Related Rules in the Reader view sidebar lost the pipe that separates date and Document ID.  This regression was caused by EREGCSC-2932, which updated the pipe separator styles for the homepage items but did not properly account for side effects elsewhere in the app.
- Creates SCSS mixin to encapsulate `recent-date--bar` styles to be reused throughout the app
- Uses this mixin for Related Rules on the homepage and in the Reader View sidebar
2. Reader view sidebar rules have a pipe …

[Hotfix] Reader Sidebar rules lost their pipe separator

---

solution/backend/redirect_lambda.py

Resolves #n/a
Calling Python's `urljoin()` without a schema (i.e. `https://`) will result in the domain part being ignored entirely. In the redirect lambda, this results in a redirect to `/`, creating an infinite redirect.
- Add `https://` before the domain
1. Deploy this to prod
2. Go to the redirect lambda and verify it redirects successfully

[hotfix 2] Include schema in redirect lambda's URL

---

.github/workflows/deploy.yml

Resolves #2915
Dev deploy failed because cypress couldn't get the API URL.
- Modify get-api-url step to more closely match the deploy-experimental version of it.
1. Approve and deploy
2. Verify dev cypress test succeeds

EREGCSC-2915-B Attempt to fix get-api-url step in deploy.yml

---

solution/backend/content_search/migrations/0005_contentindex_date.py

Resolves #2910
Previous migration failed because of a statement timeout.
- Increase local statement timeout to 10 mins.
1. Approve and deploy this PR up to val.
2. Val deploy should succeed.

EREGCSC-2910-B fix: increase local statement timeout to fix migration failure

---

cdk-eregs/lib/constructs/waf-construct.ts

Resolves #2953
For a few days we have been receiving the following error while attempting to deploy the site stack:
```
Waf/WafLogResourcePolicy (WafWafLogResourcePolicy...) Resource handler returned message: "Resource limit exceeded. (Service: CloudWatchLogs, Status Code: 400, Request ID: ...) (SDK Attempt Count: 1)"
```
The issue does not occur for already deployed stacks when redeployed, and it does not occur in production. The issue was resolved incidentally after manually deleting several old CDK stacks that had failed to delete.
After looking at the stack in CloudFormation, I saw that the resource it was referring to was of type `AWS::Logs::ResourcePolicy`. The [docs for this](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-resourcepo …

EREGCSC-2953 Remove dependency on log resource policy

---

.github/workflows/test-text-extractor.yml
README.md

Resolves #2880
If Python is installed via Homebrew, running `pip3 install boto3` will fail and suggest users to use Homebrew to install boto, which is not possible. Instead the user should create a virtualenv.
- Add instructions on creating a virtualenv for boto3 for MacOS users.
- Unrelated fix: text extractor tests were failing due to outdated Ubuntu repos, added `apt-get update` to fix.
n/a

EREGCSC-2880-B Add boto3 install instructions for MacOS users to use resource removal scripts

---

cdk-eregs/package-lock.json
cdk-eregs/package.json

Resolves #n/a
Deployments have been randomly failing since updating AWS CDK minor versions in a recent PR. Error is:
```
DeployStaticAssets/CustomResource/Default (DeployStaticAssetsCustomResource900BFA47) Received response status [FAILED] from custom resource. Message returned: Command '['/opt/awscli/aws', 's3', 'sync', '--delete', '/tmp/tmpbjjqwbd4/contents', 's3://cms-eregs-eph-1640-site-assets/']' died with <Signals.SIGKILL: 9>. 
```
We are attempting to update to a newer minor version to see if that fixes it before troubleshooting any further.
- In package.json, update aws-cdk-lib to 2.192.0
1. Be sure PR deploys successfully (in other words, the update doesn't break anything).
2. Approve …

[fix] Update aws-cdk-lib to 2.192.0 to attempt to fix deploy issue

---

README.md
cdk-eregs/README.md
scripts/restore_local_db.sh
scripts/restore_remote_db.sh

Resolves #n/a
Database restore script was recently rewritten to take advantage of the AWS CLI more instead of relying on user inputs. Forgot to consider localhost use, so needed to add a new script and reflect the new script usage in the docs. Also, needed to update the CDK documentation.
- Moved `restore_db.sh` to `restore_remove_db.sh`.
- Added `restore_local_db.sh` that bypasses AWS CLI and hardcodes certain values, only asking for a file and password.
- Updated main README.md to reflect new steps for DB backup/restore.
- Updated CDK README.md for better readability.
n/a, all scripts already tested. Feel free to read the README changes and see if they make sense.

Improve backup/restore scripts and documentation

---

cdk-eregs/lib/stacks/static-assets-stack.ts

Resolves #2955
Received SecurityHub finding in prod stating that CloudFront distributions must use a custom SSL cert. This appears to be because the CDK code was creating a local var `certificateArn`, and if `props.certificateArn` is not set, the local var is set to the value of the param from Parameter Store. However, later when creating the distribution, the local var is not used, and instead `props.certificateArn` is used.
- When setting CloudFront properties, use local var `certificateArn` instead of `props.certificateArn`
Dev and val do not use the custom SSL cert, this is only needed in prod. So:
1. Make sure this PR deploys successfully.
2. Approve and deploy through to prod. 
3. Log into …

EREGCSC-2955 Fix for SecurityHub finding: CloudFront must use custom SSL

---

.github/workflows/deploy.yml

Resolves #2654
In the previous PR I forgot to set the prod deployment process to depend on the "wait-for-approval" job, instead it is still relying on the val deploy. This is not currently an issue because environment protection has not yet been disabled for the prod environment, but before we can do that we need to ensure that the wait for approval step works properly.
- Prod deploy depends on "wait-for-approval" job instead of on val deploy.
1. Approve and deploy
2. See in the prod deploy graph that the prod deploy won't attempt to start until after the "wait-for-approval" job is complete.

EREGCSC-2654-B Fix dependency on wait-for-approval step

---

.github/workflows/deploy-to-env.yml
.github/workflows/deploy.yml

Resolves #2960
One of the goals of implementing reusable workflows was to enhance at-a-glance readability of the site deployment action. For the most part, it did accomplish that, but there were some minor issues such as the fact that the action "deploy-to-dev", for example, would be often shortened to something like "de... / job-name" where "de" is short for "deploy" instead of "dev".
- deploy-to-* replaced with *-deploy. (Shortened versions in the diagram should show "d...", "v...", "p..." which will more clearly indicate which jobs are for which environment.)
- notify replaced with add-pr-comment.
- deploy-zip-lambdas replaced with deploy-alternate-sites.
- deploy-site-lambdas replaced with deploy-site.
**Steps to manually verify this …

EREGCSC-2960 Changed some deploy job labels for readability/accuracy

---

solution/backend/regulations/templates/regulations/partials/node_types/Division.html
solution/ui/e2e/cypress/e2e/subjects.spec.cy.js
solution/ui/e2e/cypress/fixtures/subjects.json
solution/ui/regulations/eregs-component-lib/src/components/SupplementalContentCategory.vue
solution/ui/regulations/eregs-component-lib/src/components/SupplementalContentList.vue
solution/ui/regulations/eregs-component-lib/src/components/TableComponent.vue
solution/ui/regulations/eregs-vite/src/components/navigation/NavBtn.vue
solution/ui/regulations/eregs-vite/src/views/Subjects.vue

Resolves [EREGCSC-2958](https://jiraent.cms.gov/browse/EREGCSC-2958)
If a selected subject has a description field, display it on the Subjects page under the subject name at the top of the page.
- Conditionally renders `span` under `<SelectedSubjectHeading />` on `/subjects` page if selected subject has a `desc` field with non-zero-length string
- Adds Cypress e2e tests and fixtures to assert that subject descriptions are rendered if they exist and not rendered if they don't exist
- Fixes four eslint warnings that need to be cleaned up
2. Visit [ephemeral deployment's Subjects page](https://nb8hiudky9.execute-api.us-east-1.amazonaws.com/eph-1659/subjects/)
3. Click around Subjects …

EREGCSC-2958 -- Display subject descriptions on subject pages

---

README.md
solution/backend/common/fields.py
solution/backend/common/tests/test_fields.py
solution/backend/requirements.txt
solution/backend/resources/migrations/0008_update_ref_field_sort.py
solution/backend/resources/serializers/citations.py
solution/backend/resources/serializers/resources.py
solution/backend/resources/views/resources.py

Resolves #2247
In order to enable related (non-CFR) citations to show on the frontend, we need to provide that in the API response wherever resources are serialized. In addition, the citations need to be sorted alphabetically.
- Add dependency on `natsort` to provide the `natsorted()` function which replaces Python's built-in `sorted()` function.
- This is needed because alphabetical sorting is incorrect when inconsistent-length numbers are in the strings. For example, `sorted(["1", "2", "3", "10"])` would become `["1", "10", "2", "3"]`. Natsort resolves this.
- Add natural sorting (and whitespace removal) to the pre-save hook for custom reference fields (+unit test).
- Add Resources app migration to re-save all resources to utilize the …

EREGCSC-2247 Enable providing resource statute citation info to frontend

---

solution/backend/resources/admin/categories.py

Resolves #n/a
A 500 error is occurring on the public and internal subcategory admin panel list views. It's because we're prefetching parent categories for the list display, but we were specifying the models to prefetch as `InternalCategory` and `PublicCategory` instead of the abstract class.
- `InternalCategory.objects.all()` and `PublicCategory.objects.all()` in prefetch calls replaced with `AbstractCategory.objects.select_subclasses()`.
1. Go to the admin panel and click on public subcategory, make sure the page loads and parent categories are displaying properly.
2. Go to internal subcategory, make sure the page loads and parent categories are displaying properly.

[bugfix] Fix bug on category admin list view: invalid prefetch

---

.github/workflows/test-django.yml
solution/backend/content_search/migrations/0007_enable_pgvector.py
solution/backend/requirements.txt
solution/docker-compose.yml

Resolves #2813
To enable the rest of our planned hybrid semantic search work, we first need to enable pgvector and pgvector-python.
- Add pgvector-python requirement.
- Add pgvector enable migration to content-search app.
- Switch local database Docker container to use version of Postgres containing pgvector extension.
Validate the site continues to work as expected. No changes to behavior are expected at this time.

EREGCSC-2813 Add and enable pgvector extension

---

solution/backend/content_search/views.py
solution/backend/regulations/templatetags/link_statutes.py
solution/backend/regulations/tests/test_link_statutes.py
solution/backend/regulations/utils/__init__.py
solution/backend/regulations/utils/link_statutes.py
solution/backend/regulations/views/reader.py
solution/backend/resources/serializers/citations.py
solution/backend/resources/serializers/resources.py
solution/backend/resources/views/resources.py

Resolves [EREGCSC-2613](https://jiraent.cms.gov/browse/EREGCSC-2613)
In "show related citations", statute sections are linked if possible.
- Moves `act` and `usc` link logic from `link_statutes` template tags file to its own file in `solution/backend/regulations/utils/link_statutes.py`
- adds `generate_url_only` boolean flag to replace_section` and `replace_usc_citation` methods that when true will return only a URL and not a fully formed anchor element
- Moves Link Conversions and Link Config logic out of `solution/backend/regulations/views/reader.py` and into `utils/link_statutes.py` as mixins
- Imports mixins to `content_search`, `resources`, and `reader` views to add `link_conversions` and `link_config` to view context
- Propagates …

EREGCSC-2613 -- Citation link

---

solution/parser/ecfr-parser/Dockerfile
solution/parser/fr-parser/Dockerfile

Resolves #2886
Amazon Linux 2 is outdated and deprecated and so we need to switch to Amazon Linux 2023 to continue to be supported. The only place we are directly using Amazon Linux images is in the eCFR/FR parsers.
- eCFR and FR parsers switched to al2023 from al2.
1. Green checks indicate successful Docker build and deploy.
2. Check the CloudWatch logs for the eCFR and FR parser for this PR (go to CloudWatch -> search for 2886 -> select logs for parsers).
3. Verify logs show that the parsers are successfully running.

EREGCSC-2886 Update eCFR/FR parsers to Amazon Linux 2023

---

cdk-eregs/lib/stacks/api-stack.ts
cdk-eregs/lib/stacks/text-extract-stack.ts
solution/backend/resources/utils/aws_utils.py

Resolves part of #2974
In order to convert the text extractor's SQS queue from standard to FIFO, we can't have the eRegs site depending on the queue via exported URL or ARN. This is because in order to do the switch, AWS must delete the old queue and create a new one in its place. Attempting to do this currently will fail as the deploy process won't allow the deletion of a resource that is depended on by a downstream stack.
- Temporarily disable the text extractor by removing imports in the CDK API stack.
- Modify the text extractor calling code to properly display an admin panel error in the case where the text extractor's destination URL or ARN is not configured.
1. Go to the admin panel -> …

EREGCSC-2974-A Temporarily disable the text extractor

---

solution/backend/resources/serializers/citations.py

Resolves #n/a
Because the `SectionCreateSerializer` was a `ModelSerializer` with a `Meta` class referencing all fields, the FR parser was failing because the [recently added](https://github.com/Enterprise-CMCS/cmcs-eregulations/pull/1658) `child_id` field is not included in the request from the parser.
Since this field is set on save anyway, we can simply ignore it by defining the serializer as a `serializers.Serializer` and then manually defining the fields, like we do with many other serializers already.
- `SectionCreateSerializer` switched from a subclass of `ModelSerializer` to `Serializer`.
- Manually defined relevant fields in the new serializer.
I will manually run the FR parser for this …

[hotfix] Fix for FR parser bug: field required for section child_id

---

solution/ui/e2e/cypress/e2e/custom-login-page.cy.js
solution/ui/e2e/cypress/e2e/error-page.cy.js
solution/ui/e2e/cypress/e2e/homepage.spec.cy.js

Resolves [EREGCSC-2979](https://jiraent.cms.gov/browse/EREGCSC-2979)
We recently refactored the loading/disabled states for the Jump To form in the site header.  This has caused some Cypress end to end tests to become flaky, as the tests are expecting to interact with an element that is still disabled when loading data needed to populate a dropdown list in the form.  
In our Cypress configuration, we allow up to two retries (three tries total) before a test fails and moves on to the next test.  This has historically been enough to ensure that the end to end tests don't fail due to random flakiness; if a test fails, it almost always would pass on the first retry.
However, since the Jump To form refactor mentioned above, Cypress tests that interact with the Jump To form have …

EREGCSC-2979 — add cypress intercepts to handle flaky jump to tests

---

.github/workflows/lint-and-test-parsers.yml

Resolves failing [Lint & Unit Test Parsers action](https://github.com/Enterprise-CMCS/cmcs-eregulations/actions/workflows/lint-and-test-parsers.yml)
Dependabot created a [Pull Request to upgrade `dominikh/staticcheck-action` from 1.3.0 to 1.4.0](https://github.com/Enterprise-CMCS/cmcs-eregulations/pull/1728).  The [changelog seemed innocent enough](https://github.com/dominikh/staticcheck-action/compare/v1.3.0...v1.4.0), so we approved the PR and merged it into `main` untested.  
It was untested because this action only runs when golang code is changed or when a PR is merged into `main`, and no golang code was changed in this PR, so this action ran for the first time (and then failed) when the dependabot PR was merged into `main`.
Since the previous version of …

[Hotfix] Revert dominikh/staticcheck-action from 1.4.0 back to 1.3.0

---

solution/backend/resources/admin/internal_resources.py
solution/backend/resources/admin/public_resources.py
solution/backend/resources/admin/resources.py
solution/backend/resources/tests/test_robots_txt.py
solution/backend/resources/utils/aws_utils.py

Resolves #n/a
We have had a field on the resource model, `extract_url`, for a long time. It's purpose so far has been limited to Federal Register links where the user-visible page doesn't extract as well as a non-user-friendly link. However, we can apply this to other resources as well. For example: show a user a friendly web page but index a large PDF that is linked to from that page.
- `extract_url` visible and editable on the admin panel.
- If `extract_url` field changes, it will trigger extraction if auto extract is enabled.
1. Go to a public link and expand the "Search indexing" fieldset.
2. Enter a new URL in to the "Text extraction URL" field and save.
3. After some time, the indexed text …

Make "extract_url" field visible and editable in the admin panel

---

solution/ui/regulations/utilities/utils.js

Resolves `prod` bug
When loading the reader view with the `highlight` query parameter in the URL, certain links would render the reader view without the header or right sidebar.  Those missing elements are a symptom of the main problem, which is that something was causing the Javascript code for the reader view to crash.  
Example: `<prod_url>/42/442/Subpart-A/2024-07-05/?highlight=section%201902,sections,Section,1902#442-1`
- Adds an optional chaining `?` character to the [`HTMLElement` `closest()` method](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest) invocation to guard against an HTML element being `null`.
2. Visit [ephemeral deployment with same …

[HOTFIX] Following link to regs with highlighted text can break Vue

---

.github/dependabot.yml

Updated dependabot configuration
We previously added `*aws*` to our list of directories and patterns in the `package-ecosystem: "npm"` entry of our dependabot config specifically to target AWS CDK updates and allow dependabot to manage updating these libraries.  This worked as expected: pull requests are being created to update AWS CDK libraries and dependencies.
However, AWS CDK dependencies and libraries are updated at a much higher frequency than we anticipated; sometimes multiple times per day.  Since we have a limit of one dependabot PR created per day, the AWS CDK dependencies have been blocking other `npm` updates.  Before adding `*aws*` to our dependabot config, we'd gotten into a successful rhythm of one pull request being created per day; adding `*aws*` has …

[Dependabot] Allow `cdk` updates on different schedule than other `npm` updates

---

.github/workflows/deploy-to-env.yml
.github/workflows/lint-js-ts.yml
.github/workflows/remove-experimental.yml
.github/workflows/test-javascript.yml
.github/workflows/update-cdk-bootstrap.yml
.github/workflows/update-code-json.yml
README.md

Resolves [EREGCSC-2992](https://jiraent.cms.gov/browse/EREGCSC-2992)
eRegs is using Node 20 wherever Node is required.  Node 20 is currently in "Maintenance LTS (Long Term Support)" mode and will be [supported through May 2026](https://nodejs.org/en/about/previous-releases).  We should upgrade to a newer version of Node before that time.
- Updates node versions to the latest current LTS version, which is Node 22.  This will be supported through May 2027.
2. All team members install and use Node 22 LTS ([Jod](https://nodejs.org/en/blog/release/v22.11.0)) locally
- If using Node Version Manager ([nvm](https://github.com/nvm-sh/nvm)), this command will install and use Node 22: `nvm …

EREGCSC-2992 — Upgrade Node to latest LTS

---

solution/backend/regulations/templates/regulations/manual.html
solution/backend/regulations/templates/regulations/obbba.html
solution/backend/regulations/templates/regulations/partials/header.html
solution/backend/regulations/templates/regulations/statute.html
solution/backend/regulations/templates/regulations/subjects.html
solution/backend/regulations/urls.py
solution/backend/regulations/views/obbba.py
solution/ui/e2e/cypress/support/common-commands/header.js
solution/ui/regulations/eregs-vite/src/components/header/HeaderLinks.vue
solution/ui/regulations/eregs-vite/src/router/index.js
solution/ui/regulations/eregs-vite/src/views/Manual.vue
solution/ui/regulations/eregs-vite/src/views/OBBBA.vue
solution/ui/regulations/eregs-vite/src/views/Search.vue
solution/ui/regulations/eregs-vite/src/views/Statutes.vue
solution/ui/regulations/eregs-vite/src/views/Subjects.vue

Resolves [EREGCSC-3000](https://jiraent.cms.gov/browse/EREGCSC-3000)
**This pull request...**
- Adds a new static page for the text of new statute, similar in concept to the State Medicaid Manual table of contents page.
- Links to the new page from the navigation header.
- Embeds a large quantity of hardcoded static HTML in the new page, with scoped CSS. This is an excerpt of a public HTML version of the statute (https://www.congress.gov/119/bills/hr1/generated/BILLS-119hr1eas.html), converted into a more usable format:
- Replaced nested paragraph tags with spans using search-and-replace. Hand-corrected the resulting indenting errors.
- Improved and added links to cross-referenced U.S. Code sections, rules, and regulations.
- Highlighted additions to the Social Security …

EREGCSC-3000 - Add simple page with text of OBBBA

---

cdk-eregs/lib/stacks/static-assets-stack.ts

Resolves n/a
To conform with new policy changes, our CloudFront distributions must be explicitly set to use the `PRICE_CLASS_ALL` price class.
- Explicitly define `priceClass` field in CloudFront distribution properties in CDK.
- Miscellaneous spacing and indenting fixes automatically performed.
1. Green check marks.
2. Log into AWS and go to CloudFront -> Distributions -> Distribution for 1861.
3. Click "Edit" under "Settings" and observe the "Price class" is set to "Use all edge locations (best performance)".

[hotfix] Add explicit price class to CloudFront distributions: PRICE_CLASS_ALL
