Enterprise-CMCS/cmcs-eregulations

- README.md
- load_data.sh
Make sure load_data.sh always takes in the proper amount of inputs.
> EREGCSC-64 load_data.sh takes proper amount inputs

- .gitignore
- config/regulations-core/handler.py
- config/regulations-site/handler.py
- docker-compose.yml
- package-lock.json
- package.json
- serverless.yml
This is a draft of the serverless setup for eRegs.
> EREGCSC-59 draft of serverless configuration for eRegs

- .github/workflows/deploy.yml
- config/regulations-core/serverless.yml
- config/regulations-site/serverless.yml
- config/static-assets/serverless/serverless.yml
- create a role for lambda functions
- use pre-configured vpc and subnets
> Finalize continuous deploy

- .github/workflows/deploy.yml
- .gitmodules
- config/regulations-core/rebuild_index.py
- config/regulations-core/serverless.yml
- run.sh
The search functionality of eregs requires that the `rebuild_pgsql_index` be run when data is added.
> Lambda function to rebuild search index

- guidance/content/regulations/toc-sub-toc.html
- guidance/content/regulations/toc-subgrp-toc.html
- guidance/content/regulations/toc-subjgrp.html
- guidance/content/regulations/toc.html
> EREGCSC-249 Subject Groups should nest in subparts

- e2e/cypress/.gitignore
- e2e/cypress/integration/part.spec.js
- e2e/cypress/integration/search.spec.js
- serverless/regulations-site/cmcs/landing_pages/regulations
- serverless/regulations-site/cmcs/landing_pages/regulations/partials
Include e2e test asserting part view
> [Dependency] Update regulations-core

- README.md
Since people interested in this project may not guess to go visit the wiki without a tip about it.
> Link to wiki from readme

- content/regulations_landing_pages/landing_433.html
- e2e/cypress/integration/part.spec.js
- e2e/cypress/integration/search.spec.js
Regulations site:
- Style updates
- Searched value remains in results page
- Sticky header
- Part information in header
- Jump to Part homepage
Regulations core:
- Base search of sections rather than paragraphs
> Update regulations core and site dependencies

- ecfr-parser/parseXML/parseXML.go
Assumes footnotes exist in sections and subject groups.
> EREGCSC-424 Parse and submit footnotes to the api

- content/regulations_landing_pages/landing_433.html
- e2e/cypress/integration/homepage.spec.js
- e2e/cypress/integration/part.spec.js
Update custom 433 landing page to handle new urls
Depends on:
- https://github.com/CMSgov/regulations-site/pull/70
- https://github.com/CMSgov/regulations-core/pull/15
> EREGCSC-624 Dynamic titles

- serverless/package-lock.json
- serverless/package.json
- serverless/static-assets/serverless/package-lock.json
- serverless/static-assets/serverless/package.json
Looks to fix:
- https://github.com/CMSgov/cmcs-eregulations/security/dependabot/serverless/package-lock.json/lodash/open
- https://github.com/CMSgov/cmcs-eregulations/security/dependabot/serverless/package-lock.json/y18n/open
- https://github.com/CMSgov/cmcs-eregulations/security/dependabot/serverless/static-assets/serverless/package-lock.json/netmask/open
> Update serverless js libraries

- regcore/search/models.py
Return more results with a lower "rank"
> Tune search to be more sensitive

- regulations/static/components/CollapseButton.vue
- regulations/static/regulations/js/CollapseButton.js
- regulations/static/regulations/js/SupplementaryContent.js
- regulations/static/regulations/js/main.build.js
bind collapse button aria-label to name prop and toggle expand/collapse label text based on visible prop
> feat: update aria label for expand/collapse button

- regulations/static/components/Collapsible.vue
- regulations/static/regulations/js/Collapsible.js
- regulations/static/regulations/js/SupplementaryContent.js
- regulations/static/regulations/js/main.build.js
Set height to auto after transition completes
> EREGCSC-748-A   Fix nested categories not expanding correctly

- e2e/cypress/integration/part.spec.js
Changes made for EREGCSC-830 caused some tests to fail; this fixes those failures
> test: update failing tests

- .github/workflows/deploy.yml
- cmcs_regulations/context_processors.py
- cmcs_regulations/settings.py
- e2e/cypress/integration/custom-headers.js
- e2e/cypress/integration/guidance.spec.js
- e2e/cypress/integration/homepage.spec.js
- e2e/cypress/integration/left-sidebar.spec.js
- e2e/cypress/integration/part.spec.js
- e2e/cypress/integration/search.spec.js
- regulations/templates/regulations/base.html
first pass at attempting to pass in ENV variable to app during cypress e2e automated tests that are triggered during the deploy github action
> feat: pass TESTING flag into app during cypress deploy action

- supplementary_content/filters.py
Add distinct() call to queryset filter
> EREGCSC-932 [Admin] Filtering of suppl content not working as expected

- Makefile
- tools/ecfr-parser/ecfr/ecfr.go
- tools/ecfr-parser/eregs/eregs.go
- tools/ecfr-parser/go.mod
- tools/ecfr-parser/go.sum
- tools/ecfr-parser/main.go
- tools/ecfr-parser/parseXML/parseXML.go
Sets log level to trace temporarily to determine nature of github actions failure
> Add detailed logging to parser

- Makefile
- README.md
- regulations/static/components/SupplementalContentCategory.vue
- regulations/templates/regulations/partials/flash_banner.html
- supplemental_content/fixtures/supplemental_content.category.json
- supplemental_content/fixtures/supplemental_content.section.json
- supplemental_content/fixtures/supplemental_content.subcategory.json
- supplemental_content/fixtures/supplemental_content.supplementalcontent.json
Please have a look in the readme and make file for instructions.  With this you can create a DB that is more or less a copy of production for local use.
> Create local database data that resembles production

- tools/ecfr-parser/ecfr/ecfr.go
- tools/ecfr-parser/eregs/eregs.go
- tools/ecfr-parser/main.go
Also added second curl for google to debug network failures
> Increase parser timeout and add retries for individual parts

- regulations/templates/regulations/base.html
This is a really small one liner to just add a meta tag to our base template.
> adding in robots meta tag to the header to try and get bing to remove us

- regulations/templates/robots.txt
Resolves #1032
Changed robots.txt to allow searching instead of blocking it
- robots.txt now has Allow: / instead of Disallow: /
1. Go to url/robots.txt and confirm it says Allow: /
> changed robots.txt to allow all

- cmcs_regulations/settings.py
Resolves #
sets timezone to US/Eastern
- Timezone value in settings.py
1. update any object via the admin panel
2. confirm that the last updated time is in Eastern time
> updating timezone value.

- serverless/serverless-experimental.yml
- serverless/serverless.yml
Resolves #1102
Reduce Bundle Size of Lambdas
- adds some exclusions to the package entry of the serverless file.
Site should look as expected, no missing CSS or JS
In the deploy experimental action it should show a smaller zip file size (was 50 MB not +- 27 MB)
> 1102 - Shrink Lambda Bundle Size

- solution/backend/supplemental_content/admin.py
> Change the order in admin for supplmental

- .github/workflows/deploy.yml
Resolves # deployment script failing on merge
Final issue was that the parser stage was incorrect.  I am optimistic this will resolve the issue.
- parser deployment stage is not dev-PR, but the matrix value.
1. on merge to master the deployment works.
> fixed stage name for parser deployment.

- solution/backend/supplemental_content/migrations/0012_auto_20220223_1557.py
Resolves #
The migrations for adding display_name failed, fixing so it works.
> fixing migrations to not resave models in the migrate command.

- solution/ui/prototype/src/views/CacheExplorer.vue
Ads a delete all button to <prototype>/cache
1. Use the prototype site for a few pages
2. go to <prototype>/cache and select the "Delete All Cache Items" and see all cache items are gone
3. refresh page to confirm
4. repeat as needed
> Delete All Cache Items

- solution/backend/cmcs_regulations/settings.py
- solution/static-assets/requirements.txt
Resolves #
Removes no robots meta tag from http responses.  This will allow search.gov to index our site
- removes no robots meta tag and middleware.
1. in production you should see the following response header value:  x-robots-tag | noindex,nofollow
2. on this branch it should not exist.
> removing no robots meta tag to allow for indexing.

- solution/backend/supplemental_content/serializers.py
- solution/backend/supplemental_content/urls.py
- solution/backend/supplemental_content/views.py
- solution/ui/prototype/src/utilities/api.js
- solution/ui/prototype/src/views/ResourcePage.vue
Resolves # [EREGCSC-1261](https://jiraent.cms.gov/browse/EREGCSC-1261)
A different way of pulling in supplemental content.  This will do it in two phases.  First you get a list of all supplemental content tied to each section/subpart.  Then you  pull all supplemental content by a part listed by its ID.  You take the IDS from the frist pull based on your slection and pull the values of the supplemental content by part.
- The way supplemental content is pulled for the /PDResources page
Go to /pdresources.  Select either a part, subpart or selection.  It will then pull the supplemental content associated with those.  If only a part is selected all supplemental content in the part will be pulled if …
> EREGCSC126

- solution/backend/regulations/templates/regulations/about.html
Resolves [EREGCSC-1344](https://jiraent.cms.gov/browse/EREGCSC-1344)
Fixes issues found in validation
- Adds additional `p` to "About This Tool" section
- Fixes space around external link icon due to template formatting issue
1. Make sure About This Tool section has this sentence above the link to the video demonstration:
a. "All documents on this site are publicly available and compiled from other sources."
2. Make sure the external link icon at the end of certain links does not have a space before it (between the icon and the end of the link text) or after it.
> EREGCSC-1344 - Fix issues found in validation

- .github/workflows/deploy-experimental.yml
Resolves #EREGCSC-1351
Deploys storybook as part of the prototype deploy process
Adds steps for deploying Storybook
Breaks deployment job into pieces to make rerunning more efficient
Just look at the comment on this PR and click the storybook link.
> deploy storybook

- solution/ui/regulations/eregs-vite/src/components/resources/ResourcesFilters.vue
- solution/ui/regulations/eregs-vite/src/utilities/api.js
- solution/ui/regulations/eregs-vite/src/views/Resources.vue
Resolves #
Removes calls to V2 APi for determining sections in favor of more streamlined
V3 endpoints
- How all filters on resources page work
1. Full retest of the resources page.  Almost all of the underlying data changed sources so should be verified.
> Resources v3 filters

- solution/ui/e2e/cypress/integration/part.spec.js
- solution/ui/regulations/js/src/components/SupplementalContent.vue
Resolves #
EREGCSC-1374
Updates the right sidebar for supplemental content if a section is clicked from the main page for part instead of the subpart.
Clicking on the section will update right sidebar to be the section supplemental content
On the main page click on a part.
Now click on a section in the TOC.
Right sidebar will be the sections supplemental content.
Go back and click on a subpart.
Right sidebar will be the subparts supplemental content.
> Get URL in JS to determine if there is a # for sec

- solution/ui/regulations/.storybook/preview.js
- solution/ui/regulations/stories/Collapsible.stories.js
- solution/ui/regulations/stories/Dropdown.stories.js
- solution/ui/regulations/stories/DropdownContent.stories.js
- solution/ui/regulations/stories/DropdownHeader.stories.js
- solution/ui/regulations/stories/DropdownItem.stories.js
- solution/ui/regulations/stories/PartButton.stories.js
- solution/ui/regulations/stories/RelatedRule.stories.js
- solution/ui/regulations/stories/RelatedRuleList.stories.js
- solution/ui/regulations/stories/RelatedRules.stories.js
- solution/ui/regulations/stories/ShowMoreButton.stories.js
- solution/ui/regulations/stories/SupplementalContent.stories.js
- solution/ui/regulations/stories/SupplementalContentCategory.stories.js
- solution/ui/regulations/stories/SupplementalContentList.stories.js
- solution/ui/regulations/stories/SupplementalContentObject.stories.js
Resolves [EREGCSC-1375](https://jiraent.cms.gov/browse/EREGCSC-1375)
Update Storybook so it is easier to understand and use.
This was the result of a timeboxed story.  
Still much to do, like update config and install loaders to be able to display Vue Single File Components that use SCSS/mixins; figure out how to bring in Vuetify-enriched components.
Also TODO: ensure all existing components work correctly.
- Renames, regroups, and re-orders Storybook stories
1. Go to Storybook and look at the left sidebar.  Groupings should be different
> EREGCSC-1375 -- Storybook Updated

- solution/ui/regulations/js/api.js
- solution/ui/regulations/js/src/components/SupplementalContent.vue
Resolves #
1374 feedback
Hides "Show all subpart A resources link if an orphan section is selected.
Fixes the count of supplemental content in a subpart for "Show all subpart {X} resources" number.  Before number was incorrect.
> Eregcsc 1374, Update sidebar based on what they click

- solution/package-lock.json
- solution/package.json
- solution/ui/prototype/src/components/floating_nav/BottomNavBtn.stories.js
- solution/ui/prototype/src/components/floating_nav/BottomNavBtn.vue
- solution/ui/prototype/src/components/floating_nav/BottomNavBtnGroup.stories.js
- solution/ui/prototype/src/components/floating_nav/BottomNavBtnGroup.vue
- solution/ui/prototype/src/components/floating_nav/VerticalRule.vue
- solution/ui/prototype/src/views/Part.vue
- solution/ui/regulations/.storybook/main.js
- solution/ui/regulations/.storybook/preview.js
- solution/ui/regulations/css/scss/_application_settings.scss
- solution/ui/regulations/css/scss/partials/_buttons_and_tooltip.scss
- solution/ui/regulations/package-lock.json
- solution/ui/regulations/package.json
Resolves # 1386
Add sticky buttons to part section and subpart navigation in the prototype
Sticky buttons will be added to the subparts and sections.  If you click on subparts it navigates subparts and if you click section it navigates sections
Click any part on the prototype site.
Select the part tab.  
Click the navigate errors to move forwards and backwards
Click the section tab.
Click the navigate buttons to move forwards and backwards.
> Update button text, Sticky concept, 1386

- solution/ui/prototype/src/components/part/PartToc.vue
Resolves #
EREGCSC-1420
Fixes TOC on the zoom view
Go to the zoom view by having the url host/zoom/title/part
Expand TOC
Click a subpart or section.  it will navigate to the appropriate page
Find an orphan section.  It will navigate to it.
Find a section from a subcategory .   It will navigate to as well.
Go to to the other view host/title/part.  Make sure TOC works as expected as well
> Fix TOC to work on Zoom View

- solution/backend/regcore/serializers.py
- solution/backend/regcore/urls.py
- solution/backend/regcore/v3views.py
Resolves # EREGCSC-1436
Creates Synonym endpoint
Go to swagger.  
Find the endponit synonym/{synonym}
Type in ABP or any other word that will give  a result from the Synonym model.
Verify it matches swaggers return.
> EREGCSC-1436 Creating synonym endpoint

- solution/backend/regulations/templatetags/string_formatters.py
Resolves #
Fixes issue with "View Section XX Resources" all showing 0 resources
> fixing simple section formatter

- solution/backend/regulations/templates/regulations/partials/sidebar_right.html
- solution/ui/regulations/js/src/components/SupplementalContent.vue
Resolves #
Adds resource button for right sidebar.  Clicking it will take you to the resources page with either the section or subpart, and sections prefiltered
Select a part on the main page TOC.
Select a section or subpart.
On the right sidebar you should see a "Search These Resources" button.  Click that.  And it will redirect you to the resources page with either the section you selected or the subpart you selected prefiltered.
> EREGCSC-1371 Resoure button for sidebar

- .github/CODEOWNERS
> removing myself from codeowners file.

- solution/backend/resources/admin.py
Resolves # EREGCSC-1486
Bulk locations was having an issue if there were sections or subparts using bulk title and not bulk title
Put bulk title of 42 on the admin for locations.  Add a valid location without a title in bulk title and one with.  Hit save and continue.  Should work as expected now.
> Fixes bulk locations bug

- .github/CODEOWNERS
> Add Parissa to CODEOWNERS file

- solution/backend/regulations/templates/regulations/partials/header/reg-title.html
- solution/backend/regulations/views/resources.py
- solution/ui/regulations/css/scss/partials/_header.scss
Resolves #
EREGCSC-1500
Adds the view resources button to all pages except for  the resources ppage
Go the following pages and see if the "View Resources" Button appears in the toolbar
"/" home page
"/about"
"/search"
Go to "/resources" and verify that the button is not there
> EREGCSC-1500 Add view resource button to pages

- solution/ui/regulations/js/src/components/SupplementalContentList.vue
Resolves # EREGCSC-1523
An attempt to fix google analytics
Surface level changes toremove the redirect.  Leaving in most of the stuff for it until the issue is fully resolved.  Need to test this on prod to verify it works correctly.
> EREGCSC-1523 removing redirect url from sup content

- solution/ui/regulations/eregs-vite/src/components/resources/ResourceExportBtn.vue
- solution/ui/regulations/eregs-vite/src/components/resources/ResourcesResults.vue
Resolves #
Various issues with CSV format.   Search query was not being applied to the csv results.  Fixed the format of the locations for subparts and sections.
Search query is applied to the csv results
Location string is reorganized to be in the format for "Title CFR Part.SEction" or "Title CFR Part subpart Subpart"
Go the resources page.
Do a search for something like "covid".
Download CSV.  The results should be similar to the output on the resources page.
Look in the CSV.  Look at the locations.  Check the format of the locatiosn
> EREGCSC-1559 Download CSV bugs

- solution/backend/resources/admin.py
Resolves #
EREGCSC-1568
Adds a list of supplemental content and fr docs to the sections and subpart view to see if there is anything linked to it.  There will be a list of hyper links on the pages
The section and subpart pages in the admin to include list of links for supplemental content
Go to sections in the admin panel.
Click a section that has either supplemental content or fr docs linked to it.
Click the hyperlinks that would be linked to the content.
Profit
> EREGCSC-1568 Display list of related items

- solution/ui/regulations/eregs-vite/src/components/resources/ResourceExportBtn.vue
Resolves #570 
CSV was not matchin search results do to fr-grouping and title 45 being included
Go to the resources page and search for anything like "covid".
Download the csv.
The same amount of results should appear.  You can also verify by looking at the api calls.  It should be the same, provided it is less than 100 results.
> EREGCSC-1559 fix of not matching csv

- solution/backend/regulations/templates/regulations/search.html
- solution/backend/regulations/templatetags/string_formatters.py
- solution/backend/regulations/views/reader.py
- solution/static-assets/requirements.txt
- solution/ui/e2e/cypress/integration/part.spec.js
- solution/ui/e2e/cypress/integration/search.spec.js
- solution/ui/regulations/css/scss/_application_settings.scss
- solution/ui/regulations/css/scss/partials/_reg_text.scss
- solution/ui/regulations/js/main.js
- solution/ui/regulations/js/utils.js
Resolves [EREGCSC-1538](https://jiraent.cms.gov/browse/EREGCSC-1538)
Spike to show basic implementation of highlighting text in regulations reader view when being linked from the Search Results page.
- Adds search param to reader view URL when coming from the search page
- highlights text in targeted section (via hash in URL) in a case-insensitive way using JS
1. Go to `/search` and search for something
2. Follow a search result link into reg text reader view
3. See that text highlighted within the targeted section
> EREGCSC-1538 [Spike] Highlight search text in regs

- solution/ui/regulations/eregs-vite/src/components/resources/ResourceExportBtn.vue
- solution/ui/regulations/js/src/components/SimpleSpinner.vue
Resolves #ERGECSC-1541
When the download csv button is clicked on the resources page, a spinner replaces the text.  When it is finished downloading it goes away.
Go the resources page.
Click download CSV.  
As it is donwloading the text will appear and a spinner will take its place.
When it is done it will go back to the text.
> EREGCSC-1541 Adding spinner to export CSV

- solution/backend/cmcs_regulations/settings.py
Resolves production issue where CSP didn't have needed variables.
> fix: add needed values to CSP

- solution/ui/e2e/cypress/integration/api.spec.js
- solution/ui/e2e/cypress/integration/resources.spec.js
- solution/ui/regulations/eregs-vite/src/utilities/api.js
Resolves #[EREGCSC-1526](https://jiraent.cms.gov/browse/EREGCSC-1526)
**Description- Resources page filters out FR docs not linked to any part/section**
**This pull request changes...filtering only title 42 during serach**
Visit [Resources with this search term](https://gtldeyh932.execute-api.us-east-1.amazonaws.com/dev586/resources/?q="Identifying%20Medicaid%20and%20CHIP%20Beneficiaries"&sort=newest)
expected results:  You should see results from the search.
> remove hard coded title 42

- solution/backend/resources/v3serializers/resources.py
> Fix NoneType error

- solution/backend/regcore/search/fixtures/search.synonym.json
- solution/backend/resources/fixtures/resources.category.json
- solution/backend/resources/fixtures/resources.federalregisterdocument.json
- solution/backend/resources/fixtures/resources.federalregisterdocumentgroup.json
- solution/backend/resources/fixtures/resources.resourcesconfiguration.json
- solution/backend/resources/fixtures/resources.section.json
- solution/backend/resources/fixtures/resources.subcategory.json
- solution/backend/resources/fixtures/resources.subpart.json
- solution/backend/resources/fixtures/resources.supplementalcontent.json
Resolves #
- Updated fixtures from production for local development
1. Run `make local.seed` and make sure nothing bad happens
> Update fixtures to November 2022

- solution/backend/serverless.yml
- solution/docker-compose.yml
> EREGCSC-1670 Updates to docker file and yml file to match prod

- solution/backend/serverless.yml
> changes made to update postgres Family

- solution/_templates/scripts/delete_orphandbs.sql
This is the shell for what to do for deleting things.  
First command will get the list of databases, then we will just run the script one at a time until all the ones we know are not being used are gone.  We should not run a loop or a lambda for deleting them. Just do it once at a time, save some potential headaches.  You must already be connected to the main database to run these commands and you should not delete a database you are currently connected to.  Connect to the main one.
> Db script format for deletion

- solution/ui/e2e/cypress/support/e2e.js
An issue with cypress-axe attempt at fixing.
> attempt at fixing cypress

- .github/workflows/deploy-experimental.yml
- .github/workflows/deploy.yml
- solution/ui/e2e/package-lock.json
> Nodeupgrade github actions

- .github/workflows/deploy.yml
- solution/backend/serverless.yml
Resolves #690 
Creates a changeset to remove the db from the environment
- A changeset will be created for each environment to remove the db from cloud formation
> EREGCSC-1702- Encrypt database at rest - Update Template remove db

- .github/workflows/deploy.yml
Resolves #EREGCSC-1702
Placement of parameter was causing an issue.  Changed placement
- Allows deploy to work on servereless by moving the paramter put into serverless.
On deploy to dev it will work
> EREGCSC-1702 Change placement of param, causing issue on deploy

- .github/workflows/deploy-experimental.yml
- .github/workflows/deploy.yml
- solution/backend/package-lock.json
- solution/backend/package.json
- solution/backend/serverless-experimental.yml
- solution/backend/serverless.yml
Resolves # EREGCSC-1743
The removal step for the application is failing due to changesets.  Removing changesets fixing the issues
- Changesets are removed for automatically happening through AWS
- Remove-experimental works again
1. Open a PR
2. Close a PR after it finishes deployment steps
3. Close the PR.  Remove should be successful.
> EREGCSC-1743 Remove-Experimental failing

- solution/backend/aws_resources/waf.yml
- solution/backend/package-lock.json
- solution/backend/package.json
- solution/backend/serverless-experimental.yml
- solution/backend/serverless.yml
Resolves # [EREGCSC-1683](https://jiraent.cms.gov/browse/EREGCSC-1683)
API Gateway should be associated with a WAF Web ACL
Updates serverless.yml and experimental-serverless.yml files to add a Web ACL  and associate it to the api gateway.
more details here:
https://docs.aws.amazon.com/console/securityhub/APIGateway.4/remediation
https://www.serverless.com/framework/docs/providers/aws/guide/variables
https://www.serverlessguru.com/blog/connecting-aws-waf-to-api-gateway-via-serverless-framework
- Web ACL created
- Web ACL associated with api gateway
1. go to AWS dev and visit https://us-east-1.console.aws.amazon.com/wafv2/homev2/web-acls?region=us-east-1
2. click on Web ACLs in the left nav
3. …
> Ereggcsc 1683 api gateway waf

- solution/static-assets/serverless.yml
Resolves #EREGCSC1689
Adding a rule to cloudwatch firewall.  US terrirories only
- EREGS will only be accessible in the US
Will be able to access it within the US.
> EREGCSC-1689: adding rule for firewall

- solution/backend/serverless-experimental.yml
- solution/backend/serverless.yml
Resolves # 1785
This pull request ensures API Gateway  X-Ray Tracing is enabled
serverless.yml
serverless-experimental.yml
- expected change 2
go to reviewed API [dev732-cmcs-eregs-site](https://us-east-1.console.aws.amazon.com/apigateway/home?region=us-east-1#/apis/74sxkb8xt8/resources) > Stages >dev732 > Logs/Tracing X-Ray Tracing is enabled
> add xray-tracing to api gateway

- solution/backend/resources/tests/test_resources_endpoints.py
Resolves #n/a
Forgot to update the name of the test case
- Updated the name of the test case
1. n/a
> Fix name of test case

- solution/backend/regcore/search/models.py
- solution/backend/regcore/search/serializers.py
- solution/ui/regulations/eregs-vite/src/utilities/api.js
Resolves # EREGCSC-1824
Fixes phrase search to be more accurate for  regs search.  Our current implementation, had some slight flaws in logic that would possibly cause it to not pull in correctly.
- Phrase searches will have a lower ranking relevancy that allows more results to flow in.
Do a phrase search "X-Ray Services".
Regs should have a good results, and if a title has the search query in it, it will be first.
> EREGSCSC-1824 phrase fix

- solution/backend/regulations/templates/regulations/homepage_prototype.html
- solution/backend/regulations/urls.py
- solution/backend/regulations/views/homepage_prototype.py
Resolves # EREGCSC-1826
Creates an alternate path for homepage.  Page just says hello world, will be used for prototype design of home.
- Adds a new route that will be used for testing the new homepage
> EREGCSC-1826 Create base template for alternate homepage

- solution/backend/regulations/templates/regulations/homepage_prototype.html
- solution/ui/regulations/css/scss/partials/_site_homepage_update.scss
- solution/ui/regulations/eregs-component-lib/src/components/shared-components/LeftNavCollapse.vue
- solution/ui/regulations/eregs-component-lib/src/components/shared-components/TOC/Toc.vue
Resolves [EREGCSC-1550](https://jiraent.cms.gov/browse/EREGCSC-1550)
Add Hero content to updated homepage.
- Link to YouTube video demonstration video
- Descriptive text about eRegs with link to About page
- Adds Hero content and styles
- Adds image to S3 site assets buckets for experimental deployment and `dev`/`val`/`prod`
1. Visit experimental deployment
2. Make sure video link sends you to [correct YouTube video](https://www.youtube.com/watch?v=dqy8WCFedU4)
3. Make sure Learn About This Tool button takes you to the About page
4. Compare styles to [Figma](https://www.figma.com/file/Gx6pz0IxWqGsweFVdezKNe/eRegs-Homepage---Multi-View-Update?type=design&node-id=3872-12839&t=fKZz3jQAr5E0PbxP-0)
> EREGCSC-1550 -- Updated Homepage Hero Video

- solution/ui/e2e/cypress/e2e/error-page.cy.js
- solution/ui/e2e/cypress/e2e/homepage.spec.cy.js
- solution/ui/regulations/css/scss/partials/_header.scss
- solution/ui/regulations/css/scss/partials/_jump_to.scss
- solution/ui/regulations/eregs-vite/src/components/JumpTo.vue
update code so that title 45 is available
Resolves #1877
"Jump to" on prod enables switching between 45 and 42
https://0qpyhhpce0.execute-api.us-east-1.amazonaws.com/dev820
Select title 45 and select various combinations of parts and sections and make sure that it works
> EREGCSC-1877-enable-jump-to

- .github/workflows/deploy.yml
Resolves # EREGCSC1912
Typo on the deploy.yml that had a bad structure.  This fixes it.
- Deploy.yml will be correct
1. Once approved  deploy.yml will be correct
> EREGCSC-1912 Fix github action for run pytest

- .github/workflows/deploy.yml
Resolves # EREGCSC-1912
Issue with deploy.yml using pytest.  Removing it from the flow.  Still on the experimental deploy so pytest are still being ran and code is not envirnoment depenedent.
- Removes pytest from deploy.yml
1. Deploy no longer includes pytest
> EREGCSC-1912 removing pytest from deploy.yml

- solution/backend/populate_content.py
Resolves # EREGCSC-1951
- How tables are deleted when data is being repopulated
1. Build pr
2.  make small change to PR
3. See if build works
4. Keep an eye out for the errro poping up.  Its a little random
> EREGCSC-1951-rebuild pr fix

- solution/backend/common/fields.py
Resolves #n/a
Adds a new field, VariableDateField, to the `common.fields` module.
- Adds a new field, VariableDateField, to the `common.fields` module.
n/a
> Add VariableDateField

- solution/backend/regulations/migrations/0008_statutelinkconfiguration.py
Resolves #
Migration conflict caused dev deploy to fail. Renaming the conflicting migration file should fix it. Ensure this passes deployment to dev before doing anything else.
> Fix migrations

- solution/static-assets/requirements.txt
Resolves #adding precommit
This pull request adds pre-commit to our requirements.txt so that we check for secrets locally before pushing code to the repo
push code to the repo and see that it runs the precommit
> add pre-commit

- .github/workflows/deploy-experimental.yml
- .github/workflows/deploy.yml
Resolves #  EREGCSC-2062
The way the conditional was applied on deploy.yml was not correct.  Fixed the logic
- The prod step will only run on prod.  The dev step will only run on dev.
- 
1. On dev and val the prod step will not run but the other step will  
2. On prod the prod step will run but not the val one.
> Eregcsc 2062 update prod conditional

- solution/backend/serverless-experimental.yml
- solution/backend/serverless.yml
> s3 bucket policy removal

- solution/backend/file_manager/admin.py
- solution/backend/file_manager/models.py
- solution/backend/file_manager/tests/test_models.py
- solution/backend/file_manager/views.py
- solution/backend/serverless-experimental.yml
- solution/backend/serverless.yml
- solution/ui/regulations/eregs-vite/src/views/PolicyRepository.vue
Resolves # EREGCSC 2216 
Block public access on s3 buckets for file manager.  The settings are set to false for blocking currently.  Just need to be changed to true in serverless.
- public access will be blocked on our internal documents s3 buckets
1. log into the admin panel.
2. Upload an internal document.
3. Download the document.
> EREGCSC-2216 S3 block public access

- solution/backend/serverless_functions/prod_functions.yml
Resolves #
- Adds content index to prod.  Doesnt run it.
1. When the deploy gets to prod, the lamda is just added.  It isnt run.
> hot add add prod index

- .github/workflows/deploy-experimental.yml
- .github/workflows/remove-experimental.yml
- solution/backend/serverless-experimental.yml
- solution/backend/serverless.yml
Resolves # ERERGCSC-2257
Remove text extractor from deploy-experimental and update the lambda for serverless to allow invoking lambdas
- Removes text extractor from serverless experimental
- allow the environments to access the lambda
1. text extractor isnt made for experimental environment.
2. Extractor can be invoked in higher environments
> Hotfix: remove textexractor 2357

- solution/ui/regulations/eregs-vite/src/components/policy-repository/PolicySelections.vue
Resolves # EREGCSC-2350
Add tolowercase to the subject chips sorting.  Was missed on previous PR
- The chips  that are added that are selected had to get a capitalization check.  The ordering is somethign that is only done on the front end.
> EREGCSC-2350 add to lowercase to subjct sorting on front end

- .github/workflows/deploy-experimental.yml
- .github/workflows/deploy.yml
Resolves issue preventing deployment
A [Snyk-created Pull Request](https://github.com/Enterprise-CMCS/cmcs-eregulations/pull/1062) illuminated a vestigial and unused `package.json` file.  That file was removed along with its corresponding `package-lock.json` file, but unfortunately this caused the `deploy text extractor lambda` job in `deploy.yml` to fail.
After some investigation, it appears there is an unecessary `npm install` command in the `depoy text extractor lambda` job instructions:
```
- name: deploy text extractor lambda
run: |
pushd solution/text-extractor
npm install serverless -g
npm install
serverless deploy --stage ${{ matrix.environment }}
popd
```
There is no `package.json` file in `solution/text-extractor`, but there previously had been one in the parent …
> [Hotfix] Remove unnecessary npm install command

- solution/backend/content_search/models.py
Resolves # EREGCSC-2339 Increase minimum words for headlines
Increasing headlines from 30 minimum to 50 characters.
- Increase amount of characters on headlines from 30-50
> EREGCSC-2339 Expand minimum words on headlines

- .github/workflows/schedule-jira-sync.yml
Resolves # [EREGCSC-2418](https://jiraent.cms.gov/browse/EREGCSC-2418)
Enhancement of GitHub Workflow for SecurityHub-to-Jira Sync with Low Priority Issue Creation
Workflow for SecurityHub-to-Jira Sync to now create Low Priority Issues
1. steps to view and verify change: Check for the existence of a JIRA ticket if a low severity finding in Security Hub is 24 hours or older.
> EREGCSC-2418 - Modify SecurityHub Jira Sync to Generate Low-Priority Issues

- README.md
- solution/Makefile
- solution/backend/regcore/search/readme.md
- solution/backend/serverless_functions/readme.md
- solution/text-extractor/README.md
Resolves # EREGCSC-2419
Adding some documentation to the readmes over various things.  How our regulations full text search works, information regarding serverless functions, a little to the text extractor.
- Adds documentation
- Removed make python.unittest(does not work, use test.pytest instead)
1. Read it make sure it sounds ok to you.
> EREGCSC-2419 Documentation for processes

- .github/workflows/deploy-experimental.yml
- solution/backend/serverless-experimental.yml
Resolves #n/a
Removes text extractor experimental deploy
- Removes text extractor experimental deploy
1. Verify the PR deploys but text extractor step is skipped
> [hotfix] Remove text extractor from experimental deploy

- solution/backend/file_manager/admin.py
Resolves # EREGCSC-2345
Changes the drop down for the uploaded file admin categories.
1. Go to the link below and login.
https://znn4ai0a90.execute-api.us-east-1.amazonaws.com/dev1114/admin/file_manager/uploadedfile/1/change/
2.  Scroll down to the category field
3.  Field should show categories and subcategories with the proper description next to them.( It used to say abstract upload category but now it will say either sub category or category)
> EREGCSC-2345 - Admin dropdown correction for dropdown

- .github/CODEOWNERS
Resolves # My time on eregs
Onto a new team
- A part of me
1. Everything and nothing.
> Removal of Thomas Walker from owners.

- README.md
Just small changes to tidy up the readme and make it a little easier to read.
* Fix broken status badge
* Adjust section headers to keep related items together
* Use standard capitalization for proper nouns including Docker, Django, Cypress, Postgres, Lambda, etc.
* Add commas and periods as needed
* Add header for CMS SSO information
View the diff and preview the updated readme: https://github.com/Enterprise-CMCS/cmcs-eregulations/blob/7cb1e2e8c415b9b4a628d56e4945a636ece8c1e8/README.md
Check whether I made anything worse or introduced any errors.
> [No ticket number] Copyedits for readme

- solution/backend/serverless.yml
Resolves # Fixes deployment of EREGSCS-2456
typo in log_file_mode
1. spelling of log_file_mode is correct.
2. deploys correctly on dev.
> HOTFIX - EREGSCS 2456 update parameter group values

- solution/backend/serverless.yml
Resolves #EREGSCS-2456
Remove the log_file_mode since serverless is having issues with it. 
removed the log_file_mode
has to be deployed to dev rds to see if the changes.
> hotfix-Eregcsc 2456 update parameter group values

- .github/workflows/deploy.yml
Resolves #n/a
For our code freeze we want to only deploy new code to dev.
- Removes val and prod from deploy.yml
1. Approve and merge this PR. Deploy should only occur in dev.
> [Temporary] Deploy to dev only for code freeze

- .github/workflows/deploy.yml
Resolves #n/a
Penetration testing is complete so we can deploy to val and prod again.
- Allows deploy to prod.
1. Approve and merge this PR and make sure it goes all the way through to prod.
> [hotfix] Allow deploy to prod 

- solution/backend/cmcs_regulations/settings/deploy.py
- solution/backend/serverless.yml
Resolves #
database timeout issues. 
increase database timeout to resolve the issue of some complex db queries taking too long and timing out.
adds timeout of 20 seconds for the database. 
> [hotfix] - Add a db timeout of 20 seconds

- solution/backend/content_search/views.py
Resolves #2598
New search code failed on deployment because it was still generating headlines for all results instead of only the current page. 
- Force pagination of the queryset _before_ generating headlines
1. Green check marks.
2. Make sure `/v3/content-search/?q=test` and `/v3/content-search/?q=test&paginate=false` both do not fail.
3. Check if searching for "test" works properly on dev and val before deploying to prod.
> [hotfix] EREGCSC-2598-B Paginate before generating headlines

- solution/backend/content_search/models.py
- solution/backend/content_search/tests/test_search.py
Resolves #2598
The `search_query` variable was being defined as two different things in search: first as a string containing the raw text of the query, and then as a Django `SearchQuery` object. This led to me forgetting to include it while generating headlines.
- Made a method in the ContentIndex queryset to create the `SearchQuery` object.
- Used a different name for this variable to avoid future confusion.
- SearchHeadline now uses this object instead of the raw string, as intended.
Test highlighting on a search query and ensure all instances are highlighted. [See here](https://4k5cpzavkb.execute-api.us-east-1.amazonaws.com/dev1233/v3/content-search/?html_api&q=affordable+care+act). Before, …
> [hotfix] EREGCSC-2598-C Fix search query configuration while generating headlines

- solution/backend/content_search/models.py
Resolves #2622
The `search_configuration` method of the `ContentIndexQuerySet` model was being called on each search, however all it did was overwrite the default values (defined as class attributes) if a search query was quoted, rather than explicitly set the attributes for each search.
This caused undefined behavior because it assumed that the queryset instance was being deleted or reset between searches. This is apparently not always the case. In the more rare occasions in which the queryset instance gets reused, a previous quoted search would cause a current non-quoted search to be treated as quoted, thus reducing the result count or eliminating it entirely.
- Removed `search_configuration` method and replaced with simpler `is_quoted` …
> EREGCSC-2622 Fix for "Inconsistent number of search results" bug

- .github/workflows/snyk-test.yml
changes the name of GA in snyk workflow
check if the snyk action runs successfully
> updated snyk github action name

- solution/backend/cmcs_regulations/settings/base.py
- solution/static-assets/requirements.txt
Resolves #EREGCSC-2218
Upgrades pyopenssl and cryptopgraphy
- update requirements.txt with the upgrade version. 
Verify tests are passing
Ensure login to EUA still works fine
Poke around the site make sure everything works.
> EREGCSC-2218 - Upgrade openssl and cryptography

- solution/backend/regcore/views/history.py
> [hotfix] Add timeout to httpx client to satisfy linter

- .github/workflows/deploy-experimental.yml
Resolves #
This pull request updates the deploy-experimental workflow YAML to exclude the maintenance Lambda function, as it is not needed in the experimental environment.
Update the deploy-experimental workflow YAML to exclude the deployment of the maintenance Lambda function.
1.  Check code see its been removed from deploy-experimental.
2. Notice the lambda function is not there on experimental anymore.
> remove maintenance from experimental

- .gitignore
- README.md
Small updates made to README file to reflect actual process of backing up and locally restoring a database on a fresh machine.
- Updates README file with informative additions and asides based on experience
1. README makes sense and looks good
> [Tech Debt] README updates based on DB backup experience

- README.md
- solution/backend/scripts/backup_db.sh
Resolves # Making the backup easier.
This pull request enables you to dump production data to your local environment using AWS CLI credentials. It eliminates the need to manually enter credentials, as the process is automated once you sign into AWS.
- expected change 
Update the backup script. 
1. Follow the Directions in the README:
2. Refer to the README file included in this pull request for detailed instructions.
3. Execute the backup script as outlined in the README.
4. Verify the backup.
> update the backup script to use aws

- solution/Dockerfile.template
- solution/backend/serverless-experimental.yml
- solution/backend/serverless.yml
- solution/ui/e2e/cypress/schemas/example-schema.js
Resolves # 2619 
Update the code base to remove any remaining references to serach.gov since we do not use it anymore. 
serverless files
docker files
cypress fixtures files
Steps to view and verify change
- ensure the removal of code referencing search.gov is not breaking anything by clicking on the website.
> EREGCSC - Remove Searchgov from the code

- .github/workflows/deploy-experimental.yml
- .github/workflows/javascript-test.yml
- README.md
- solution/Makefile
- solution/ui/regulations/eregs-vite/src/components/subjects/SubjectSelector.test.js
- solution/ui/regulations/package-lock.json
- solution/ui/regulations/package.json
- solution/ui/regulations/utilities/utils.test.js
- solution/ui/regulations/vitest.config.ts
Resolves [EREGCSC-2004](https://jiraent.cms.gov/browse/EREGCSC-2004)
Add Vitest unit tests to CI/CD workflow.
- Creates `javascript-test` workflow to be run on:
- pull request `opened`, `synchronize`, `reopened`
- `push` on `main` branch
- Adds Deploy Status and CodeQL status badges to README.md based on badging examples from peer Enterprise-CMCS repositories
- Examples [1](https://github.com/Enterprise-CMCS/macpro-mdct-seds), [2](https://github.com/Enterprise-CMCS/managed-care-review), [3](https://github.com/Enterprise-CMCS/macpro-mako)
1. Green check marks (including new JavaScript Unit Tests with Vitest workflow!)
2. Look through Github Actions logs to ensure that JavaScript Unit Tests with Vitest …
> EREGCSC-2004 -- Implement Vitest into our build pipeline

- cdk-eregs/lib/stacks/api-stack.ts
- solution/backend/handler.py
- solution/backend/requirements.txt
> ERERCSC-2859 Custom WSGI handler to replace Mangum

- .github/workflows/deploy-cdk-dev.yml
- cdk-eregs/lib/constructs/database-construct.ts
> Eregs-2859: Remove duplicate cfn output

- solution/backend/authorizer.Dockerfile
- solution/backend/createdb.Dockerfile
- solution/backend/createsu.Dockerfile
- solution/backend/dropdb.Dockerfile
- solution/backend/empty_bucket.Dockerfile
- solution/backend/migrate.Dockerfile
- solution/backend/regsite.Dockerfile
> Fix name of requirements.txt

- cdk-eregs/lib/stacks/redirect-stack.ts
Resolves #n/a
CUSTOM_URL param is missing from the redirect lambda's environment, causing it to fail with a 500 error.
- For prod only, add the CUSTOM_URL parameter to the lambda's environment.
1. Approve and deploy to dev, val, and prod
2. Go to the redirect lambda URL and verify it redirects, no 500 error
> [hotfix] Include custom_url param in redirect lambda environment
